package com.picalibrary.android;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.*;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import java.util.*;
import java.util.concurrent.*;

/** Creator works over provider bindings. Core retrieval is Pica + E-H; ExH is optional. */
public final class AuthorWorksActivity extends Activity {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private String conceptId="",sourceMode="all";private TextView status;private RecyclerView list;private boolean destroyed,refreshing;private AuthorConceptStore.Concept concept;
    @Override public void onCreate(Bundle saved){super.onCreate(saved);Ui.applyWindow(this);conceptId=safe(getIntent().getStringExtra("authorConceptId"));AuthorConceptStore.Snapshot snapshot=AuthorConceptStore.build(this);concept=snapshot.get(conceptId);renderShell();renderWorks();refreshOnline();}
    private Button compact(String label,android.view.View.OnClickListener action){return Ui.button(this,label,action,true);}
    private void renderShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(Ui.dp(this,8),Ui.dp(this,6),Ui.dp(this,8),Ui.dp(this,4));bar.addView(compact("‹ 返回",v->finish()));bar.addView(Ui.text(this,concept==null?"作者作品":concept.canonicalName,21,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));bar.addView(compact("↻",v->refreshOnline()));root.addView(bar);HorizontalScrollView scroller=new HorizontalScrollView(this);LinearLayout filters=new LinearLayout(this);filters.setPadding(Ui.dp(this,12),0,Ui.dp(this,12),Ui.dp(this,2));addFilter(filters,"全部","all");addFilter(filters,"Pica","pica");addFilter(filters,"E-H","eh");if(EhCapabilityStore.load(this).available())addFilter(filters,"ExH","exh");scroller.addView(filters);root.addView(scroller);status=Ui.text(this,"",12,Ui.MUTED,false);status.setPadding(Ui.dp(this,14),Ui.dp(this,3),Ui.dp(this,14),Ui.dp(this,3));root.addView(status);list=new RecyclerView(this);list.setLayoutManager(new LinearLayoutManager(this));list.setItemAnimator(null);list.setPadding(Ui.dp(this,6),0,Ui.dp(this,6),Ui.dp(this,16));root.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);root.requestApplyInsets();}
    private void addFilter(LinearLayout parent,String label,String value){Button b=compact(label+(sourceMode.equals(value)?" ✓":""),v->{sourceMode=value;renderShell();renderWorks();refreshOnline();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,0,Ui.dp(this,6),0);parent.addView(b,lp);}
    private void renderWorks(){AuthorConceptStore.Snapshot authors=AuthorConceptStore.build(this);AuthorConceptStore.Concept updated=authors.get(conceptId);if(updated!=null)concept=updated;if(concept==null){status.setText("作者信息已变化，请返回作者列表重新选择");list.setAdapter(new UnifiedComicCollectionAdapter(this,UnifiedComicCollectionAdapter.MODE_LIST,Collections.emptyList(),null));return;}UnifiedCatalogStore.Snapshot catalog=UnifiedCatalogStore.load(this);LinkedHashSet<String> ids=new LinkedHashSet<>();if("all".equals(sourceMode))ids.addAll(concept.comicIds);else for(AuthorConceptStore.Binding b:concept.bindings)if(bindingMatches(b,sourceMode))ids.addAll(b.comicIds);ArrayList<UnifiedCatalogStore.Entry> items=new ArrayList<>();for(String id:ids){UnifiedCatalogStore.Entry e=catalog.byId.get(id);if(e==null)continue;if("eh".equals(sourceMode)&&!e.sourceBindings.contains("eh"))continue;if("exh".equals(sourceMode)&&!e.sourceBindings.contains("exh"))continue;if("pica".equals(sourceMode)&&!(e.picaAvailable||e.sourceBindings.contains("pica")||"pica".equals(e.providerId)))continue;items.add(e);}items.sort((a,b)->safe(b.updatedAt).compareTo(safe(a.updatedAt)));status.setText((refreshing?"正在刷新在线作品 · ":"")+items.size()+" 部已识别作品 · "+AuthorConceptStore.sourceLabel(concept));list.setAdapter(new UnifiedComicCollectionAdapter(this,UnifiedComicCollectionAdapter.MODE_LIST,items,this::open));}
    private boolean bindingMatches(AuthorConceptStore.Binding b,String mode){return "pica".equals(mode)?"pica".equals(b.providerId):("eh".equals(mode)||"exh".equals(mode))&&"eh".equals(b.providerId);}
    private void refreshOnline(){if(refreshing||concept==null)return;refreshing=true;renderWorks();worker.submit(()->{try{if(("all".equals(sourceMode)||"pica".equals(sourceMode))&&PicaAccountStore.load(this).configured()){try{PicaClient.ComicPage page=new PicaClient(this).search(AuthorConceptStore.queryForPica(concept),1,"ld",Collections.emptyList());UnifiedPicaCatalogSync.mergeAll(this,page.comics);}catch(Exception ignored){}}if("all".equals(sourceMode)||"eh".equals(sourceMode)){try{List<EhClient.Comic> rows=new EhClient(this).search(AuthorConceptStore.queryForEh(concept),"eh");UnifiedEhCatalogSync.mergeAll(this,rows);}catch(Exception ignored){}}if(("all".equals(sourceMode)||"exh".equals(sourceMode))&&EhAccountStore.load(this).configured()){try{EhCapabilityStore.Snapshot capability=EhCapabilityStore.refresh(this,false);if(capability.available()){List<EhClient.Comic> rows=new EhClient(this).search(AuthorConceptStore.queryForEh(concept),"exh");UnifiedEhCatalogSync.mergeAll(this,rows);}}catch(Exception ignored){}}}finally{runOnUiThread(()->{if(destroyed)return;refreshing=false;AuthorConceptStore.Snapshot next=AuthorConceptStore.build(this);AuthorConceptStore.Concept c=next.get(conceptId);if(c!=null)concept=c;renderWorks();});}});}
    private void open(UnifiedCatalogStore.Entry entry){Intent i=new Intent(this,UnifiedComicDetailActivity.class);i.putExtra("comicId",entry.id);i.putExtra("title",entry.title);i.putExtra("author",entry.displayAuthor());startActivity(i);}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
    private static String safe(String value){return value==null?"":value;}
}
