package com.picalibrary.android;

import android.content.Context;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.regex.*;
import javax.net.ssl.SSLException;
import org.json.*;

/** E-H public client with optional encrypted cookie-session account capabilities. */
final class EhClient {
    static final String ORIGIN="https://e-hentai.org",EXH_ORIGIN="https://exhentai.org",API="https://api.e-hentai.org/api.php";
    private static final String UA="Pica-Library-Android/0.1";
    private static final long SEARCH_INTERVAL_MS=3100L;
    private static long lastSearchAt;
    private final Context context;
    EhClient(Context context){this.context=context.getApplicationContext();}

    static final class Comic {
        final String id,remoteId,title,alternateTitle,author,circle,coverUrl,category,uploader,completionStatus;
        final List<String> tags,rawTags,authors;
        final int pagesCount;final double rating;final long posted,filesize;
        Comic(String id,String remoteId,String title,String alternateTitle,String author,String circle,String coverUrl,String category,String uploader,String completionStatus,List<String> tags,List<String> rawTags,List<String> authors,int pagesCount,double rating,long posted,long filesize){this.id=id;this.remoteId=remoteId;this.title=title;this.alternateTitle=alternateTitle;this.author=author;this.circle=circle;this.coverUrl=coverUrl;this.category=category;this.uploader=uploader;this.completionStatus=completionStatus;this.tags=tags;this.rawTags=rawTags;this.authors=authors;this.pagesCount=pagesCount;this.rating=rating;this.posted=posted;this.filesize=filesize;}
    }
    static final class Episode {final String id,title;final int order;Episode(String id,String title,int order){this.id=id;this.title=title;this.order=order;}}
    static final class Page {final String id,pageUrl;final int position;Page(String id,String pageUrl,int position){this.id=id;this.pageUrl=pageUrl;this.position=position;}}

    static boolean isEhId(String value){return value!=null&&value.matches("^eh:\\d+:[0-9a-fA-F]{10}$");}
    private static String[] parseId(String value){if(!isEhId(value))throw new IllegalArgumentException("无效的 E-H 画廊标识");String[] p=value.split(":",3);return new String[]{p[1],p[2].toLowerCase(Locale.ROOT)};}
    private static String decodeHtml(String s){return s.replace("&amp;","&").replace("&quot;","\"").replace("&#39;","'").replace("&apos;","'").replace("&lt;","<").replace("&gt;",">");}
    private static String tagValue(String raw){int i=raw.indexOf(':');return (i>0?raw.substring(i+1):raw).trim();}
    private static String tagNamespace(String raw){int i=raw.indexOf(':');return i>0?raw.substring(0,i).toLowerCase(Locale.ROOT):"";}
    private static void addUnique(List<String> out,String value){if(value!=null){value=value.trim();if(!value.isEmpty()&&!out.contains(value))out.add(value);}}
    private static boolean privateIpv4(String host){String[] p=host.split("\\.");if(p.length!=4)return false;int[] n=new int[4];try{for(int i=0;i<4;i++){n[i]=Integer.parseInt(p[i]);if(n[i]<0||n[i]>255)return true;}}catch(Exception e){return false;}return n[0]==0||n[0]==10||n[0]==127||(n[0]==169&&n[1]==254)||(n[0]==172&&n[1]>=16&&n[1]<=31)||(n[0]==192&&n[1]==168)||(n[0]==100&&n[1]>=64&&n[1]<=127)||n[0]>=224;}
    private static URL publicHttps(String raw) throws Exception {URL u=new URL(raw);String host=u.getHost()==null?"":u.getHost().toLowerCase(Locale.ROOT);if(!"https".equalsIgnoreCase(u.getProtocol())||host.isEmpty()||"localhost".equals(host)||host.endsWith(".localhost")||privateIpv4(host)||host.equals("::1")||host.startsWith("fc")||host.startsWith("fd")||host.startsWith("fe8")||host.startsWith("fe9")||host.startsWith("fea")||host.startsWith("feb"))throw new SecurityException("E-H 媒体地址未通过安全校验");return u;}

    private static synchronized void paceSearch() throws InterruptedException {long wait=SEARCH_INTERVAL_MS-(System.currentTimeMillis()-lastSearchAt);if(wait>0)Thread.sleep(wait);lastSearchAt=System.currentTimeMillis();}
    private String cookieHeader(String host){if(!"e-hentai.org".equalsIgnoreCase(host)&&!"exhentai.org".equalsIgnoreCase(host))return "";EhAccountStore.Session s=EhAccountStore.load(context);if(!s.configured())return "";StringBuilder out=new StringBuilder();appendCookie(out,"ipb_member_id",s.memberId);appendCookie(out,"ipb_pass_hash",s.passHash);appendCookie(out,"igneous",s.igneous);appendCookie(out,"cf_clearance",s.cfClearance);appendCookie(out,"nw","1");return out.toString();}
    private static void appendCookie(StringBuilder out,String name,String value){if(value==null||value.isEmpty())return;if(out.length()>0)out.append("; ");out.append(name).append('=').append(value);}
    private HttpURLConnection open(String url,String method,String accept) throws Exception {URL u=publicHttps(url);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(8000);c.setReadTimeout(15000);c.setInstanceFollowRedirects(true);c.setRequestMethod(method);c.setRequestProperty("Accept",accept);c.setRequestProperty("User-Agent",UA);String cookie=cookieHeader(u.getHost());if(!cookie.isEmpty())c.setRequestProperty("Cookie",cookie);c.setUseCaches(false);return c;}
    private static byte[] read(InputStream in,int max) throws Exception {try(InputStream input=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=input.read(b))>0){if(out.size()+n>max)throw new IOException("E-H 响应过大");out.write(b,0,n);}return out.toByteArray();}}
    private String text(String url) throws Exception {HttpURLConnection c=open(url,"GET","text/html,*/*;q=0.8");try{int status=c.getResponseCode();if(status<200||status>=300)throw new IOException("E-H HTTP "+status);return new String(read(c.getInputStream(),8*1024*1024),StandardCharsets.UTF_8);}finally{c.disconnect();}}
    private String accountText(String url) throws Exception {if(!EhAccountStore.load(context).configured())throw new SecurityException("尚未配置 E-H 会话");HttpURLConnection c=open(url,"GET","text/html,*/*;q=0.8");try{int status=c.getResponseCode();URL end=c.getURL();if(status==401||status==403||end.getPath().contains("bounce_login")||end.getHost().startsWith("forums."))throw new SecurityException("E-H 会话无效或已过期");if(status<200||status>=300)throw new IOException("E-H HTTP "+status);String body=new String(read(c.getInputStream(),8*1024*1024),StandardCharsets.UTF_8);if(body.contains("act=Login&CODE=00")||body.contains("name=\"UserName\""))throw new SecurityException("E-H 会话无效或已过期");return body;}finally{c.disconnect();}}
    private JSONObject postJson(JSONObject body) throws Exception {HttpURLConnection c=open(API,"POST","application/json");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}try{int status=c.getResponseCode();if(status<200||status>=300)throw new IOException("E-H API HTTP "+status);return new JSONObject(new String(read(c.getInputStream(),4*1024*1024),StandardCharsets.UTF_8));}finally{c.disconnect();}}

    private List<Comic> gdata(List<String[]> refs) throws Exception {List<Comic> out=new ArrayList<>();int batch=0;for(int offset=0;offset<refs.size();offset+=25){JSONArray ids=new JSONArray();for(int i=offset;i<Math.min(offset+25,refs.size());i++){String[] ref=refs.get(i);JSONArray pair=new JSONArray();pair.put(Long.parseLong(ref[0]));pair.put(ref[1]);ids.put(pair);}JSONObject request=new JSONObject();request.put("method","gdata");request.put("gidlist",ids);request.put("namespace",1);JSONArray rows=postJson(request).optJSONArray("gmetadata");if(rows==null)throw new IOException("E-H 元数据响应格式异常");for(int i=0;i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(row!=null&&!row.has("error"))out.add(parseComic(row));}batch++;if(offset+25<refs.size())Thread.sleep(batch%4==0?5000:250);}return out;}
    private Comic parseComic(JSONObject row){long gid=row.optLong("gid");String token=row.optString("token","").toLowerCase(Locale.ROOT);String id="eh:"+gid+":"+token;JSONArray arr=row.optJSONArray("tags");List<String> raw=new ArrayList<>(),tags=new ArrayList<>(),authors=new ArrayList<>(),groups=new ArrayList<>();if(arr!=null)for(int i=0;i<arr.length();i++){String value=arr.optString(i,"");addUnique(raw,value);addUnique(tags,tagValue(value));String ns=tagNamespace(value);if("artist".equals(ns))addUnique(authors,tagValue(value));if("group".equals(ns))addUnique(groups,tagValue(value));}String uploader=row.optString("uploader","");String author=!authors.isEmpty()?authors.get(0):!groups.isEmpty()?groups.get(0):uploader;double rating;try{rating=Double.parseDouble(row.optString("rating","NaN"));}catch(Exception e){rating=Double.NaN;}String cover=row.optString("thumb","");try{if(!cover.isEmpty())cover=publicHttps(cover).toString();}catch(Exception e){cover="";}return new Comic(id,gid+":"+token,row.optString("title","E-H Gallery "+gid),row.optString("title_jpn",""),author,groups.isEmpty()?"":groups.get(0),cover,row.optString("category",""),uploader,"UNKNOWN",tags,raw,authors,Math.max(0,row.optInt("filecount",0)),rating,row.optLong("posted",0),row.optLong("filesize",0));}

    List<Comic> search(String query) throws Exception {paceSearch();String encoded=URLEncoder.encode(query==null?"":query.trim(),"UTF-8").replace("+","%20");String html=text(ORIGIN+"/?f_search="+encoded);Pattern p=Pattern.compile("(?:https?://e-hentai\\.org)?/g/(\\d+)/([0-9a-fA-F]{10})/");Matcher m=p.matcher(html);LinkedHashMap<String,String[]> refs=new LinkedHashMap<>();while(m.find()&&refs.size()<50){String key=m.group(1)+":"+m.group(2).toLowerCase(Locale.ROOT);refs.put(key,new String[]{m.group(1),m.group(2).toLowerCase(Locale.ROOT)});}return refs.isEmpty()?Collections.emptyList():gdata(new ArrayList<>(refs.values()));}
    Comic comic(String comicId) throws Exception {String[] ref=parseId(comicId);List<Comic> values=gdata(Collections.singletonList(ref));if(values.isEmpty())throw new IOException("E-H 未返回画廊元数据");return values.get(0);}
    List<Episode> episodes(String comicId) throws Exception {Comic comic=comic(comicId);String[] ref=parseId(comicId);return Collections.singletonList(new Episode("eh-"+ref[0],comic.title,1));}
    List<Page> pages(String comicId) throws Exception {Comic comic=comic(comicId);String[] ref=parseId(comicId);long gid=Long.parseLong(ref[0]);LinkedHashSet<String> urls=new LinkedHashSet<>();Pattern p=Pattern.compile("(?:https?://e-hentai\\.org)?/s/[0-9a-fA-F]+/"+gid+"-\\d+");for(int page=0;page<100;page++){String html=text(ORIGIN+"/g/"+gid+"/"+ref[1]+"/?p="+page);Matcher m=p.matcher(html);int before=urls.size();while(m.find())urls.add(new URL(new URL(ORIGIN),decodeHtml(m.group())).toString());if((comic.pagesCount>0&&urls.size()>=comic.pagesCount)||urls.size()==before)break;Thread.sleep(100);}if(comic.pagesCount>0&&urls.size()<comic.pagesCount)throw new IOException("E-H 页列表不完整（"+urls.size()+"/"+comic.pagesCount+"）");List<Page> out=new ArrayList<>();int pos=0;for(String url:urls){pos++;out.add(new Page("eh-"+gid+"-"+pos,url,pos));if(comic.pagesCount>0&&pos>=comic.pagesCount)break;}return out;}

    void verifyAccount() throws Exception {accountText(ORIGIN+"/favorites.php?favcat=all");}
    List<Comic> favoritesAll() throws Exception {verifyAccount();LinkedHashMap<String,String[]> refs=new LinkedHashMap<>();Set<String> cursors=new HashSet<>();String url=ORIGIN+"/favorites.php?favcat=all";Pattern gallery=Pattern.compile("(?:https?://e-hentai\\.org)?/g/(\\d+)/([0-9a-fA-F]{10})/");Pattern next=Pattern.compile("(?:\\?|&amp;|&)next=(\\d+)");for(int page=0;page<200;page++){String html=accountText(url);Matcher gm=gallery.matcher(html);while(gm.find()){String key=gm.group(1)+":"+gm.group(2).toLowerCase(Locale.ROOT);refs.put(key,new String[]{gm.group(1),gm.group(2).toLowerCase(Locale.ROOT)});}Matcher nm=next.matcher(html);String cursor="";if(nm.find())cursor=nm.group(1);if(cursor.isEmpty()||!cursors.add(cursor))break;url=ORIGIN+"/favorites.php?favcat=all&next="+URLEncoder.encode(cursor,"UTF-8");Thread.sleep(250);}return refs.isEmpty()?Collections.emptyList():gdata(new ArrayList<>(refs.values()));}
    String probeExH(){if(!EhAccountStore.load(context).configured())return "UNAVAILABLE";HttpURLConnection c=null;try{c=open(EXH_ORIGIN+"/uconfig.php","GET","text/html,*/*;q=0.8");int status=c.getResponseCode();URL end=c.getURL();if(status==401||status==403||status==404||end.getPath().contains("bounce_login")||!"exhentai.org".equalsIgnoreCase(end.getHost()))return "UNAVAILABLE";if(status<200||status>=300)return "NETWORK_ERROR";String body=new String(read(c.getInputStream(),2*1024*1024),StandardCharsets.UTF_8);if(body.trim().isEmpty()||body.contains("Sad Panda")||body.contains("act=Login"))return "UNAVAILABLE";return "AVAILABLE";}catch(SocketTimeoutException e){return "NETWORK_ERROR";}catch(UnknownHostException e){return "NETWORK_ERROR";}catch(ConnectException e){return "NETWORK_ERROR";}catch(SSLException e){return "NETWORK_ERROR";}catch(Exception e){return "NETWORK_ERROR";}finally{if(c!=null)c.disconnect();}}
    void setRemoteFavorite(String comicId,boolean desired) throws Exception {if(!EhAccountStore.load(context).configured())throw new SecurityException("尚未配置 E-H 会话");String[] ref=parseId(comicId);String url=ORIGIN+"/gallerypopups.php?gid="+URLEncoder.encode(ref[0],"UTF-8")+"&t="+URLEncoder.encode(ref[1],"UTF-8")+"&act=addfav";HttpURLConnection c=open(url,"POST","text/html,*/*;q=0.8");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded");String favcat=desired?"0":"favdel";String form="favcat="+URLEncoder.encode(favcat,"UTF-8")+"&favnote=&apply="+URLEncoder.encode("Apply Changes","UTF-8")+"&update=1";try(OutputStream out=c.getOutputStream()){out.write(form.getBytes(StandardCharsets.UTF_8));}try{int status=c.getResponseCode();URL end=c.getURL();if(status==401||status==403||end.getPath().contains("bounce_login")||end.getHost().startsWith("forums."))throw new SecurityException("E-H 会话无效或已过期");if(status<200||status>=300)throw new IOException("E-H 收藏更新 HTTP "+status);try{read(c.getInputStream(),1024*1024);}catch(Exception ignored){}}finally{c.disconnect();}}

    HttpURLConnection thumbnail(String url) throws Exception {HttpURLConnection c=(HttpURLConnection)publicHttps(url).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(15000);c.setInstanceFollowRedirects(true);c.setRequestProperty("Accept","image/*");c.setRequestProperty("Referer",ORIGIN+"/");c.setRequestProperty("User-Agent",UA);c.setUseCaches(false);return c;}
    HttpURLConnection image(String pageUrl) throws Exception {URL page=new URL(pageUrl);if(!"https".equalsIgnoreCase(page.getProtocol())||!"e-hentai.org".equalsIgnoreCase(page.getHost())||!page.getPath().matches("^/s/[0-9a-fA-F]+/\\d+-\\d+$"))throw new SecurityException("无效的 E-H 图片页");String html=text(page.toString());Matcher first=Pattern.compile("<img[^>]+id=[\"']img[\"'][^>]+src=[\"']([^\"']+)[\"']",Pattern.CASE_INSENSITIVE).matcher(html);Matcher second=Pattern.compile("<img[^>]+src=[\"']([^\"']+)[\"'][^>]+id=[\"']img[\"']",Pattern.CASE_INSENSITIVE).matcher(html);String imageUrl=first.find()?first.group(1):second.find()?second.group(1):"";if(imageUrl.isEmpty())throw new IOException("E-H 图片页没有可读取图片");URL image=publicHttps(decodeHtml(imageUrl));HttpURLConnection c=(HttpURLConnection)image.openConnection();c.setConnectTimeout(8000);c.setReadTimeout(20000);c.setInstanceFollowRedirects(true);c.setRequestProperty("Accept","image/*");c.setRequestProperty("Referer",page.toString());c.setRequestProperty("User-Agent",UA);c.setUseCaches(false);return c;}
}
