package com.picalibrary.android;

import android.app.*;
import android.content.Context;
import android.content.Intent;
import android.content.pm.ServiceInfo;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import androidx.annotation.NonNull;
import androidx.core.app.NotificationCompat;
import androidx.documentfile.provider.DocumentFile;
import androidx.work.*;
import java.io.*;
import java.net.HttpURLConnection;
import java.util.*;

/** Long-running E-H download using the same phone catalog/index as Pica downloads. */
public final class EhDownloadWorker extends Worker {
    static final String KEY_COMIC="comicId",KEY_DONE="done",KEY_TOTAL="total",KEY_PHASE="phase",KEY_TITLE="title";
    private static final String CHANNEL="pica-downloads";
    public EhDownloadWorker(@NonNull Context context,@NonNull WorkerParameters params){super(context,params);}

    @NonNull @Override public Result doWork(){String comicId=getInputData().getString(KEY_COMIC);if(comicId==null||!EhClient.isEhId(comicId))return Result.failure();try{EhClient client=new EhClient(getApplicationContext());EhClient.Comic comic=client.comic(comicId);List<EhClient.Episode> episodes=client.episodes(comicId);if(episodes.isEmpty())return failure("没有可下载章节");EhClient.Episode episode=episodes.get(0);List<EhClient.Page> pages=client.pages(comicId);if(pages.isEmpty())return failure("画廊没有可下载页面");setForegroundAsync(foreground(comicId,comic.title,"正在准备 E-H 下载",0,pages.size()));List<PhoneDownloadStore.Page> stored=new ArrayList<>();int done=0;for(EhClient.Page page:pages){if(isStopped())return Result.failure();String prior=PhoneDownloadStore.indexedUri(getApplicationContext(),comicId,episode.id,page.position-1);String uri=prior.isEmpty()?download(client,comicId,episode,page):prior;stored.add(new PhoneDownloadStore.Page(page.position-1,uri));done++;publish(comicId,comic.title,done,pages.size(),prior.isEmpty()?"正在下载":"正在校验已有页面");}PhoneDownloadStore.putChapter(getApplicationContext(),comicId,comic.title,comic.author,new PhoneDownloadStore.Chapter(episode.id,episode.title,episode.order,stored));UnifiedEhCatalogSync.merge(getApplicationContext(),comic);PhoneDownloadStore.reconcileCatalog(getApplicationContext());EhDownloadJobs.complete(getApplicationContext(),comicId);return Result.success(progress(pages.size(),pages.size(),comic.title,"下载完成"));}catch(Exception e){String message=e.getMessage()==null?"下载失败":e.getMessage();if(getRunAttemptCount()<3)return Result.retry();return failure(message);}}

    private void publish(String comicId,String title,int done,int total,String phase){Data data=progress(done,total,title,phase);setProgressAsync(data);setForegroundAsync(foreground(comicId,title,phase+" · "+done+" / "+total,done,total));}
    private static Data progress(int done,int total,String title,String phase){return new Data.Builder().putInt(KEY_DONE,done).putInt(KEY_TOTAL,total).putString(KEY_TITLE,title).putString(KEY_PHASE,phase).build();}
    private Result failure(String message){return Result.failure(new Data.Builder().putString(KEY_PHASE,message).build());}
    private ForegroundInfo foreground(String comicId,String title,String text,int done,int total){NotificationManager manager=(NotificationManager)getApplicationContext().getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)manager.createNotificationChannel(new NotificationChannel(CHANNEL,"Pica Library 下载",NotificationManager.IMPORTANCE_LOW));Intent intent=new Intent(getApplicationContext(),DownloadsActivity.class);PendingIntent pending=PendingIntent.getActivity(getApplicationContext(),0,intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);NotificationCompat.Builder b=new NotificationCompat.Builder(getApplicationContext(),CHANNEL).setSmallIcon(android.R.drawable.stat_sys_download).setContentTitle(title==null||title.isEmpty()?"Pica Library 下载":title).setContentText(text).setContentIntent(pending).setOnlyAlertOnce(true).setOngoing(true);if(total>0)b.setProgress(total,Math.max(0,Math.min(done,total)),false);else b.setProgress(0,0,true);Notification notification=b.build();int id=0x54000000|(ReaderPolicy.hash(comicId).hashCode()&0x00ffffff);if(Build.VERSION.SDK_INT>=29)return new ForegroundInfo(id,notification,ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC);return new ForegroundInfo(id,notification);}

    private String download(EhClient client,String comicId,EhClient.Episode episode,EhClient.Page page) throws Exception {String name=String.format(Locale.ROOT,"%06d.jpg",page.position),tree=StorageSettings.downloadTreeUri(getApplicationContext());if(tree!=null&&!tree.isEmpty())return downloadDocument(client,comicId,episode,page,name,tree);File base=getApplicationContext().getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS);if(base==null)base=getApplicationContext().getFilesDir();File target=new File(new File(new File(new File(base,"PicaLibraryDownloads"),comicId),episode.id),name);target.getParentFile().mkdirs();File tmp=new File(target.getParentFile(),target.getName()+".part");if(tmp.exists())tmp.delete();try{try(OutputStream out=new FileOutputStream(tmp)){copy(client,page.pageUrl,out);}validateLength(tmp.length());if(target.exists()&&!target.delete())throw new IOException("无法替换已下载页面");if(!tmp.renameTo(target))throw new IOException("无法完成页面下载");return Uri.fromFile(target).toString();}catch(Exception e){tmp.delete();throw e;}}
    private String downloadDocument(EhClient client,String comicId,EhClient.Episode episode,EhClient.Page page,String name,String tree) throws Exception {DocumentFile root=DocumentFile.fromTreeUri(getApplicationContext(),Uri.parse(tree));if(root==null||!root.canWrite())throw new IOException("手机下载目录不可写，请重新选择");DocumentFile library=dir(root,"PicaLibraryDownloads"),comic=dir(library,comicId),chapter=dir(comic,episode.id);DocumentFile orphan=chapter.findFile(name);if(orphan!=null)orphan.delete();String partName=name+".part";DocumentFile oldPart=chapter.findFile(partName);if(oldPart!=null)oldPart.delete();DocumentFile part=chapter.createFile("application/octet-stream",partName);if(part==null)throw new IOException("无法创建临时下载页面");try{try(OutputStream out=getApplicationContext().getContentResolver().openOutputStream(part.getUri(),"wt")){if(out==null)throw new IOException("无法写入下载页面");copy(client,page.pageUrl,out);}validateLength(part.length());if(part.renameTo(name))return part.getUri().toString();DocumentFile target=chapter.createFile("image/jpeg",name);if(target==null)throw new IOException("无法完成下载页面");try(InputStream in=getApplicationContext().getContentResolver().openInputStream(part.getUri());OutputStream out=getApplicationContext().getContentResolver().openOutputStream(target.getUri(),"wt")){if(in==null||out==null)throw new IOException("无法提交临时下载页面");byte[] b=new byte[32768];int n;while((n=in.read(b))>0)out.write(b,0,n);}validateLength(target.length());part.delete();return target.getUri().toString();}catch(Exception e){part.delete();throw e;}}
    private void copy(EhClient client,String pageUrl,OutputStream out) throws Exception {HttpURLConnection c=client.image(pageUrl);try{int status=c.getResponseCode();if(status<200||status>=300)throw new IOException("图片 HTTP "+status);String type=String.valueOf(c.getContentType()).toLowerCase(Locale.ROOT);if(!type.startsWith("image/"))throw new IOException("E-H 返回了非图片内容");try(InputStream in=c.getInputStream()){byte[] b=new byte[32768];int n;long bytes=0;while((n=in.read(b))>0){if(isStopped())throw new IOException("下载已停止");bytes+=n;if(bytes>64L*1024*1024)throw new IOException("单页文件过大");out.write(b,0,n);}}}finally{c.disconnect();}}
    private static void validateLength(long length) throws IOException {if(length<=0)throw new IOException("下载页面为空");}
    private static DocumentFile dir(DocumentFile parent,String name) throws IOException {DocumentFile value=parent.findFile(name);if(value!=null&&value.isDirectory())return value;if(value!=null)value.delete();value=parent.createDirectory(name);if(value==null)throw new IOException("无法创建目录 "+name);return value;}
}
