package com.picalibrary.android;

import android.app.*;
import android.content.Context;
import android.text.InputType;
import android.widget.*;
import java.util.*;

/** Progressive-disclosure E-H server-side filters. */
final class EhOnlineFilterDialog {
    interface Applied { void apply(EhOnlineFilterSpec value); }
    private EhOnlineFilterDialog(){}

    static void show(Activity activity,EhOnlineFilterSpec current,Applied applied){EhOnlineFilterSpec spec=current==null?new EhOnlineFilterSpec():current.copy();showRoot(activity,spec,applied);}
    private static void showRoot(Activity a,EhOnlineFilterSpec s,Applied applied){
        String[] labels={"分类"+suffix(categorySummary(s)),"语言"+suffix(languageLabel(s.language)),"标签"+count(s.includeTags.size()),"排除标签"+count(s.excludeTags.size()),"最低评分"+suffix(s.minRating>0?"≥ "+s.minRating:"不限"),"页数"+suffix(pageLabel(s)),"重置筛选"};
        new AlertDialog.Builder(a).setTitle(LocalizedText.ui("筛选")).setItems(labels,(d,w)->{switch(w){case 0:categories(a,s,applied);break;case 1:language(a,s,applied);break;case 2:tags(a,s,false,applied);break;case 3:tags(a,s,true,applied);break;case 4:rating(a,s,applied);break;case 5:pages(a,s,applied);break;default:EhOnlineFilterSpec reset=new EhOnlineFilterSpec();reset.freeText=s.freeText;reset.mode=s.mode;reset.toplist=s.toplist;applied.apply(reset);break;}}).setPositiveButton(LocalizedText.ui("应用"),(d,w)->applied.apply(s)).setNegativeButton(LocalizedText.ui("取消"),null).show();
    }
    private static void categories(Activity a,EhOnlineFilterSpec s,Applied applied){int[] bits=EhOnlineFilterSpec.categoryBits();String[] labels=new String[bits.length];boolean[] checked=new boolean[bits.length];for(int i=0;i<bits.length;i++){labels[i]=EhOnlineFilterSpec.categoryLabel(bits[i]);checked[i]=(s.includeCategories&bits[i])!=0;}new AlertDialog.Builder(a).setTitle(LocalizedText.ui("分类")).setMultiChoiceItems(labels,checked,(d,w,on)->checked[w]=on).setPositiveButton(LocalizedText.ui("确定"),(d,w)->{int mask=0;for(int i=0;i<bits.length;i++)if(checked[i])mask|=bits[i];s.includeCategories=mask==0?EhOnlineFilterSpec.ALL:mask;showRoot(a,s,applied);}).setNegativeButton(LocalizedText.ui("返回"),(d,w)->showRoot(a,s,applied)).show();}
    private static void language(Activity a,EhOnlineFilterSpec s,Applied applied){String[] labels={"不限","中文","日文","英文"};String[] values={"","chinese","japanese","english"};int checked=0;for(int i=1;i<values.length;i++)if(values[i].equals(s.language))checked=i;new AlertDialog.Builder(a).setTitle(LocalizedText.ui("语言")).setSingleChoiceItems(labels,checked,(d,w)->{s.language=values[w];d.dismiss();showRoot(a,s,applied);}).setNegativeButton(LocalizedText.ui("返回"),(d,w)->showRoot(a,s,applied)).show();}
    private static void tags(Activity a,EhOnlineFilterSpec s,boolean excluded,Applied applied){List<String> target=excluded?s.excludeTags:s.includeTags;ArrayList<String> labels=new ArrayList<>();labels.add("＋ 添加标签");EhTagTranslationStore tr=EhTagTranslationStore.load(a);for(String tag:target){int at=tag.indexOf(':');String ns=at>0?tag.substring(0,at):"",raw=at>0?tag.substring(at+1):tag;String display=tr.display(ns,raw);labels.add(EhTagTranslationStore.namespaceLabel(ns)+" · "+display);}new AlertDialog.Builder(a).setTitle(excluded?LocalizedText.ui("排除标签"):LocalizedText.ui("标签")).setItems(labels.toArray(new String[0]),(d,w)->{if(w==0)tagSearch(a,s,excluded,applied);else{target.remove(w-1);tags(a,s,excluded,applied);}}).setPositiveButton(LocalizedText.ui("返回"),(d,w)->showRoot(a,s,applied)).show();}
    private static void tagSearch(Activity a,EhOnlineFilterSpec s,boolean excluded,Applied applied){EditText input=new EditText(a);input.setSingleLine(true);input.setHint(LocalizedText.ui("中文标签或 namespace:value"));input.setInputType(InputType.TYPE_CLASS_TEXT);int pad=Ui.dp(a,18);FrameLayout wrap=new FrameLayout(a);wrap.setPadding(pad,Ui.dp(a,6),pad,0);wrap.addView(input);new AlertDialog.Builder(a).setTitle(LocalizedText.ui("添加标签")).setView(wrap).setPositiveButton(LocalizedText.ui("查找"),(d,w)->{String q=input.getText().toString().trim();if(EhOnlineFilterSpec.validCanonical(q)){addTag(s,excluded,q.toLowerCase(Locale.ROOT));tags(a,s,excluded,applied);return;}List<EhTagTranslationStore.Suggestion> found=EhTagTranslationStore.load(a).suggest(q,16);if(found.isEmpty()){Toast.makeText(a,LocalizedText.ui("未找到标签；也可以输入 namespace:value"),Toast.LENGTH_SHORT).show();tags(a,s,excluded,applied);return;}String[] labels=new String[found.size()];for(int i=0;i<found.size();i++){EhTagTranslationStore.Suggestion row=found.get(i);labels[i]=EhTagTranslationStore.namespaceLabel(row.namespace)+" · "+row.display+"\n"+row.canonical;}new AlertDialog.Builder(a).setTitle(LocalizedText.ui("选择标签")).setItems(labels,(dd,index)->{addTag(s,excluded,found.get(index).canonical);tags(a,s,excluded,applied);}).setNegativeButton(LocalizedText.ui("返回"),(dd,index)->tags(a,s,excluded,applied)).show();}).setNegativeButton(LocalizedText.ui("返回"),(d,w)->tags(a,s,excluded,applied)).show();}
    private static void addTag(EhOnlineFilterSpec s,boolean excluded,String canonical){List<String> target=excluded?s.excludeTags:s.includeTags;if(!target.contains(canonical))target.add(canonical);}
    private static void rating(Activity a,EhOnlineFilterSpec s,Applied applied){String[] labels={"不限","≥ 2","≥ 3","≥ 4","≥ 5"};int[] values={-1,2,3,4,5};int checked=0;for(int i=1;i<values.length;i++)if(values[i]==s.minRating)checked=i;new AlertDialog.Builder(a).setTitle(LocalizedText.ui("最低评分")).setSingleChoiceItems(labels,checked,(d,w)->{s.minRating=values[w];d.dismiss();showRoot(a,s,applied);}).setNegativeButton(LocalizedText.ui("返回"),(d,w)->showRoot(a,s,applied)).show();}
    private static void pages(Activity a,EhOnlineFilterSpec s,Applied applied){String[] labels={"不限","少于 20 页","20–50 页","50–100 页","100 页以上"};new AlertDialog.Builder(a).setTitle(LocalizedText.ui("页数")).setItems(labels,(d,w)->{switch(w){case 1:s.pageFrom=-1;s.pageTo=19;break;case 2:s.pageFrom=20;s.pageTo=50;break;case 3:s.pageFrom=50;s.pageTo=100;break;case 4:s.pageFrom=100;s.pageTo=-1;break;default:s.pageFrom=s.pageTo=-1;break;}showRoot(a,s,applied);}).setNegativeButton(LocalizedText.ui("返回"),(d,w)->showRoot(a,s,applied)).show();}
    private static String categorySummary(EhOnlineFilterSpec s){if(s.includeCategories==EhOnlineFilterSpec.ALL)return "不限";int count=0;String one="";for(int bit:EhOnlineFilterSpec.categoryBits())if((s.includeCategories&bit)!=0){count++;one=EhOnlineFilterSpec.categoryLabel(bit);}return count==1?one:count+" 项";}
    private static String languageLabel(String value){if("chinese".equals(value))return "中文";if("japanese".equals(value))return "日文";if("english".equals(value))return "英文";return "不限";}
    private static String pageLabel(EhOnlineFilterSpec s){if(s.pageFrom<=0&&s.pageTo<=0)return "不限";if(s.pageFrom>0&&s.pageTo>0)return s.pageFrom+"–"+s.pageTo;return s.pageFrom>0?"≥ "+s.pageFrom:"< "+(s.pageTo+1);}
    private static String suffix(String value){return " · "+value;}
    private static String count(int value){return value>0?" · "+value+" 项":"";}
}
