package com.picalibrary.android;

import android.app.*;
import android.content.*;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import java.net.*;
import javax.net.ssl.SSLException;

/** Focused E-H session import screen. Normal state stays terse; failures explain the next action. */
public final class EhSessionActivity extends Activity {
    private EditText memberId,passHash,igneous,cfClearance;private TextView status;private LinearLayout advanced;private boolean busy;
    @Override public void onCreate(Bundle saved){super.onCreate(saved);Ui.applyWindow(this);render();}
    private Button compact(String label,View.OnClickListener action){return Ui.button(this,label,action,true);}
    private EditText secret(String hint){EditText input=new EditText(this);input.setSingleLine(true);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);input.setHint(hint);input.setSaveEnabled(false);Ui.styleField(input,this);return input;}
    private void render(){EhAccountStore.Session session=EhAccountStore.load(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(Ui.dp(this,8),Ui.dp(this,6),Ui.dp(this,8),Ui.dp(this,4));bar.addView(compact("‹ 返回",v->finish()));bar.addView(Ui.text(this,"连接 E-H 账号",22,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));bar.addView(compact("官网登录",v->openOfficialLogin()));root.addView(bar);ScrollView scroll=new ScrollView(this);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(Ui.dp(this,18),Ui.dp(this,14),Ui.dp(this,18),Ui.dp(this,24));scroll.addView(p);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));p.addView(Ui.text(this,"ipb_member_id",13,Ui.TEXT,true));memberId=new EditText(this);memberId.setSingleLine(true);memberId.setText(session.memberId);Ui.styleField(memberId,this);p.addView(memberId);Ui.gap(p,this,10);p.addView(Ui.text(this,"ipb_pass_hash",13,Ui.TEXT,true));passHash=secret(session.passHash.isEmpty()?"必填":"已保存；留空则保留");p.addView(passHash);Ui.gap(p,this,8);p.addView(compact("更多 ▾",v->advanced.setVisibility(advanced.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE)),new LinearLayout.LayoutParams(-2,-2));advanced=new LinearLayout(this);advanced.setOrientation(LinearLayout.VERTICAL);advanced.setVisibility(View.GONE);advanced.setPadding(0,Ui.dp(this,8),0,0);p.addView(advanced);advanced.addView(Ui.text(this,"igneous",13,Ui.TEXT,true));igneous=secret(session.igneous.isEmpty()?"可选":"已保存；留空则保留");advanced.addView(igneous);Ui.gap(advanced,this,8);advanced.addView(Ui.text(this,"cf_clearance",13,Ui.TEXT,true));cfClearance=secret(session.cfClearance.isEmpty()?"可选":"已保存；留空则保留");advanced.addView(cfClearance);status=Ui.text(this,"",13,Ui.BAD,false);status.setVisibility(View.GONE);status.setPadding(0,Ui.dp(this,10),0,Ui.dp(this,4));p.addView(status);Button save=Ui.button(this,"验证并保存",v->saveAndVerify(),false);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,Ui.dp(this,10),0,0);p.addView(save,sp);setContentView(root);root.requestApplyInsets();}
    private EhAccountStore.Session candidate(){EhAccountStore.Session old=EhAccountStore.load(this);String id=memberId.getText().toString().trim(),hash=passHash.getText().toString().trim(),ign=igneous.getText().toString().trim(),cf=cfClearance.getText().toString().trim();return new EhAccountStore.Session(id.isEmpty()?old.memberId:id,hash.isEmpty()?old.passHash:hash,ign.isEmpty()?old.igneous:ign,cf.isEmpty()?old.cfClearance:cf);}
    private void saveAndVerify(){if(busy)return;EhAccountStore.Session old=EhAccountStore.load(this),next=candidate();memberId.setError(null);passHash.setError(null);if(next.memberId.isEmpty()){memberId.setError("缺少 ipb_member_id");memberId.requestFocus();return;}if(next.passHash.isEmpty()){passHash.setError("缺少 ipb_pass_hash");passHash.requestFocus();return;}busy=true;showStatus("正在验证…",Ui.MUTED);new Thread(()->{try{EhAccountStore.save(this,next);new EhClient(this).verifyAccount();runOnUiThread(()->{busy=false;Toast.makeText(this,"E-H 账号已连接",Toast.LENGTH_SHORT).show();finish();});}catch(Exception e){try{if(old.configured())EhAccountStore.save(this,old);else EhAccountStore.clear(this);}catch(Exception ignored){}runOnUiThread(()->{busy=false;showStatus(errorMessage(e),Ui.BAD);});}}).start();}
    private String errorMessage(Exception e){String message=e.getMessage()==null?"":e.getMessage();if(e instanceof SocketTimeoutException||e instanceof UnknownHostException||e instanceof ConnectException||e instanceof SSLException)return "无法连接 E-H，请检查网络或代理后重试。";if(message.contains("会话无效")||message.contains("已过期"))return "会话无效，请重新登录 E-H 后更新 Cookie。";if(message.contains("403")||message.contains("拦截"))return "E-H 暂时无法访问，请稍后重试。";return message.isEmpty()?"验证失败，请重新检查会话。":"验证失败："+message;}
    private void showStatus(String text,int color){status.setText(text);status.setTextColor(color);status.setVisibility(View.VISIBLE);}
    private void openOfficialLogin(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://forums.e-hentai.org/index.php?act=Login")));}catch(Exception e){Toast.makeText(this,"无法打开登录页面",Toast.LENGTH_SHORT).show();}}
}
