package com.picalibrary.android;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;

/** Reading-history destination outside bottom navigation. */
public final class HistoryActivity extends Activity {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private LinearLayout list,filterRow;private TextView status;private ReadingHistoryStore.Range range=ReadingHistoryStore.Range.DAYS_7;private LocalDate exactDate;private boolean destroyed,importing;
    @Override public void onCreate(Bundle saved){super.onCreate(saved);Ui.applyWindow(this);ReadingHistoryStore.importLocalBookmarksOnce(this);renderShell();renderList();importLegacySources();}
    private Button compact(String label,android.view.View.OnClickListener action){return Ui.button(this,label,action,true);}
    private void renderShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(Ui.dp(this,8),Ui.dp(this,6),Ui.dp(this,8),Ui.dp(this,4));bar.addView(compact("‹ 返回",v->finish()));bar.addView(Ui.text(this,"阅读历史",22,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));bar.addView(compact("📅",v->pickDate()));root.addView(bar);HorizontalScrollView scroller=new HorizontalScrollView(this);filterRow=new LinearLayout(this);filterRow.setPadding(Ui.dp(this,12),0,Ui.dp(this,12),Ui.dp(this,2));scroller.addView(filterRow);root.addView(scroller);status=Ui.text(this,"",12,Ui.MUTED,false);status.setPadding(Ui.dp(this,14),Ui.dp(this,4),Ui.dp(this,14),Ui.dp(this,2));root.addView(status);ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(Ui.dp(this,10),0,Ui.dp(this,10),Ui.dp(this,24));scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);root.requestApplyInsets();renderFilters();}
    private void renderFilters(){filterRow.removeAllViews();addRange("今天",ReadingHistoryStore.Range.TODAY);addRange("7天",ReadingHistoryStore.Range.DAYS_7);addRange("30天",ReadingHistoryStore.Range.DAYS_30);addRange("全部",ReadingHistoryStore.Range.ALL);if(exactDate!=null){Button exact=compact(exactDate.getMonthValue()+"/"+exactDate.getDayOfMonth()+" ✓",v->{exactDate=null;renderFilters();renderList();});filterRow.addView(exact);}}
    private void addRange(String label,ReadingHistoryStore.Range value){String text=label+(exactDate==null&&range==value?" ✓":"");Button b=compact(text,v->{range=value;exactDate=null;renderFilters();renderList();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,0,Ui.dp(this,6),0);filterRow.addView(b,lp);}
    private void pickDate(){LocalDate base=exactDate==null?LocalDate.now():exactDate;new DatePickerDialog(this,(view,y,m,d)->{exactDate=LocalDate.of(y,m+1,d);renderFilters();renderList();},base.getYear(),base.getMonthValue()-1,base.getDayOfMonth()).show();}
    private void renderList(){if(list==null)return;list.removeAllViews();ZoneId zone=ZoneId.systemDefault();List<ReadingHistoryStore.Session> rows=ReadingHistoryStore.filter(ReadingHistoryStore.load(this),range,exactDate,zone);status.setText((importing?"正在合并旧阅读记录 · ":"")+rows.size()+" 条阅读记录"+(exactDate==null?"":" · "+exactDate));if(rows.isEmpty()){LinearLayout empty=Ui.card(this);empty.addView(Ui.text(this,exactDate==null?"这个时间段还没有阅读记录":"当天没有阅读记录",16,Ui.TEXT,true));empty.addView(Ui.text(this,"新阅读会按会话记录；旧版进度只能导入现存的最后一次快照。",12,Ui.MUTED,false));list.addView(empty);return;}LocalDate current=null;DateTimeFormatter dayFormat=DateTimeFormatter.ofPattern("yyyy年M月d日 EEEE",Locale.CHINA);for(ReadingHistoryStore.Session row:rows){LocalDate day=ReadingHistoryStore.localDay(row.lastReadAt,zone);if(day==null)continue;if(!day.equals(current)){current=day;TextView h=Ui.text(this,dayFormat.format(day),14,Ui.MUTED,true);h.setPadding(Ui.dp(this,8),Ui.dp(this,12),0,Ui.dp(this,2));list.addView(h);}addSession(row,zone);}}
    private void addSession(ReadingHistoryStore.Session row,ZoneId zone){LinearLayout card=Ui.card(this);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);String time=ReadingHistoryStore.timeLabel(row.lastReadAt,zone);head.addView(Ui.text(this,(time.isEmpty()?"":time+"  ")+row.title,17,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));if(row.legacySnapshot)head.addView(Ui.pill(this,"旧记录",Ui.ACTION,Ui.MUTED));card.addView(head);String chapter=row.chapterTitle.isEmpty()?"章节":row.chapterTitle;card.addView(Ui.text(this,chapter+" · 第 "+(row.lastPage+1)+" 页",12.5f,Ui.PRIMARY,false));if(!row.author.isEmpty())card.addView(Ui.text(this,row.author,12,Ui.MUTED,false));String source=sourceLabel(row);if(!source.isEmpty())card.addView(Ui.text(this,source,11,Ui.MUTED,false));LinearLayout actions=new LinearLayout(this);actions.setPadding(0,Ui.dp(this,7),0,0);actions.addView(compact("详情",v->openDetail(row)),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(actions,this,6);actions.addView(compact("继续阅读",v->continueReading(row)),new LinearLayout.LayoutParams(0,-2,1));card.addView(actions);list.addView(card);}
    private String sourceLabel(ReadingHistoryStore.Session row){String source="phone".equals(row.sourceKind)?"手机":"desktop".equals(row.sourceKind)?"电脑":"remote".equals(row.sourceKind)?"WebDAV":"pica".equals(row.sourceKind)?"Pica":"eh".equals(row.sourceKind)?"E-H":"";if(row.legacySnapshot)return source.isEmpty()?"旧版最后进度快照":source+" · 旧版最后进度快照";return source;}
    private void openDetail(ReadingHistoryStore.Session row){Intent i=new Intent(this,UnifiedComicDetailActivity.class);i.putExtra("comicId",row.comicId);i.putExtra("title",row.title);i.putExtra("author",row.author);startActivity(i);}
    private void continueReading(ReadingHistoryStore.Session row){if(!resumeSupported(row)){openDetail(row);return;}ReaderProgress.seedOneShotPosition(this,row.comicId,row.chapterId,row.lastPage);Intent i=new Intent(this,ReaderActivity.class);i.putExtra("comicId",row.comicId);i.putExtra("title",row.title);i.putExtra("author",row.author);i.putExtra("episodeId",row.chapterId);i.putExtra("source",row.sourceKind);startActivity(i);}
    private boolean resumeSupported(ReadingHistoryStore.Session row){if(row.chapterId.isEmpty())return false;if("phone".equals(row.sourceKind))return PhoneDownloadStore.has(this,row.comicId);if("remote".equals(row.sourceKind))return RemoteConfigStore.load(this).configured();if("desktop".equals(row.sourceKind))return BridgeStore.paired(this);if("pica".equals(row.sourceKind))return PicaAccountStore.load(this).configured();if("eh".equals(row.sourceKind))return EhClient.isEhId(row.comicId);return false;}
    private void importLegacySources(){if(importing)return;importing=true;renderList();worker.submit(()->{ArrayList<ReadingHistoryStore.Legacy> rows=new ArrayList<>();UnifiedCatalogStore.Snapshot catalog=UnifiedCatalogStore.load(this);if(RemoteConfigStore.load(this).configured())try{for(RemoteLibraryClient.ReadingEntry e:new RemoteLibraryClient(this).readingEntries()){UnifiedCatalogStore.Entry c=catalog.byId.get(e.comicId);String title=!e.comicTitle.isEmpty()?e.comicTitle:c==null?"漫画":c.title,author=!e.author.isEmpty()?e.author:c==null?"未知作者":c.displayAuthor(),provider=c==null?(EhClient.isEhId(e.comicId)?"eh":""):c.providerId;rows.add(new ReadingHistoryStore.Legacy("webdav",e.comicId,e.episodeId,title,author,e.episodeTitle,provider,"remote",e.pageIndex,e.updatedAt,e.deviceId));}}catch(Exception ignored){}if(BridgeStore.paired(this))try{for(BridgeClient.RecentItem r:BridgeClient.recent(this,200)){UnifiedCatalogStore.Entry c=catalog.byId.get(r.comic.id);String provider=c==null?(EhClient.isEhId(r.comic.id)?"eh":"pica"):c.providerId;rows.add(new ReadingHistoryStore.Legacy("desktop",r.comic.id,r.episodeId,r.comic.title,r.comic.author,r.episodeTitle,provider,"desktop",r.pageIndex,r.updatedAt,"desktop"));}}catch(Exception ignored){}ReadingHistoryStore.importLegacy(this,rows);runOnUiThread(()->{if(destroyed)return;importing=false;renderList();});});}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
}
