package com.picalibrary.android;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import java.util.*;
import java.util.concurrent.*;

/** Alpha8.3 product shell: favorite library, recommendations, native Pica online, connections and appearance. */
public final class HomeActivity extends Activity {
    private static final String REPO_URL="https://github.com/Saber-Alter-Lily/pica-library";
    private FrameLayout body;private LinearLayout nav;private SharedPreferences prefs;private final ExecutorService worker=Executors.newFixedThreadPool(4);private Future<?> pending;private int serial,current,collectionMode;private String libraryQuery="",activeShelfId="",themeKey="";private boolean showingShelves;
    private UnifiedLibraryFilter.Spec librarySpec;private UnifiedLibraryFilter.Facets libraryFacets=new UnifiedLibraryFilter.Facets(new ArrayList<>(),new ArrayList<>(),new ArrayList<>());
    private String onlineMode="leaderboard",onlineKeyword="",onlineCategory="",leaderboardRange="H24";private int onlinePage=1;
    private final int[] tabScrollY=new int[4],tabListPosition=new int[4],tabListOffset=new int[4];private ScrollView activeScroll;private RecyclerView activeList;private int activeViewportTab=-1;

    @Override public void onCreate(Bundle saved){super.onCreate(saved);Ui.applyWindow(this);themeKey=ThemeStore.effectiveKey(this);prefs=getSharedPreferences("alpha81-ui",MODE_PRIVATE);collectionMode=UnifiedComicCollectionAdapter.normalizeMode(prefs.getInt("collectionMode",UnifiedComicCollectionAdapter.MODE_GRID_MEDIUM));activeShelfId=prefs.getString("activeShelfId","");librarySpec=UnifiedFilterStore.load(getSharedPreferences("library-display",MODE_PRIVATE));librarySpec.favoriteOnly=false;if(saved!=null){current=ShellPolicy.clampTab(saved.getInt("tab",0));showingShelves=saved.getBoolean("shelves",false);libraryQuery=saved.getString("libraryQuery","");onlineMode=saved.getString("onlineMode","leaderboard");onlineKeyword=saved.getString("onlineKeyword","");onlineCategory=saved.getString("onlineCategory","");onlinePage=saved.getInt("onlinePage",1);leaderboardRange=PicaClient.normalizeLeaderboardRange(saved.getString("leaderboardRange","H24"));int[] sy=saved.getIntArray("tabScrollY"),sp=saved.getIntArray("tabListPosition"),so=saved.getIntArray("tabListOffset");if(sy!=null&&sy.length==4)System.arraycopy(sy,0,tabScrollY,0,4);if(sp!=null&&sp.length==4)System.arraycopy(sp,0,tabListPosition,0,4);if(so!=null&&so.length==4)System.arraycopy(so,0,tabListOffset,0,4);}renderShell();show();}
    @Override protected void onResume(){super.onResume();String key=ThemeStore.effectiveKey(this);if(!key.equals(themeKey)){themeKey=key;Ui.applyWindow(this);renderShell();show();return;}if(body!=null)show();}
    @Override protected void onSaveInstanceState(Bundle out){captureCurrentViewport();out.putInt("tab",current);out.putBoolean("shelves",showingShelves);out.putString("libraryQuery",libraryQuery);out.putString("onlineMode",onlineMode);out.putString("onlineKeyword",onlineKeyword);out.putString("onlineCategory",onlineCategory);out.putInt("onlinePage",onlinePage);out.putString("leaderboardRange",leaderboardRange);out.putIntArray("tabScrollY",tabScrollY);out.putIntArray("tabListPosition",tabListPosition);out.putIntArray("tabListOffset",tabListOffset);super.onSaveInstanceState(out);}
    @Override protected void onPause(){captureCurrentViewport();super.onPause();}
    @Override protected void onDestroy(){++serial;if(pending!=null)pending.cancel(true);worker.shutdownNow();super.onDestroy();}

    private void renderShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});body=new FrameLayout(this);body.setBackgroundColor(Ui.BG);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setBackgroundColor(Ui.NAV);String[] labels=ShellPolicy.bottomTabs();for(int i=0;i<labels.length;i++){final int tab=i;Button b=navButton(labels[i],v->{showingShelves=false;current=tab;show();});nav.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));}root.addView(nav);setContentView(root);root.requestApplyInsets();}
    private Button navButton(String label,View.OnClickListener action){Button b=new Button(this);b.setText(label);b.setTextSize(12.5f);b.setAllCaps(false);b.setTextColor(Ui.PRIMARY);b.setBackgroundColor(Color.TRANSPARENT);b.setMinHeight(Ui.dp(this,48));b.setGravity(Gravity.CENTER);android.graphics.drawable.Drawable icon=ThemePackStore.navDrawable(this,label);if(icon!=null){int size=Ui.dp(this,20);icon.setBounds(0,0,size,size);b.setCompoundDrawables(null,icon,null,null);b.setCompoundDrawablePadding(Ui.dp(this,1));}String typography=ThemePackStore.navigationTypography(this);if("comic".equals(typography)||"cute".equals(typography))b.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);b.setOnClickListener(action);return b;}
    private Button compact(String label,View.OnClickListener action){return Ui.button(this,label,action,true);}
    private void updateNav(){for(int i=0;i<nav.getChildCount();i++){View v=nav.getChildAt(i);v.setBackground(i==current?Ui.rounded(Ui.PRIMARY_SOFT,0,this):Ui.rounded(Color.TRANSPARENT,0,this));}}
    private void show(){captureCurrentViewport();++serial;if(pending!=null)pending.cancel(true);pending=null;body.removeAllViews();activeScroll=null;activeList=null;activeViewportTab=-1;updateNav();if(showingShelves){shelves();return;}if(current==0)library();else if(current==1)recommendations();else if(current==2)online();else connections();}
    private LinearLayout page(boolean scroll){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setBackgroundColor(Ui.BG);p.setPadding(Ui.dp(this,12),Ui.dp(this,8),Ui.dp(this,12),Ui.dp(this,8));if(scroll){final int tab=current;ScrollView s=new ScrollView(this);activeScroll=s;activeList=null;activeViewportTab=tab;s.setBackgroundColor(Ui.BG);s.addView(p);body.addView(s,new FrameLayout.LayoutParams(-1,-1));s.post(()->s.scrollTo(0,Math.max(0,tabScrollY[tab])));}else{activeScroll=null;activeList=null;activeViewportTab=-1;body.addView(p,new FrameLayout.LayoutParams(-1,-1));}return p;}
    private void titleRow(LinearLayout p,String title,View... actions){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView label=Ui.text(this,title,26,Ui.TEXT,true);row.addView(label,new LinearLayout.LayoutParams(0,-2,1));for(View action:actions){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(Ui.dp(this,4),0,0,0);row.addView(action,lp);}p.addView(row);}
    private RecyclerView collection(LinearLayout p,int mode){final int tab=current;RecyclerView v=new RecyclerView(this);activeScroll=null;activeList=v;activeViewportTab=tab;v.setClipToPadding(false);v.setPadding(0,Ui.dp(this,4),0,Ui.dp(this,16));setCollectionLayout(v,mode);p.addView(v,new LinearLayout.LayoutParams(-1,0,1));return v;}
    private void rememberListPosition(RecyclerView v,int tab){RecyclerView.LayoutManager raw=v.getLayoutManager();if(!(raw instanceof LinearLayoutManager))return;LinearLayoutManager lm=(LinearLayoutManager)raw;int position=lm.findFirstVisibleItemPosition();if(position<0)return;View first=lm.findViewByPosition(position);tabListPosition[tab]=position;tabListOffset[tab]=first==null?0:first.getTop()-v.getPaddingTop();}
    private void captureCurrentViewport(){int tab=activeViewportTab;if(tab<0||tab>=4)return;if(activeScroll!=null){tabScrollY[tab]=Math.max(0,activeScroll.getScrollY());return;}if(activeList!=null)rememberListPosition(activeList,tab);}
    private void restoreListPosition(RecyclerView v,int tab){int position=Math.max(0,tabListPosition[tab]),offset=tabListOffset[tab];v.post(()->{RecyclerView.LayoutManager raw=v.getLayoutManager();if(raw instanceof LinearLayoutManager)((LinearLayoutManager)raw).scrollToPositionWithOffset(position,offset);});}
    private void resetTabScroll(int tab){if(tab<0||tab>=4)return;tabScrollY[tab]=0;tabListPosition[tab]=0;tabListOffset[tab]=0;if(activeViewportTab==tab){activeViewportTab=-1;activeScroll=null;activeList=null;}}
    private void setCollectionLayout(RecyclerView v,int mode){if(mode==UnifiedComicCollectionAdapter.MODE_LIST)v.setLayoutManager(new LinearLayoutManager(this));else v.setLayoutManager(new GridLayoutManager(this,Math.max(2,mode)));v.setItemAnimator(null);}
    private void open(UnifiedCatalogStore.Entry e){Intent i=new Intent(this,UnifiedComicDetailActivity.class);i.putExtra("comicId",e.id);i.putExtra("title",e.title);i.putExtra("author",e.displayAuthor());startActivity(i);}

    private void library(){LinearLayout p=page(false);titleRow(p,"我的书库",compact("书架",v->{showingShelves=true;show();}),compact("↻",v->refreshLibrary(true)),compact("▦",v->chooseCollectionMode()));EditText search=new EditText(this);search.setSingleLine(true);search.setHint("搜索标题 / 作者 / 标签 / 分类");search.setText(libraryQuery);search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);Ui.styleField(search,this);search.setOnEditorActionListener((v,id,event)->{if(id==EditorInfo.IME_ACTION_SEARCH){libraryQuery=v.getText().toString().trim();show();return true;}return false;});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,Ui.dp(this,8),0,Ui.dp(this,6));p.addView(search,sp);LinearLayout tools=new LinearLayout(this);tools.setGravity(Gravity.CENTER_VERTICAL);Button filter=compact("筛选与排序"+(librarySpec.activeCount()>0?" ("+librarySpec.activeCount()+")":""),v->UnifiedLibraryFilterDialog.show(this,librarySpec,libraryFacets,next->{librarySpec=next;librarySpec.favoriteOnly=false;UnifiedFilterStore.save(getSharedPreferences("library-display",MODE_PRIVATE),next);show();}));tools.addView(filter);TextView count=Ui.text(this,"",13,Ui.MUTED,false);count.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-1,1);cp.setMargins(Ui.dp(this,10),0,0,0);tools.addView(count,cp);p.addView(tools);RecyclerView list=collection(p,collectionMode);renderLibrary(list,count);refreshLibrary(false);}
    private void renderLibrary(RecyclerView list,TextView count){UnifiedCatalogStore.Snapshot snapshot=UnifiedCatalogStore.reconcileLocalReferences(this);List<UnifiedCatalogStore.Entry> favorites=new ArrayList<>();for(UnifiedCatalogStore.Entry e:snapshot.entries())if(e.favorite)favorites.add(e);libraryFacets=UnifiedLibraryFilter.facets(favorites);UnifiedLibraryFilter.Spec spec=librarySpec.copy();spec.text=libraryQuery;spec.favoriteOnly=false;List<UnifiedCatalogStore.Entry> visible=UnifiedLibraryFilter.apply(favorites,spec);count.setText(visible.size()+(visible.size()==favorites.size()?" 本":" / "+favorites.size()+" 本"));list.setAdapter(new UnifiedComicCollectionAdapter(this,collectionMode,visible,this::open));restoreListPosition(list,0);}
    private void refreshLibrary(boolean force){final int id=serial;if(!force&&prefs.getBoolean("libraryRefreshed",false))return;prefs.edit().putBoolean("libraryRefreshed",true).apply();pending=worker.submit(()->{try{if(BridgeStore.paired(this)){BridgeClient.device(this);UnifiedCatalogStore.refreshDesktop(this);try{FavoriteCacheStore.syncFromDesktop(this,false,null);}catch(Exception ignored){}try{ShelfStore.syncWithDesktop(this);}catch(Exception ignored){}}if(RemoteConfigStore.load(this).configured()){try{RemoteLibraryClient client=new RemoteLibraryClient(this);UnifiedCatalogStore.refreshRemote(this);FavoriteCacheStore.Snapshot f=FavoriteCacheStore.fromRemote(client.favorites());FavoriteCacheStore.save(this,f.items,false);if(ShelfStore.load(this).activeShelves().isEmpty())try{ShelfStore.save(this,ShelfStore.fromRemote(client.shelves()));}catch(Exception ignored){}}catch(Exception ignored){}}runOnUiThread(()->{if(id==serial&&!isDestroyed())show();});}catch(Exception ignored){}});}
    private void chooseCollectionMode(){String[] labels={"列表","网格 · 大（2列）","网格 · 中（3列）","网格 · 小（5列）"};int[] modes={0,2,3,5};int checked=0;for(int i=0;i<modes.length;i++)if(modes[i]==collectionMode)checked=i;new AlertDialog.Builder(this).setTitle("显示方式").setSingleChoiceItems(labels,checked,(d,which)->{collectionMode=modes[which];prefs.edit().putInt("collectionMode",collectionMode).apply();d.dismiss();show();}).show();}

    private void shelves(){LinearLayout p=page(false);titleRow(p,"书架",compact("返回",v->{showingShelves=false;show();}),compact("＋",v->createShelf()),compact("▦",v->chooseCollectionMode()));ShelfStore.Snapshot snapshot=ShelfStore.load(this);List<ShelfStore.Shelf> shelves=snapshot.activeShelves();if(shelves.isEmpty()){TextView empty=Ui.text(this,"还没有书架",15,Ui.MUTED,false);empty.setGravity(Gravity.CENTER);empty.setPadding(0,Ui.dp(this,80),0,Ui.dp(this,16));p.addView(empty);p.addView(compact("新建书架",v->createShelf()));if(BridgeStore.paired(this))syncShelves();return;}ShelfStore.Shelf active=null;for(ShelfStore.Shelf s:shelves)if(s.id.equals(activeShelfId)){active=s;break;}if(active==null)active=shelves.get(0);activeShelfId=active.id;prefs.edit().putString("activeShelfId",activeShelfId).apply();HorizontalScrollView scroller=new HorizontalScrollView(this);LinearLayout tabs=new LinearLayout(this);tabs.setPadding(0,Ui.dp(this,6),0,Ui.dp(this,4));for(ShelfStore.Shelf s:shelves){Button b=compact(s.name+(s.id.equals(activeShelfId)?" ✓":""),v->{activeShelfId=s.id;prefs.edit().putString("activeShelfId",activeShelfId).apply();show();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,0,Ui.dp(this,6),0);tabs.addView(b,lp);}scroller.addView(tabs);p.addView(scroller);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.addView(Ui.text(this,active.activeItems().size()+" 本",13,Ui.MUTED,false),new LinearLayout.LayoutParams(0,-2,1));ShelfStore.Shelf selected=active;bar.addView(compact("重命名",v->renameShelf(selected)));Ui.gap(bar,this,6);bar.addView(compact("删除",v->deleteShelf(selected)));p.addView(bar);RecyclerView list=collection(p,collectionMode);List<UnifiedCatalogStore.Entry> entries=new ArrayList<>();UnifiedCatalogStore.Snapshot catalog=UnifiedCatalogStore.load(this);for(ShelfStore.Item item:active.activeItems()){UnifiedCatalogStore.Entry e=catalog.byId.get(item.comicId);if(e==null){e=new UnifiedCatalogStore.Entry(item.comicId,item.title,item.author);e.canonicalAuthor=item.canonicalAuthor;e.tags.addAll(item.tags);e.categories.addAll(item.categories);e.finished=item.finished;e.knownPictures=item.knownPictures;e.inShelf=true;}entries.add(e);}list.setAdapter(new UnifiedComicCollectionAdapter(this,collectionMode,entries,this::open));restoreListPosition(list,0);if(BridgeStore.paired(this))syncShelves();}
    private void createShelf(){final EditText input=new EditText(this);input.setHint("书架名称");Ui.styleField(input,this);new AlertDialog.Builder(this).setTitle("新建书架").setView(input).setNegativeButton("取消",null).setPositiveButton("创建",(d,w)->{try{ShelfStore.Shelf shelf=ShelfStore.create(this,input.getText().toString());activeShelfId=shelf.id;prefs.edit().putString("activeShelfId",activeShelfId).apply();syncShelves();show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}).show();}
    private void renameShelf(ShelfStore.Shelf shelf){final EditText input=new EditText(this);input.setText(shelf.name);Ui.styleField(input,this);new AlertDialog.Builder(this).setTitle("重命名书架").setView(input).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{try{ShelfStore.rename(this,shelf.id,input.getText().toString());syncShelves();show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}).show();}
    private void deleteShelf(ShelfStore.Shelf shelf){new AlertDialog.Builder(this).setTitle("删除“"+shelf.name+"”？").setMessage("只删除书架，不删除漫画。") .setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{ShelfStore.delete(this,shelf.id);activeShelfId="";syncShelves();show();}).show();}
    private void syncShelves(){if(!BridgeStore.paired(this))return;worker.submit(()->{try{BridgeClient.device(this);ShelfStore.syncWithDesktop(this);runOnUiThread(()->{if(showingShelves&&!isDestroyed())show();});}catch(Exception ignored){}});}

    private void recommendations(){LinearLayout p=page(true);RecommendationProgressPanel progress=new RecommendationProgressPanel(this,()->{if(current==1&&!isDestroyed()&&!isFinishing())show();});titleRow(p,"为你推荐",Ui.iconButton(this,R.drawable.ic_refresh_24,"刷新推荐",v->{NativeRecommendationJobs.refresh(this);progress.begin();}));p.addView(progress);if(!PicaAccountStore.load(this).configured()){TextView t=Ui.text(this,"登录 Pica 后即可根据收藏生成推荐。",14,Ui.MUTED,false);t.setPadding(0,Ui.dp(this,20),0,Ui.dp(this,10));p.addView(t);p.addView(compact("登录 Pica",v->startActivity(new Intent(this,PicaAccountActivity.class))));return;}NativeRecommendationStore.Snapshot snapshot=NativeRecommendationStore.load(this);if(!snapshot.available()){TextView t=Ui.text(this,"还没有推荐结果",14,Ui.MUTED,false);t.setPadding(0,Ui.dp(this,20),0,Ui.dp(this,10));p.addView(t);p.addView(compact("生成推荐",v->{NativeRecommendationJobs.refresh(this);progress.begin();}));return;}LinearLayout pager=new LinearLayout(this);pager.setGravity(Gravity.CENTER_VERTICAL);pager.addView(compact("上一批",v->{NativeRecommendationStore.previousBatch(this);show();}),new LinearLayout.LayoutParams(0,-2,1));TextView batch=Ui.text(this,"第 "+(snapshot.batchIndex+1)+" / "+snapshot.batches.size()+" 批",13,Ui.MUTED,false);batch.setGravity(Gravity.CENTER);pager.addView(batch,new LinearLayout.LayoutParams(0,-1,1));pager.addView(compact("下一批",v->{NativeRecommendationStore.nextBatch(this);show();}),new LinearLayout.LayoutParams(0,-2,1));p.addView(pager);UnifiedCatalogStore.Snapshot catalog=UnifiedCatalogStore.load(this);for(NativeRecommendationStore.Item item:snapshot.current()){UnifiedCatalogStore.Entry e=catalog.byId.get(item.comicId);if(e==null)e=new UnifiedCatalogStore.Entry(item.comicId,item.title,item.author);LinearLayout card=Ui.card(this);card.setOrientation(LinearLayout.HORIZONTAL);ImageView cover=new ImageView(this);cover.setScaleType(ImageView.ScaleType.CENTER_CROP);cover.setBackgroundColor(Ui.PLACEHOLDER);card.addView(cover,new LinearLayout.LayoutParams(Ui.dp(this,86),Ui.dp(this,122)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);copy.setPadding(Ui.dp(this,12),0,0,0);copy.addView(Ui.text(this,item.title,16,Ui.TEXT,true));copy.addView(Ui.text(this,item.author,12,Ui.MUTED,false));TextView why=Ui.text(this,item.reason,12,Ui.PRIMARY,false);why.setPadding(0,Ui.dp(this,6),0,0);copy.addView(why);card.addView(copy,new LinearLayout.LayoutParams(0,-2,1));UnifiedCatalogStore.Entry target=e;card.setOnClickListener(v->open(target));CoverRepository.load(this,cover,e,Ui.PLACEHOLDER);p.addView(card);}NativeRecommendationStore.markCurrentSeen(this);}

    private void online(){LinearLayout p=page(false);titleRow(p,"在线",Ui.iconButton(this,R.drawable.ic_person_24,"Pica 账号",v->startActivity(new Intent(this,PicaAccountActivity.class))));if(!PicaAccountStore.load(this).configured()){TextView t=Ui.text(this,"登录 Pica 后可搜索、浏览、收藏和在线阅读。",14,Ui.MUTED,false);t.setPadding(0,Ui.dp(this,36),0,Ui.dp(this,12));p.addView(t);p.addView(compact("登录 Pica",v->startActivity(new Intent(this,PicaAccountActivity.class))));return;}EditText search=new EditText(this);search.setSingleLine(true);search.setHint("搜索 Pica 漫画");search.setText("search".equals(onlineMode)?onlineKeyword:"");search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);Ui.styleField(search,this);search.setOnEditorActionListener((v,id,event)->{if(id==EditorInfo.IME_ACTION_SEARCH){onlineKeyword=v.getText().toString().trim();onlineMode="search";onlinePage=1;resetTabScroll(2);show();return true;}return false;});p.addView(search);LinearLayout actions=new LinearLayout(this);actions.setPadding(0,Ui.dp(this,7),0,Ui.dp(this,3));actions.addView(compact("收藏",v->{onlineMode="favorites";onlinePage=1;resetTabScroll(2);show();}),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(actions,this,6);actions.addView(compact("排行",v->chooseLeaderboardRange()),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(actions,this,6);actions.addView(compact("分类",v->chooseOnlineCategory()),new LinearLayout.LayoutParams(0,-2,1));p.addView(actions);TextView status=Ui.text(this,"正在读取…",12,Ui.MUTED,false);status.setPadding(0,Ui.dp(this,4),0,0);p.addView(status);RecyclerView list=collection(p,UnifiedComicCollectionAdapter.MODE_LIST);loadOnline(list,status);}
    private void loadOnline(RecyclerView list,TextView status){final int id=serial;pending=worker.submit(()->{try{PicaClient client=new PicaClient(this);List<PicaClient.Comic> comics;int pages=1,currentPage=onlinePage;if("favorites".equals(onlineMode)){PicaClient.ComicPage value=client.favorites(onlinePage,"dd");comics=value.comics;pages=value.pages;currentPage=value.page;}else if("search".equals(onlineMode)){PicaClient.ComicPage value=client.search(onlineKeyword,onlinePage,"ld",Collections.emptyList());comics=value.comics;pages=value.pages;currentPage=value.page;}else if("category".equals(onlineMode)){PicaClient.ComicPage value=client.browse(onlineCategory,"","dd",onlinePage);comics=value.comics;pages=value.pages;currentPage=value.page;}else{comics=client.leaderboard(leaderboardRange);onlinePage=1;}UnifiedPicaCatalogSync.mergeAll(this,comics);if("favorites".equals(onlineMode)){UnifiedCatalogStore.Snapshot s=UnifiedCatalogStore.load(this);for(PicaClient.Comic c:comics){UnifiedCatalogStore.Entry e=s.byId.get(c.id);if(e!=null)e.favorite=true;}UnifiedCatalogStore.save(this,s);}UnifiedCatalogStore.Snapshot catalog=UnifiedCatalogStore.load(this);List<UnifiedCatalogStore.Entry> entries=new ArrayList<>();for(PicaClient.Comic c:comics){UnifiedCatalogStore.Entry e=catalog.byId.get(c.id);if(e!=null)entries.add(e);}final int pageCount=pages,shownPage=currentPage;runOnUiThread(()->{if(id!=serial||isDestroyed())return;status.setText(onlineLabel()+("leaderboard".equals(onlineMode)?" · "+entries.size()+" 本":" · 第 "+shownPage+" / "+pageCount+" 页"));list.setAdapter(new UnifiedComicCollectionAdapter(this,UnifiedComicCollectionAdapter.MODE_LIST,entries,this::open));restoreListPosition(list,2);if(pageCount>1){LinearLayout navRow=new LinearLayout(this);navRow.setPadding(0,Ui.dp(this,5),0,0);navRow.addView(compact("上一页",v->{if(onlinePage>1){onlinePage--;resetTabScroll(2);show();}}),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(navRow,this,8);navRow.addView(compact("下一页",v->{if(onlinePage<pageCount){onlinePage++;resetTabScroll(2);show();}}),new LinearLayout.LayoutParams(0,-2,1));((LinearLayout)list.getParent()).addView(navRow);}});}catch(Exception e){runOnUiThread(()->{if(id==serial)status.setText("读取失败："+(e.getMessage()==null?"请稍后重试":e.getMessage()));});}});}
    private String onlineLabel(){if("favorites".equals(onlineMode))return "我的收藏";if("search".equals(onlineMode))return onlineKeyword;if("category".equals(onlineMode))return onlineCategory;return "排行 · "+leaderboardRangeLabel();}
    private String leaderboardRangeLabel(){if("D7".equals(leaderboardRange))return "7 天";if("D30".equals(leaderboardRange))return "30 天";return "24 小时";}
    private void chooseLeaderboardRange(){String[] labels={"24 小时","7 天","30 天"};String[] values={"H24","D7","D30"};int checked="D7".equals(leaderboardRange)?1:"D30".equals(leaderboardRange)?2:0;new AlertDialog.Builder(this).setTitle("排行榜范围").setSingleChoiceItems(labels,checked,(d,which)->{leaderboardRange=values[which];onlineMode="leaderboard";onlinePage=1;resetTabScroll(2);d.dismiss();show();}).setNegativeButton("取消",null).show();}
    private void chooseOnlineCategory(){worker.submit(()->{try{List<String> values=new PicaClient(this).categories();runOnUiThread(()->new AlertDialog.Builder(this).setTitle("分类").setItems(values.toArray(new String[0]),(d,i)->{onlineCategory=values.get(i);onlineMode="category";onlinePage=1;resetTabScroll(2);show();}).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"分类读取失败",Toast.LENGTH_SHORT).show());}});}

    private interface Probe {String check() throws Exception;}
    private void connections(){LinearLayout p=page(true);titleRow(p,"连接与设置");boolean desktop=BridgeStore.paired(this),webdav=RemoteConfigStore.load(this).configured(),pica=PicaAccountStore.load(this).configured();connectionCard(p,"局域网电脑",desktop,desktop?"已配对":"未配对",desktop?"管理连接":"配对电脑",v->startActivity(new Intent(this,PairingActivity.class)),desktop,()->{BridgeClient.device(this);return "在线 · "+BridgeStore.serverName(this);});connectionCard(p,"WebDAV",webdav,webdav?"已配置":"未配置","管理 WebDAV",v->startActivity(new Intent(this,RemoteStorageActivity.class)),webdav,()->new RemoteLibraryClient(this).test()?"可连接":"连接异常");connectionCard(p,"Pica",pica,pica?"已配置":"未配置","账号",v->startActivity(new Intent(this,PicaAccountActivity.class)),pica,()->{new PicaClient(this).categories();return "可用";});
        LinearLayout appearance=Ui.card(this);LinearLayout ah=new LinearLayout(this);ah.setGravity(Gravity.CENTER_VERTICAL);ah.addView(Ui.text(this,"外观",18,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));ah.addView(Ui.pill(this,ThemeStore.label(this),Ui.PRIMARY_SOFT,Ui.PRIMARY));appearance.addView(ah);appearance.addView(compact("外观设置",v->startActivity(new Intent(this,AppearanceActivity.class))));p.addView(appearance);
        LinearLayout storage=Ui.card(this);storage.addView(Ui.text(this,"存储与下载",18,Ui.TEXT,true));LinearLayout row=new LinearLayout(this);row.setPadding(0,Ui.dp(this,8),0,0);row.addView(compact("存储与缓存",v->startActivity(new Intent(this,StorageSettingsActivity.class))),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(row,this,8);row.addView(compact("下载任务",v->startActivity(new Intent(this,DownloadsActivity.class))),new LinearLayout.LayoutParams(0,-2,1));storage.addView(row);p.addView(storage);
        LinearLayout update=Ui.card(this);update.addView(Ui.text(this,"软件更新",18,Ui.TEXT,true));Button check=compact("检查更新",v->startActivity(new Intent(this,UpdateActivity.class)));LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(-1,-2);up.setMargins(0,Ui.dp(this,8),0,0);update.addView(check,up);p.addView(update);
        LinearLayout about=Ui.card(this);about.addView(Ui.text(this,"支持项目",18,Ui.TEXT,true));TextView thanks=Ui.text(this,"感谢你使用 Pica Library。",13,Ui.MUTED,false);thanks.setPadding(0,Ui.dp(this,8),0,Ui.dp(this,10));about.addView(thanks);LinearLayout support=new LinearLayout(this);support.addView(compact("⭐ GitHub 项目主页",v->openUrl(REPO_URL)),new LinearLayout.LayoutParams(-1,-2));about.addView(support);p.addView(about);
        if(desktop)worker.submit(()->{try{BridgeClient.device(this);ShelfStore.syncWithDesktop(this);SupporterSyncJobs.enqueue(this);}catch(Exception ignored){}});
    }
    private void connectionCard(LinearLayout p,String title,boolean configured,String configuredLabel,String action,View.OnClickListener click,boolean probeEnabled,Probe probe){LinearLayout card=Ui.card(this);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(Ui.text(this,title,18,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));head.addView(Ui.pill(this,configuredLabel,configured?Ui.GOOD_SOFT:Ui.ACTION,configured?Ui.GOOD:Ui.MUTED));card.addView(head);LinearLayout currentRow=new LinearLayout(this);currentRow.setGravity(Gravity.CENTER_VERTICAL);currentRow.setPadding(0,Ui.dp(this,9),0,Ui.dp(this,8));currentRow.addView(Ui.text(this,"当前状态",12.5f,Ui.MUTED,false),new LinearLayout.LayoutParams(0,-2,1));TextView currentPill=Ui.pill(this,configured?"检查中":"未连接",configured?Ui.WARN_SOFT:Ui.ACTION,configured?Ui.WARN:Ui.MUTED);currentRow.addView(currentPill);card.addView(currentRow);card.addView(compact(action,click));p.addView(card);if(probeEnabled){final int id=serial;worker.submit(()->{try{String value=probe.check();runOnUiThread(()->{if(id==serial&&!isDestroyed())Ui.stylePill(currentPill,this,value,Ui.GOOD_SOFT,Ui.GOOD);});}catch(Exception e){runOnUiThread(()->{if(id==serial&&!isDestroyed())Ui.stylePill(currentPill,this,"当前不可用",Ui.WARN_SOFT,Ui.WARN);});}});}}
    private void openUrl(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){Toast.makeText(this,"无法打开浏览器",Toast.LENGTH_SHORT).show();}}
}
