package com.picalibrary.android;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import java.util.*;
import java.util.concurrent.*;

/** Product shell: library and recommendations live here; Online and Settings own separate screens. */
public final class HomeActivity extends Activity {
    private FrameLayout body;private LinearLayout nav;private SharedPreferences prefs;private final ExecutorService worker=Executors.newFixedThreadPool(4);private Future<?> pending;private int serial,current,collectionMode;private String libraryQuery="",activeShelfId="",themeKey="";private boolean showingShelves;
    private UnifiedLibraryFilter.Spec librarySpec;private UnifiedLibraryFilter.Facets libraryFacets=new UnifiedLibraryFilter.Facets(new ArrayList<>(),new ArrayList<>(),new ArrayList<>());
    private final int[] tabScrollY=new int[4],tabListPosition=new int[4],tabListOffset=new int[4];private ScrollView activeScroll;private RecyclerView activeList;private int activeViewportTab=-1;

    @Override public void onCreate(Bundle saved){super.onCreate(saved);Ui.applyWindow(this);themeKey=ThemeStore.effectiveKey(this);prefs=getSharedPreferences("alpha81-ui",MODE_PRIVATE);collectionMode=UnifiedComicCollectionAdapter.normalizeMode(prefs.getInt("collectionMode",UnifiedComicCollectionAdapter.MODE_GRID_MEDIUM));activeShelfId=prefs.getString("activeShelfId","");librarySpec=UnifiedFilterStore.load(getSharedPreferences("library-display",MODE_PRIVATE));librarySpec.favoriteOnly=false;if(saved!=null){current=ShellPolicy.clampTab(saved.getInt("tab",0));showingShelves=saved.getBoolean("shelves",false);libraryQuery=saved.getString("libraryQuery","");int[] sy=saved.getIntArray("tabScrollY"),sp=saved.getIntArray("tabListPosition"),so=saved.getIntArray("tabListOffset");if(sy!=null&&sy.length==4)System.arraycopy(sy,0,tabScrollY,0,4);if(sp!=null&&sp.length==4)System.arraycopy(sp,0,tabListPosition,0,4);if(so!=null&&so.length==4)System.arraycopy(so,0,tabListOffset,0,4);}renderShell();show();}
    @Override protected void onResume(){super.onResume();String key=ThemeStore.effectiveKey(this);if(!key.equals(themeKey)){themeKey=key;Ui.applyWindow(this);renderShell();show();return;}if(body!=null)show();}
    @Override protected void onSaveInstanceState(Bundle out){captureCurrentViewport();out.putInt("tab",current);out.putBoolean("shelves",showingShelves);out.putString("libraryQuery",libraryQuery);out.putIntArray("tabScrollY",tabScrollY);out.putIntArray("tabListPosition",tabListPosition);out.putIntArray("tabListOffset",tabListOffset);super.onSaveInstanceState(out);}
    @Override protected void onPause(){captureCurrentViewport();super.onPause();}
    @Override protected void onDestroy(){++serial;if(pending!=null)pending.cancel(true);worker.shutdownNow();super.onDestroy();}

    private void renderShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});body=new FrameLayout(this);body.setBackgroundColor(Ui.BG);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setBackgroundColor(Ui.NAV);String[] labels=ShellPolicy.bottomTabs();for(int i=0;i<labels.length;i++){final int tab=i;Button b=navButton(labels[i],v->{showingShelves=false;if(tab==2){startActivity(new Intent(this,PicaBrowseActivity.class));return;}if(tab==3){startActivity(new Intent(this,SettingsActivity.class));return;}current=tab;show();});nav.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));}root.addView(nav);setContentView(root);root.requestApplyInsets();}
    private Button navButton(String label,View.OnClickListener action){Button b=new Button(this);b.setText(label);b.setTextSize(12.5f);b.setAllCaps(false);b.setTextColor(Ui.PRIMARY);b.setBackgroundColor(Color.TRANSPARENT);b.setMinHeight(Ui.dp(this,48));b.setGravity(Gravity.CENTER);android.graphics.drawable.Drawable icon=ThemePackStore.navDrawable(this,label);if(icon!=null){int size=Ui.dp(this,20);icon.setBounds(0,0,size,size);b.setCompoundDrawables(null,icon,null,null);b.setCompoundDrawablePadding(Ui.dp(this,1));}String typography=ThemePackStore.navigationTypography(this);if("comic".equals(typography)||"cute".equals(typography))b.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);b.setOnClickListener(action);return b;}
    private Button compact(String label,View.OnClickListener action){return Ui.button(this,label,action,true);}
    private void updateNav(){for(int i=0;i<nav.getChildCount();i++){View v=nav.getChildAt(i);v.setBackground(i==current?Ui.rounded(Ui.PRIMARY_SOFT,0,this):Ui.rounded(Color.TRANSPARENT,0,this));}}
    private void show(){captureCurrentViewport();++serial;if(pending!=null)pending.cancel(true);pending=null;body.removeAllViews();activeScroll=null;activeList=null;activeViewportTab=-1;updateNav();if(showingShelves){shelves();return;}if(current==0)library();else if(current==1)recommendations();else if(current==2)onlineEntry();else settingsEntry();}
    private LinearLayout page(boolean scroll){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setBackgroundColor(Ui.BG);p.setPadding(Ui.dp(this,12),Ui.dp(this,8),Ui.dp(this,12),Ui.dp(this,8));if(scroll){final int tab=current;ScrollView s=new ScrollView(this);activeScroll=s;activeList=null;activeViewportTab=tab;s.setBackgroundColor(Ui.BG);s.addView(p);body.addView(s,new FrameLayout.LayoutParams(-1,-1));s.post(()->s.scrollTo(0,Math.max(0,tabScrollY[tab])));}else{activeScroll=null;activeList=null;activeViewportTab=-1;body.addView(p,new FrameLayout.LayoutParams(-1,-1));}return p;}
    private void titleRow(LinearLayout p,String title,View... actions){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView label=Ui.text(this,title,26,Ui.TEXT,true);row.addView(label,new LinearLayout.LayoutParams(0,-2,1));for(View action:actions){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(Ui.dp(this,4),0,0,0);row.addView(action,lp);}p.addView(row);}
    private RecyclerView collection(LinearLayout p,int mode){final int tab=current;RecyclerView v=new RecyclerView(this);activeScroll=null;activeList=v;activeViewportTab=tab;v.setClipToPadding(false);v.setPadding(0,Ui.dp(this,4),0,Ui.dp(this,16));setCollectionLayout(v,mode);p.addView(v,new LinearLayout.LayoutParams(-1,0,1));return v;}
    private void rememberListPosition(RecyclerView v,int tab){RecyclerView.LayoutManager raw=v.getLayoutManager();if(!(raw instanceof LinearLayoutManager))return;LinearLayoutManager lm=(LinearLayoutManager)raw;int position=lm.findFirstVisibleItemPosition();if(position<0)return;View first=lm.findViewByPosition(position);tabListPosition[tab]=position;tabListOffset[tab]=first==null?0:first.getTop()-v.getPaddingTop();}
    private void captureCurrentViewport(){int tab=activeViewportTab;if(tab<0||tab>=4)return;if(activeScroll!=null){tabScrollY[tab]=Math.max(0,activeScroll.getScrollY());return;}if(activeList!=null)rememberListPosition(activeList,tab);}
    private void restoreListPosition(RecyclerView v,int tab){int position=Math.max(0,tabListPosition[tab]),offset=tabListOffset[tab];v.post(()->{RecyclerView.LayoutManager raw=v.getLayoutManager();if(raw instanceof LinearLayoutManager)((LinearLayoutManager)raw).scrollToPositionWithOffset(position,offset);});}
    private void setCollectionLayout(RecyclerView v,int mode){if(mode==UnifiedComicCollectionAdapter.MODE_LIST)v.setLayoutManager(new LinearLayoutManager(this));else v.setLayoutManager(new GridLayoutManager(this,Math.max(2,mode)));v.setItemAnimator(null);}
    private void open(UnifiedCatalogStore.Entry e){Intent i=new Intent(this,UnifiedComicDetailActivity.class);i.putExtra("comicId",e.id);i.putExtra("title",e.title);i.putExtra("author",e.displayAuthor());startActivity(i);}

    private void library(){LinearLayout p=page(false);titleRow(p,"我的书库",compact("书架",v->{showingShelves=true;show();}),compact("↻",v->refreshLibrary(true)),compact("▦",v->chooseCollectionMode()));EditText search=new EditText(this);search.setSingleLine(true);search.setHint("搜索标题 / 作者 / 标签 / 分类");search.setText(libraryQuery);search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);Ui.styleField(search,this);search.setOnEditorActionListener((v,id,event)->{if(id==EditorInfo.IME_ACTION_SEARCH){libraryQuery=v.getText().toString().trim();show();return true;}return false;});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,Ui.dp(this,8),0,Ui.dp(this,6));p.addView(search,sp);LinearLayout tools=new LinearLayout(this);tools.setGravity(Gravity.CENTER_VERTICAL);Button filter=compact("筛选与排序"+(librarySpec.activeCount()>0?" ("+librarySpec.activeCount()+")":""),v->UnifiedLibraryFilterDialog.show(this,librarySpec,libraryFacets,next->{librarySpec=next;librarySpec.favoriteOnly=false;UnifiedFilterStore.save(getSharedPreferences("library-display",MODE_PRIVATE),next);show();}));tools.addView(filter);TextView count=Ui.text(this,"",13,Ui.MUTED,false);count.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-1,1);cp.setMargins(Ui.dp(this,10),0,0,0);tools.addView(count,cp);p.addView(tools);RecyclerView list=collection(p,collectionMode);renderLibrary(list,count);refreshLibrary(false);}
    private void renderLibrary(RecyclerView list,TextView count){UnifiedCatalogStore.Snapshot snapshot=UnifiedCatalogStore.reconcileLocalReferences(this);List<UnifiedCatalogStore.Entry> favorites=new ArrayList<>();for(UnifiedCatalogStore.Entry e:snapshot.entries())if(e.favorite)favorites.add(e);libraryFacets=UnifiedLibraryFilter.facets(favorites);UnifiedLibraryFilter.Spec spec=librarySpec.copy();spec.text=libraryQuery;spec.favoriteOnly=false;List<UnifiedCatalogStore.Entry> visible=UnifiedLibraryFilter.apply(favorites,spec);count.setText(visible.size()+(visible.size()==favorites.size()?" 本":" / "+favorites.size()+" 本"));list.setAdapter(new UnifiedComicCollectionAdapter(this,collectionMode,visible,this::open));restoreListPosition(list,0);}
    private void refreshLibrary(boolean force){final int id=serial;if(!force&&prefs.getBoolean("libraryRefreshed",false))return;prefs.edit().putBoolean("libraryRefreshed",true).apply();pending=worker.submit(()->{try{if(BridgeStore.paired(this)){BridgeClient.device(this);UnifiedCatalogStore.refreshDesktop(this);try{FavoriteCacheStore.syncFromDesktop(this,false,null);}catch(Exception ignored){}try{ShelfStore.syncWithDesktop(this);}catch(Exception ignored){}}if(RemoteConfigStore.load(this).configured()){try{RemoteLibraryClient client=new RemoteLibraryClient(this);UnifiedCatalogStore.refreshRemote(this);FavoriteCacheStore.Snapshot f=FavoriteCacheStore.fromRemote(client.favorites());FavoriteCacheStore.save(this,f.items,false);if(ShelfStore.load(this).activeShelves().isEmpty())try{ShelfStore.save(this,ShelfStore.fromRemote(client.shelves()));}catch(Exception ignored){}}catch(Exception ignored){}}runOnUiThread(()->{if(id==serial&&!isDestroyed())show();});}catch(Exception ignored){}});}
    private void chooseCollectionMode(){String[] labels={"列表","网格 · 大（2列）","网格 · 中（3列）","网格 · 小（5列）"};int[] modes={0,2,3,5};int checked=0;for(int i=0;i<modes.length;i++)if(modes[i]==collectionMode)checked=i;new AlertDialog.Builder(this).setTitle("显示方式").setSingleChoiceItems(labels,checked,(d,which)->{collectionMode=modes[which];prefs.edit().putInt("collectionMode",collectionMode).apply();d.dismiss();show();}).show();}

    private void shelves(){LinearLayout p=page(false);titleRow(p,"书架",compact("返回",v->{showingShelves=false;show();}),compact("＋",v->createShelf()),compact("▦",v->chooseCollectionMode()));ShelfStore.Snapshot snapshot=ShelfStore.load(this);List<ShelfStore.Shelf> shelves=snapshot.activeShelves();if(shelves.isEmpty()){TextView empty=Ui.text(this,"还没有书架",15,Ui.MUTED,false);empty.setGravity(Gravity.CENTER);empty.setPadding(0,Ui.dp(this,80),0,Ui.dp(this,16));p.addView(empty);p.addView(compact("新建书架",v->createShelf()));if(BridgeStore.paired(this))syncShelves();return;}ShelfStore.Shelf active=null;for(ShelfStore.Shelf s:shelves)if(s.id.equals(activeShelfId)){active=s;break;}if(active==null)active=shelves.get(0);activeShelfId=active.id;prefs.edit().putString("activeShelfId",activeShelfId).apply();HorizontalScrollView scroller=new HorizontalScrollView(this);LinearLayout tabs=new LinearLayout(this);tabs.setPadding(0,Ui.dp(this,6),0,Ui.dp(this,4));for(ShelfStore.Shelf s:shelves){Button b=compact(s.name+(s.id.equals(activeShelfId)?" ✓":""),v->{activeShelfId=s.id;prefs.edit().putString("activeShelfId",activeShelfId).apply();show();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,0,Ui.dp(this,6),0);tabs.addView(b,lp);}scroller.addView(tabs);p.addView(scroller);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.addView(Ui.text(this,active.activeItems().size()+" 本",13,Ui.MUTED,false),new LinearLayout.LayoutParams(0,-2,1));ShelfStore.Shelf selected=active;bar.addView(compact("重命名",v->renameShelf(selected)));Ui.gap(bar,this,6);bar.addView(compact("删除",v->deleteShelf(selected)));p.addView(bar);RecyclerView list=collection(p,collectionMode);List<UnifiedCatalogStore.Entry> entries=new ArrayList<>();UnifiedCatalogStore.Snapshot catalog=UnifiedCatalogStore.load(this);for(ShelfStore.Item item:active.activeItems()){UnifiedCatalogStore.Entry e=catalog.byId.get(item.comicId);if(e==null){e=new UnifiedCatalogStore.Entry(item.comicId,item.title,item.author);e.canonicalAuthor=item.canonicalAuthor;e.tags.addAll(item.tags);e.categories.addAll(item.categories);e.finished=item.finished;e.knownPictures=item.knownPictures;e.inShelf=true;}entries.add(e);}list.setAdapter(new UnifiedComicCollectionAdapter(this,collectionMode,entries,this::open));restoreListPosition(list,0);if(BridgeStore.paired(this))syncShelves();}
    private void createShelf(){final EditText input=new EditText(this);input.setHint("书架名称");Ui.styleField(input,this);new AlertDialog.Builder(this).setTitle("新建书架").setView(input).setNegativeButton("取消",null).setPositiveButton("创建",(d,w)->{try{ShelfStore.Shelf shelf=ShelfStore.create(this,input.getText().toString());activeShelfId=shelf.id;prefs.edit().putString("activeShelfId",activeShelfId).apply();syncShelves();show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}).show();}
    private void renameShelf(ShelfStore.Shelf shelf){final EditText input=new EditText(this);input.setText(shelf.name);Ui.styleField(input,this);new AlertDialog.Builder(this).setTitle("重命名书架").setView(input).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{try{ShelfStore.rename(this,shelf.id,input.getText().toString());syncShelves();show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}).show();}
    private void deleteShelf(ShelfStore.Shelf shelf){new AlertDialog.Builder(this).setTitle("删除“"+shelf.name+"”？").setMessage("只删除书架，不删除漫画。") .setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{ShelfStore.delete(this,shelf.id);activeShelfId="";syncShelves();show();}).show();}
    private void syncShelves(){if(!BridgeStore.paired(this))return;worker.submit(()->{try{BridgeClient.device(this);ShelfStore.syncWithDesktop(this);runOnUiThread(()->{if(showingShelves&&!isDestroyed())show();});}catch(Exception ignored){}});}

    private void recommendations(){LinearLayout p=page(true);RecommendationProgressPanel progress=new RecommendationProgressPanel(this,()->{if(current==1&&!isDestroyed()&&!isFinishing())show();});titleRow(p,"为你推荐",Ui.iconButton(this,R.drawable.ic_refresh_24,"刷新推荐",v->{NativeRecommendationJobs.refresh(this);progress.begin();}));p.addView(progress);if(!PicaAccountStore.load(this).configured()){TextView t=Ui.text(this,"登录 Pica 后即可生成推荐",14,Ui.MUTED,false);t.setPadding(0,Ui.dp(this,20),0,Ui.dp(this,10));p.addView(t);p.addView(compact("登录 Pica",v->startActivity(new Intent(this,PicaAccountActivity.class))));return;}NativeRecommendationStore.Snapshot snapshot=NativeRecommendationStore.load(this);if(!snapshot.available()){TextView t=Ui.text(this,"还没有推荐结果",14,Ui.MUTED,false);t.setPadding(0,Ui.dp(this,20),0,Ui.dp(this,10));p.addView(t);p.addView(compact("生成推荐",v->{NativeRecommendationJobs.refresh(this);progress.begin();}));return;}LinearLayout pager=new LinearLayout(this);pager.setGravity(Gravity.CENTER_VERTICAL);pager.addView(compact("上一批",v->{NativeRecommendationStore.previousBatch(this);show();}),new LinearLayout.LayoutParams(0,-2,1));TextView batch=Ui.text(this,"第 "+(snapshot.batchIndex+1)+" / "+snapshot.batches.size()+" 批",13,Ui.MUTED,false);batch.setGravity(Gravity.CENTER);pager.addView(batch,new LinearLayout.LayoutParams(0,-1,1));pager.addView(compact("下一批",v->{NativeRecommendationStore.nextBatch(this);show();}),new LinearLayout.LayoutParams(0,-2,1));p.addView(pager);UnifiedCatalogStore.Snapshot catalog=UnifiedCatalogStore.load(this);for(NativeRecommendationStore.Item item:snapshot.current()){UnifiedCatalogStore.Entry e=catalog.byId.get(item.comicId);if(e==null)e=new UnifiedCatalogStore.Entry(item.comicId,item.title,item.author);LinearLayout card=Ui.card(this);card.setOrientation(LinearLayout.HORIZONTAL);ImageView cover=new ImageView(this);cover.setScaleType(ImageView.ScaleType.CENTER_CROP);cover.setBackgroundColor(Ui.PLACEHOLDER);card.addView(cover,new LinearLayout.LayoutParams(Ui.dp(this,86),Ui.dp(this,122)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);copy.setPadding(Ui.dp(this,12),0,0,0);copy.addView(Ui.text(this,item.title,16,Ui.TEXT,true));copy.addView(Ui.text(this,item.author,12,Ui.MUTED,false));TextView why=Ui.text(this,item.reason,12,Ui.PRIMARY,false);why.setPadding(0,Ui.dp(this,6),0,0);copy.addView(why);card.addView(copy,new LinearLayout.LayoutParams(0,-2,1));UnifiedCatalogStore.Entry target=e;card.setOnClickListener(v->open(target));CoverRepository.load(this,cover,e,Ui.PLACEHOLDER);p.addView(card);}NativeRecommendationStore.markCurrentSeen(this);}

    private void onlineEntry(){LinearLayout p=page(true);titleRow(p,"在线");p.addView(Ui.button(this,"进入在线",v->startActivity(new Intent(this,PicaBrowseActivity.class)),false));}
    private void settingsEntry(){LinearLayout p=page(true);titleRow(p,"设置");p.addView(Ui.button(this,"打开设置",v->startActivity(new Intent(this,SettingsActivity.class)),false));}
}
