package com.picalibrary.android;

import android.app.*;
import android.content.Intent;
import android.os.Bundle;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

/** Unified online discovery surface. Pica account features stay Pica-only; E-H public browse requires no account. */
public final class PicaBrowseActivity extends Activity {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private EditText search;private TextView status;private ProgressBar loading;private LinearLayout results;private int page=1;private String keyword="",category="",mode="search",sourceMode="all";private boolean destroyed;
    @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().setStatusBarColor(Ui.BG);getWindow().setNavigationBarColor(Ui.BG);render();loadPublicHome();}
    private Button button(String label,View.OnClickListener action){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextColor(Ui.PRIMARY);b.setOnClickListener(action);return b;}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.addView(button("‹ 返回",v->finish()));bar.addView(Ui.text(this,"在线发现",22,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));bar.addView(button("账号与来源",v->showAccountSources()));root.addView(bar);LinearLayout sourceRow=new LinearLayout(this);sourceRow.setGravity(Gravity.CENTER_VERTICAL);sourceRow.addView(Ui.text(this,"在线来源",13,Ui.MUTED,true),new LinearLayout.LayoutParams(0,-2,1));sourceRow.addView(button("选择来源 ▾",v->chooseSource()));root.addView(sourceRow);search=new EditText(this);search.setSingleLine(true);search.setHint("搜索 Pica / E-H 漫画");search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);search.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_SEARCH){startSearch();return true;}return false;});root.addView(search);LinearLayout actions=new LinearLayout(this);actions.addView(button("搜索",v->startSearch()),new LinearLayout.LayoutParams(0,-2,1));actions.addView(button("Pica 收藏",v->favorites()),new LinearLayout.LayoutParams(0,-2,1));actions.addView(button("Pica 24h",v->leaderboard()),new LinearLayout.LayoutParams(0,-2,1));actions.addView(button("Pica 分类",v->chooseCategory()),new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);status=Ui.text(this,"全部来源 · E-H 公共浏览无需账号",12,Ui.MUTED,false);root.addView(status);loading=new ProgressBar(this);loading.setVisibility(View.GONE);root.addView(loading);ScrollView scroll=new ScrollView(this);results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);results.setPadding(Ui.dp(this,10),Ui.dp(this,5),Ui.dp(this,10),Ui.dp(this,24));scroll.addView(results);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);root.requestApplyInsets();}
    private void chooseSource(){String[] labels={"全部可用来源","Pica","E-H 公共","ExH"};String[] values={"all","pica","eh","exh"};int checked=0;for(int i=0;i<values.length;i++)if(values[i].equals(sourceMode))checked=i;new AlertDialog.Builder(this).setTitle("选择在线来源").setSingleChoiceItems(labels,checked,(d,w)->{d.dismiss();selectSource(values[w]);}).setNegativeButton("取消",null).show();}
    private void showAccountSources(){boolean pica=PicaAccountStore.load(this).configured(),eh=EhAccountStore.load(this).configured();String[] labels={"Pica · "+(pica?"已连接":"未连接"),"E-H / ExH · "+(eh?"已连接 · 公共模式仍独立可用":"公共模式可用 · 未连接账号"),"注册 E-H 账号 · 打开官方注册页"};new AlertDialog.Builder(this).setTitle("账号与来源").setItems(labels,(d,w)->{if(w==0)startActivity(new Intent(this,PicaAccountActivity.class));else if(w==1)startActivity(new Intent(this,EhAccountActivity.class));else if(w==2)startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://forums.e-hentai.org/index.php?act=Reg&CODE=00")));}).setNegativeButton("关闭",null).show();}
    private void selectSource(String source){sourceMode=source;page=1;category="";status.setText("eh".equals(source)?"E-H 公共浏览 · 无需登录":"exh".equals(source)?"ExH · 使用已连接的 E-H 账号权限":"pica".equals(source)?"Pica 在线 · 搜索/收藏需要账号":"全部可用来源 · E-H 公共浏览无需账号");if(!search.getText().toString().trim().isEmpty())startSearch();else if("pica".equals(source)&&PicaAccountStore.load(this).configured())leaderboard();else loadPublicHome();}
    @Override protected void onResume(){super.onResume();}
    private boolean requirePica(){if(PicaAccountStore.load(this).configured())return true;new AlertDialog.Builder(this).setTitle("需要 Pica 账号").setMessage("这个操作属于 Pica 账号能力。E-H 公共搜索不需要登录。") .setNegativeButton("取消",null).setPositiveButton("去登录",(d,w)->startActivity(new Intent(this,PicaAccountActivity.class))).show();return false;}
    private void loadPublicHome(){keyword="";category="";page=1;mode="search";if("pica".equals(sourceMode)){if(PicaAccountStore.load(this).configured())leaderboard();else{results.removeAllViews();status.setText("Pica 未登录；可切换 E-H 或全部来源直接浏览");}}else loadEhOnly("");}
    private void startSearch(){keyword=search.getText().toString().trim();category="";page=1;mode="search";reload();}
    private void leaderboard(){if(!requirePica())return;sourceMode="pica";keyword="";category="";page=1;mode="leaderboard";reload();}
    private void favorites(){if(!requirePica())return;sourceMode="pica";keyword="";category="";page=1;mode="favorites";reload();}
    private void chooseCategory(){if(!requirePica())return;sourceMode="pica";busy("正在读取 Pica 分类…");worker.submit(()->{try{List<String> values=new PicaClient(this).categories();runOnUiThread(()->{if(destroyed)return;loading.setVisibility(View.GONE);new AlertDialog.Builder(this).setTitle("Pica 分类").setItems(values.toArray(new String[0]),(d,index)->{category=values.get(index);keyword="";page=1;mode="category";reload();}).show();});}catch(Exception e){fail("Pica",e);}});}
    private void reload(){if("favorites".equals(mode)){loadFavorites();return;}if("leaderboard".equals(mode)){loadLeaderboard();return;}if("category".equals(mode)){loadCategory();return;}if("eh".equals(sourceMode)){loadEhOnly(keyword,"eh");return;}if("exh".equals(sourceMode)){loadEhOnly(keyword,"exh");return;}if("pica".equals(sourceMode)){loadPicaSearch();return;}loadCombined();}
    private void loadPicaSearch(){if(!requirePica())return;busy("正在搜索 Pica…");worker.submit(()->{try{PicaClient.ComicPage value=keyword.isEmpty()?new PicaClient(this).browse("","","ld",page):new PicaClient(this).search(keyword,page,"ld",Collections.emptyList());UnifiedPicaCatalogSync.mergeAll(this,value.comics);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:value.comics)ids.add(comic.id);runOnUiThread(()->showIds(ids,"Pica · 第 "+value.page+" / "+value.pages+" 页",value.pages));}catch(Exception e){fail("Pica",e);}});}
    private void loadEhOnly(String query){loadEhOnly(query,"eh");}
    private void loadEhOnly(String query,String surface){String label="exh".equals(surface)?"ExH":"E-H 公共";busy("正在读取 "+label+"…");worker.submit(()->{try{List<EhClient.Comic> comics=new EhClient(this).search(query,surface);UnifiedEhCatalogSync.mergeAll(this,comics);List<String> ids=new ArrayList<>();for(EhClient.Comic comic:comics)ids.add(comic.id);runOnUiThread(()->showIds(ids,label+"结果 · "+ids.size()+" 本",1));}catch(Exception e){fail("E-H",e);}});}
    private void loadCombined(){busy("正在搜索 Pica + E-H…");worker.submit(()->{List<String> ids=new ArrayList<>();StringBuilder warning=new StringBuilder();if(PicaAccountStore.load(this).configured()){try{PicaClient.ComicPage value=keyword.isEmpty()?new PicaClient(this).browse("","","ld",1):new PicaClient(this).search(keyword,1,"ld",Collections.emptyList());UnifiedPicaCatalogSync.mergeAll(this,value.comics);for(PicaClient.Comic comic:value.comics)if(!ids.contains(comic.id))ids.add(comic.id);}catch(Exception e){warning.append("Pica 暂不可用；");}}try{List<EhClient.Comic> comics=new EhClient(this).search(keyword);UnifiedEhCatalogSync.mergeAll(this,comics);for(EhClient.Comic comic:comics)if(!ids.contains(comic.id))ids.add(comic.id);}catch(Exception e){warning.append("E-H 暂不可用；");}if(EhAccountStore.load(this).configured()&&"AVAILABLE".equals(new EhClient(this).probeExH()))try{List<EhClient.Comic> comics=new EhClient(this).search(keyword,"exh");UnifiedEhCatalogSync.mergeAll(this,comics);for(EhClient.Comic comic:comics)if(!ids.contains(comic.id))ids.add(comic.id);}catch(Exception e){warning.append("ExH 暂不可用；");}final String label=(warning.length()==0?"全部来源":"部分来源失败 · "+warning)+" · "+ids.size()+" 本";runOnUiThread(()->showIds(ids,label,1));});}
    private void loadCategory(){if(!requirePica())return;busy("正在读取 Pica 分类 · "+category);worker.submit(()->{try{PicaClient.ComicPage value=new PicaClient(this).browse(category,"","dd",page);UnifiedPicaCatalogSync.mergeAll(this,value.comics);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:value.comics)ids.add(comic.id);runOnUiThread(()->showIds(ids,category+" · 第 "+value.page+" / "+value.pages+" 页",value.pages));}catch(Exception e){fail("Pica",e);}});}
    private void loadFavorites(){busy("正在读取 Pica 收藏…");worker.submit(()->{try{PicaClient.ComicPage value=new PicaClient(this).favorites(page,"dd");UnifiedPicaCatalogSync.mergeAll(this,value.comics);UnifiedCatalogStore.Snapshot snapshot=UnifiedCatalogStore.load(this);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:value.comics){ids.add(comic.id);UnifiedCatalogStore.Entry entry=snapshot.byId.get(comic.id);if(entry!=null)entry.favorite=true;}UnifiedCatalogStore.save(this,snapshot);runOnUiThread(()->showIds(ids,"Pica 收藏 · 第 "+value.page+" / "+value.pages+" 页",value.pages));}catch(Exception e){fail("Pica",e);}});}
    private void loadLeaderboard(){busy("正在读取 Pica 24h 排行…");worker.submit(()->{try{List<PicaClient.Comic> comics=new PicaClient(this).leaderboard();UnifiedPicaCatalogSync.mergeAll(this,comics);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:comics)ids.add(comic.id);runOnUiThread(()->showIds(ids,"Pica 24h 排行 · "+ids.size()+" 本",1));}catch(Exception e){fail("Pica",e);}});}
    private void busy(String text){runOnUiThread(()->{loading.setVisibility(View.VISIBLE);status.setText(text);});}
    private void fail(String source,Exception e){runOnUiThread(()->{if(destroyed)return;loading.setVisibility(View.GONE);status.setText(source+" 读取失败："+(e.getMessage()==null?"未知错误":e.getMessage()));});}
    private void showIds(List<String> ids,String label,int pages){if(destroyed)return;loading.setVisibility(View.GONE);status.setText(label);results.removeAllViews();UnifiedCatalogStore.Snapshot snapshot=UnifiedCatalogStore.load(this);for(String id:ids){UnifiedCatalogStore.Entry entry=snapshot.byId.get(id);if(entry==null)continue;LinearLayout card=Ui.card(this);LinearLayout row=new LinearLayout(this);ImageView cover=new ImageView(this);cover.setScaleType(ImageView.ScaleType.CENTER_CROP);row.addView(cover,new LinearLayout.LayoutParams(Ui.dp(this,82),Ui.dp(this,116)));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);text.setPadding(Ui.dp(this,12),0,0,0);text.addView(Ui.text(this,entry.title,17,Ui.TEXT,true));text.addView(Ui.text(this,entry.displayAuthor(),12,Ui.MUTED,false));if(!entry.tags.isEmpty())text.addView(Ui.text(this,String.join(" · ",entry.tags.subList(0,Math.min(4,entry.tags.size()))),11,Ui.PRIMARY,false));String provider="eh".equals(entry.providerId)?"E-H 在线":"Pica 在线";String extra="eh".equals(entry.providerId)&&!Double.isNaN(entry.rating)?" · ★ "+String.format(Locale.ROOT,"%.2f",entry.rating):"";text.addView(Ui.text(this,provider+" · "+entry.knownPictures+" 页"+extra,11,Ui.MUTED,false));row.addView(text,new LinearLayout.LayoutParams(0,-2,1));card.addView(row);CoverRepository.load(this,cover,entry,0xffebe8ef);card.setOnClickListener(v->open(entry));results.addView(card);}if(pages>1){LinearLayout nav=new LinearLayout(this);nav.addView(button("上一页",v->{if(page>1){page--;reload();}}),new LinearLayout.LayoutParams(0,-2,1));nav.addView(button("下一页",v->{if(page<pages){page++;reload();}}),new LinearLayout.LayoutParams(0,-2,1));results.addView(nav);}}
    private void open(UnifiedCatalogStore.Entry entry){Intent i=new Intent(this,UnifiedComicDetailActivity.class);i.putExtra("comicId",entry.id);i.putExtra("title",entry.title);i.putExtra("author",entry.author);startActivity(i);}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
}
