package com.picalibrary.android;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

/** Unified online discovery. Core providers stay independent; ExH is an optional E-H capability. */
public final class PicaBrowseActivity extends LocaleAwareActivity {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private EditText search;private TextView status;private ProgressBar loading;private LinearLayout results;private int page=1;private String keyword="",category="",mode="search",sourceMode="all";private boolean destroyed;
    private EhOnlineFilterSpec ehFilter=new EhOnlineFilterSpec();private List<String> lastIds=new ArrayList<>();private String lastLabel="";private int lastPages=1;
    @Override public void onCreate(Bundle saved){super.onCreate(saved);Ui.applyWindow(this);String requested=getIntent()==null?"":getIntent().getStringExtra("sourceMode");if(requested!=null&&!requested.trim().isEmpty())sourceMode=SourceCapabilities.byId(requested).id;render();EhTagTranslationStore.scheduleUpdate(this,()->{if(!destroyed&&!lastIds.isEmpty())showIds(new ArrayList<>(lastIds),lastLabel,lastPages);});loadPublicHome();}
    private Button button(String label,View.OnClickListener action){return Ui.button(this,label,action,true);}
    private Button primaryButton(String label,View.OnClickListener action){return Ui.button(this,label,action,false);}
    private SourceCapabilities.Source source(){return SourceCapabilities.byId(sourceMode);}
    private boolean ehSurface(){return source()==SourceCapabilities.EH||source()==SourceCapabilities.EXH;}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(Ui.dp(this,8),Ui.dp(this,6),Ui.dp(this,8),Ui.dp(this,4));bar.addView(button("‹ 返回",v->finish()));bar.addView(Ui.text(this,"在线",22,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));bar.addView(Ui.iconButton(this,R.drawable.ic_person_24,"账号与来源",v->startActivity(new Intent(this,AccountSourcesActivity.class))));root.addView(bar);Button sourceButton=button(source().label+" ▾",v->chooseSource());sourceButton.setSingleLine(true);LinearLayout.LayoutParams slp=new LinearLayout.LayoutParams(-1,-2);slp.setMargins(Ui.dp(this,12),Ui.dp(this,3),Ui.dp(this,12),Ui.dp(this,4));root.addView(sourceButton,slp);search=new EditText(this);search.setSingleLine(true);search.setHint(SourceCapabilities.searchHint(source()));search.setText(keyword);search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);search.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_SEARCH){startSearch();return true;}return false;});Ui.styleField(search,this);LinearLayout.LayoutParams searchParams=new LinearLayout.LayoutParams(-1,-2);searchParams.setMargins(Ui.dp(this,12),0,Ui.dp(this,12),Ui.dp(this,4));root.addView(search,searchParams);LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER_VERTICAL);actions.setPadding(Ui.dp(this,12),Ui.dp(this,2),Ui.dp(this,12),0);Button searchAction=primaryButton("搜索",v->startSearch());searchAction.setSingleLine(true);actions.addView(searchAction,new LinearLayout.LayoutParams(0,-2,1));if(source().supportsBrowse){Ui.gap(actions,this,6);Button browse=button("浏览",v->showBrowseActions());browse.setSingleLine(true);actions.addView(browse,new LinearLayout.LayoutParams(-2,-2));}if(ehSurface()){Ui.gap(actions,this,6);Button filter=button(filterLabel(),v->EhOnlineFilterDialog.show(this,ehFilter,value->{ehFilter=value;ehFilter.mode=EhOnlineFilterSpec.Mode.LATEST;page=1;render();reload();}));filter.setSingleLine(true);actions.addView(filter,new LinearLayout.LayoutParams(-2,-2));}root.addView(actions);status=Ui.text(this,"",12,Ui.MUTED,false);status.setVisibility(View.GONE);status.setPadding(Ui.dp(this,12),Ui.dp(this,4),Ui.dp(this,12),Ui.dp(this,2));root.addView(status);loading=new ProgressBar(this);loading.setVisibility(View.GONE);root.addView(loading);ScrollView scroll=new ScrollView(this);results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);results.setPadding(Ui.dp(this,10),Ui.dp(this,5),Ui.dp(this,10),Ui.dp(this,24));scroll.addView(results);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);root.requestApplyInsets();}
    private String filterLabel(){int n=0;if(ehFilter.includeCategories!=EhOnlineFilterSpec.ALL)n++;if(!ehFilter.language.isEmpty())n++;if(!ehFilter.includeTags.isEmpty())n++;if(!ehFilter.excludeTags.isEmpty())n++;if(ehFilter.minRating>0)n++;if(ehFilter.pageFrom>0||ehFilter.pageTo>0)n++;return n==0?"筛选":"筛选 "+n;}
    private void chooseSource(){SourceCapabilities.Source[] sources=SourceCapabilities.values();String[] labels=new String[sources.length];int checked=0;EhCapabilityStore.Snapshot exh=EhCapabilityStore.load(this);for(int i=0;i<sources.length;i++){SourceCapabilities.Source s=sources[i];labels[i]=s.label;if(s==SourceCapabilities.PICA){boolean local=PicaAccountStore.load(this).configured();if(!PicaClient.available(this))labels[i]+=" · 未连接";else if(!local)labels[i]+=" · Desktop";}if(s==SourceCapabilities.EXH)labels[i]+=" · 可选 · "+exh.label();if(s.id.equals(sourceMode))checked=i;}new AlertDialog.Builder(this).setTitle(LocalizedText.ui("选择来源")).setSingleChoiceItems(labels,checked,(d,w)->{d.dismiss();selectSource(sources[w].id);}).setNegativeButton(LocalizedText.ui("取消"),null).show();}
    private void selectSource(String value){keyword=search==null?keyword:search.getText().toString().trim();sourceMode=SourceCapabilities.byId(value).id;page=1;category="";mode="search";render();if(keyword.isEmpty())loadPublicHome();else reload();}
    private void showBrowseActions(){SourceCapabilities.Source s=source();if(s==SourceCapabilities.PICA){String[] labels={"我的收藏","排行榜","分类"};new AlertDialog.Builder(this).setTitle(LocalizedText.ui("浏览")).setItems(labels,(d,w)->{if(w==0)favorites();else if(w==1)leaderboard();else chooseCategory();}).setNegativeButton(LocalizedText.ui("取消"),null).show();return;}if(s==SourceCapabilities.EH||s==SourceCapabilities.EXH){boolean isEh=s==SourceCapabilities.EH;String[] labels=isEh?new String[]{"最新","热门","我的收藏","关注","分类","排行榜"}:new String[]{"最新","热门","我的收藏","关注","分类"};new AlertDialog.Builder(this).setTitle(LocalizedText.ui("浏览")).setItems(labels,(d,w)->{if(w==0)setEhMode(EhOnlineFilterSpec.Mode.LATEST);else if(w==1)setEhMode(EhOnlineFilterSpec.Mode.POPULAR);else if(w==2)chooseEhFavorites();else if(w==3){if(requireEh())setEhMode(EhOnlineFilterSpec.Mode.WATCHED);}else if(w==4)chooseEhCategory();else chooseEhToplist();}).setNegativeButton(LocalizedText.ui("取消"),null).show();}}
    private void setEhMode(EhOnlineFilterSpec.Mode value){ehFilter.mode=value;if(value!=EhOnlineFilterSpec.Mode.LATEST&&value!=EhOnlineFilterSpec.Mode.WATCHED){keyword="";if(search!=null)search.setText("");}page=1;mode="search";reload();}
    private boolean requirePica(){if(PicaClient.available(this))return true;new AlertDialog.Builder(this).setTitle(LocalizedText.ui("需要登录 Pica")).setMessage(LocalizedText.ui("此操作需要登录 Pica。")) .setNegativeButton(LocalizedText.ui("取消"),null).setPositiveButton(LocalizedText.ui("去登录"),(d,w)->startActivity(new Intent(this,PicaAccountActivity.class))).show();return false;}
    private boolean requireEh(){if(EhClient.accountAvailable(this))return true;new AlertDialog.Builder(this).setTitle(LocalizedText.ui("需要 E-H 账号")).setMessage(LocalizedText.ui("可以在手机登录，或先配对一台已经登录 E-H 的电脑。")).setNegativeButton(LocalizedText.ui("取消"),null).setPositiveButton(LocalizedText.ui("账号与来源"),(d,w)->startActivity(new Intent(this,EhAccountActivity.class))).show();return false;}
    private void loadPublicHome(){keyword="";category="";page=1;mode="search";SourceCapabilities.Source s=source();if(s==SourceCapabilities.PICA){if(PicaClient.available(this))loadPicaSearch();else showPicaUnavailable();}else if(s==SourceCapabilities.EH)loadEhOnly("","eh");else if(s==SourceCapabilities.EXH){if(EhClient.accountAvailable(this))loadEhOnly("","exh");else showExhProblem(EhCapabilityStore.load(this));}else loadCombined();}
    private void showPicaUnavailable(){loading.setVisibility(View.GONE);hideStatus();results.removeAllViews();LinearLayout card=Ui.card(this);card.addView(Ui.text(this,"Pica",17,Ui.TEXT,true));card.addView(SettingsRow.statusLine(this,"账号","未登录"));LinearLayout row=new LinearLayout(this);row.addView(primaryButton("登录",v->startActivity(new Intent(this,PicaAccountActivity.class))),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(row,this,8);row.addView(button("注册账号",v->startActivity(new Intent(this,PicaRegisterActivity.class))),new LinearLayout.LayoutParams(0,-2,1));card.addView(row);results.addView(card);}
    private void startSearch(){keyword=search.getText().toString().trim();category="";page=1;mode="search";if(ehSurface()){ehFilter.mode=EhOnlineFilterSpec.Mode.LATEST;ehFilter.freeText=keyword;}reload();}
    private void leaderboard(){if(!requirePica())return;keyword="";search.setText("");category="";page=1;mode="leaderboard";reload();}
    private void favorites(){if(!requirePica())return;keyword="";search.setText("");category="";page=1;mode="favorites";reload();}
    private void chooseCategory(){if(!requirePica())return;busy();worker.submit(()->{try{List<String> values=new PicaClient(this).categories();runOnUiThread(()->{if(destroyed)return;loading.setVisibility(View.GONE);hideStatus();new AlertDialog.Builder(this).setTitle(LocalizedText.ui("分类")).setItems(values.toArray(new String[0]),(d,index)->{category=values.get(index);keyword="";search.setText("");page=1;mode="category";reload();}).show();});}catch(Exception e){fail("Pica",e);}});}
    private void chooseEhCategory(){int[] bits=EhOnlineFilterSpec.categoryBits();String[] labels=new String[bits.length];for(int i=0;i<bits.length;i++)labels[i]=EhOnlineFilterSpec.categoryLabel(bits[i]);new AlertDialog.Builder(this).setTitle(LocalizedText.ui("分类")).setItems(labels,(d,w)->{ehFilter.includeCategories=bits[w];ehFilter.mode=EhOnlineFilterSpec.Mode.LATEST;keyword="";search.setText("");page=1;render();reload();}).setNegativeButton(LocalizedText.ui("取消"),null).show();}
    private void chooseEhToplist(){String[] labels={"全期","过去一年","过去一个月","昨日"};String[] values={"11","12","13","15"};new AlertDialog.Builder(this).setTitle(LocalizedText.ui("排行榜")).setItems(labels,(d,w)->{ehFilter.toplist=values[w];setEhMode(EhOnlineFilterSpec.Mode.TOPLIST);}).setNegativeButton(LocalizedText.ui("取消"),null).show();}
    private void chooseEhFavorites(){if(!requireEh())return;busy();worker.submit(()->{try{EhFavoriteSync sync=new EhClient(this).favoritesSnapshot();UnifiedEhCatalogSync.mergeAll(this,sync.comics);EhFavoriteStore.replaceRemote(this,sync);runOnUiThread(()->{if(destroyed)return;loading.setVisibility(View.GONE);hideStatus();String[] labels=new String[11];labels[0]="全部收藏 · "+sync.comics.size();for(int i=0;i<10;i++){String name=i<sync.categoryNames.size()?sync.categoryNames.get(i):"Favorites "+i;labels[i+1]=name+" · "+sync.categoryCounts[i];}new AlertDialog.Builder(this).setTitle(LocalizedText.ui("我的收藏")).setItems(labels,(d,w)->showEhFavoriteSelection(sync,w-1)).setNegativeButton(LocalizedText.ui("取消"),null).show();});}catch(Exception e){fail("E-H",e);}});}
    private void showEhFavoriteSelection(EhFavoriteSync sync,int slot){ehFilter.mode=EhOnlineFilterSpec.Mode.FAVORITES;ehFilter.favoriteSlot=slot;List<String> ids=new ArrayList<>();Set<String> allowed=new LinkedHashSet<>();for(EhFavoriteSync.Item item:sync.items)if(slot<0||item.slot==slot)allowed.add(item.comicId);for(EhClient.Comic comic:sync.comics)if(allowed.contains(comic.id))ids.add(comic.id);String name=slot<0?"全部收藏":slot<sync.categoryNames.size()?sync.categoryNames.get(slot):"Favorites "+slot;showIds(ids,name+" · "+ids.size()+" 本",1);}
    private void reload(){if("favorites".equals(mode)){loadFavorites();return;}if("leaderboard".equals(mode)){loadLeaderboard();return;}if("category".equals(mode)){loadCategory();return;}SourceCapabilities.Source s=source();if(s==SourceCapabilities.EH){loadEhOnly(keyword,"eh");return;}if(s==SourceCapabilities.EXH){if(EhClient.accountAvailable(this))loadEhOnly(keyword,"exh");else showExhProblem(EhCapabilityStore.load(this));return;}if(s==SourceCapabilities.PICA){if(PicaClient.available(this))loadPicaSearch();else showPicaUnavailable();return;}loadCombined();}
    private void loadPicaSearch(){if(!requirePica())return;busy();worker.submit(()->{try{PicaClient.ComicPage value=keyword.isEmpty()?new PicaClient(this).browse("","","ld",page):new PicaClient(this).search(keyword,page,"ld",Collections.emptyList());UnifiedPicaCatalogSync.mergeAll(this,value.comics);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:value.comics)ids.add(comic.id);runOnUiThread(()->showIds(ids,"第 "+value.page+" / "+value.pages+" 页",value.pages));}catch(Exception e){fail("Pica",e);}});}
    private void loadEhOnly(String query,String surface){String label="exh".equals(surface)?"ExHentai":"E-Hentai";busy();worker.submit(()->{try{EhOnlineFilterSpec spec=ehFilter.copy();spec.freeText=query==null?"":query;List<EhClient.Comic> comics=new EhClient(this).browse(spec,surface);UnifiedEhCatalogSync.mergeAll(this,comics);List<String> ids=new ArrayList<>();for(EhClient.Comic comic:comics)ids.add(comic.id);String modeLabel=ehModeLabel(spec);runOnUiThread(()->showIds(ids,label+" · "+modeLabel+" · "+ids.size()+" 本",1));}catch(Exception e){fail(label,e);}});}
    private String ehModeLabel(EhOnlineFilterSpec spec){if(spec.mode==EhOnlineFilterSpec.Mode.POPULAR)return "热门";if(spec.mode==EhOnlineFilterSpec.Mode.WATCHED)return "关注";if(spec.mode==EhOnlineFilterSpec.Mode.TOPLIST)return "排行榜";if(spec.mode==EhOnlineFilterSpec.Mode.FAVORITES)return "收藏";return "最新";}
    private void loadCombined(){busy();worker.submit(()->{List<String> ids=new ArrayList<>();boolean corePartial=false;if(PicaClient.available(this))try{PicaClient.ComicPage value=keyword.isEmpty()?new PicaClient(this).browse("","","ld",1):new PicaClient(this).search(keyword,1,"ld",Collections.emptyList());UnifiedPicaCatalogSync.mergeAll(this,value.comics);for(PicaClient.Comic comic:value.comics)if(!ids.contains(comic.id))ids.add(comic.id);}catch(Exception e){corePartial=true;}try{List<EhClient.Comic> comics=new EhClient(this).search(keyword);UnifiedEhCatalogSync.mergeAll(this,comics);for(EhClient.Comic comic:comics)if(!ids.contains(comic.id))ids.add(comic.id);}catch(Exception e){corePartial=true;}if(EhClient.accountAvailable(this)){try{EhCapabilityStore.Snapshot capability=EhCapabilityStore.refresh(this,false);if(capability.available()){List<EhClient.Comic> comics=new EhClient(this).search(keyword,"exh");UnifiedEhCatalogSync.mergeAll(this,comics);for(EhClient.Comic comic:comics)if(!ids.contains(comic.id))ids.add(comic.id);}}catch(Exception ignored){}}final boolean someCoreFailed=corePartial;runOnUiThread(()->{showIds(ids,ids.size()+" 本",1);if(someCoreFailed)showStatus("部分核心来源不可用",Ui.BAD);});});}
    private void loadCategory(){if(!requirePica())return;busy();worker.submit(()->{try{PicaClient.ComicPage value=new PicaClient(this).browse(category,"","dd",page);UnifiedPicaCatalogSync.mergeAll(this,value.comics);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:value.comics)ids.add(comic.id);runOnUiThread(()->showIds(ids,category+" · 第 "+value.page+" / "+value.pages+" 页",value.pages));}catch(Exception e){fail("Pica",e);}});}
    private void loadFavorites(){busy();worker.submit(()->{try{PicaClient.ComicPage value=new PicaClient(this).favorites(page,"dd");UnifiedPicaCatalogSync.mergeAll(this,value.comics);UnifiedCatalogStore.Snapshot snapshot=UnifiedCatalogStore.load(this);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:value.comics){ids.add(comic.id);UnifiedCatalogStore.Entry entry=snapshot.byId.get(comic.id);if(entry!=null)entry.favorite=true;}UnifiedCatalogStore.save(this,snapshot);runOnUiThread(()->showIds(ids,"收藏 · 第 "+value.page+" / "+value.pages+" 页",value.pages));}catch(Exception e){fail("Pica",e);}});}
    private void loadLeaderboard(){busy();worker.submit(()->{try{List<PicaClient.Comic> comics=new PicaClient(this).leaderboard();UnifiedPicaCatalogSync.mergeAll(this,comics);List<String> ids=new ArrayList<>();for(PicaClient.Comic comic:comics)ids.add(comic.id);runOnUiThread(()->showIds(ids,"排行榜 · "+ids.size()+" 本",1));}catch(Exception e){fail("Pica",e);}});}
    private void busy(){runOnUiThread(()->{loading.setVisibility(View.VISIBLE);showStatus("正在加载…",Ui.MUTED);});}
    private void fail(String sourceName,Exception e){runOnUiThread(()->{if(destroyed)return;loading.setVisibility(View.GONE);String m=e.getMessage()==null?"":e.getMessage();if(m.contains("会话无效")||m.contains("已过期")){showStatus("登录会话已过期",Ui.BAD);return;}if(sourceName.contains("ExH")&&(m.contains("当前不可访问")||m.contains("暂无法确认")||m.contains("需要先连接"))){showExhProblem(EhCapabilityStore.load(this));return;}showStatus(m.isEmpty()?sourceName+" 暂时不可用":sourceName+" · "+m,Ui.BAD);});}
    private void showExhProblem(EhCapabilityStore.Snapshot capability){loading.setVisibility(View.GONE);results.removeAllViews();hideStatus();LinearLayout card=Ui.card(this);card.addView(Ui.text(this,"ExHentai · 可选扩展",17,Ui.TEXT,true));card.addView(SettingsRow.statusLine(this,"状态",capability.label()));LinearLayout row=new LinearLayout(this);if(EhClient.accountAvailable(this))row.addView(primaryButton("重新检查",v->recheckExh()),new LinearLayout.LayoutParams(0,-2,1));else row.addView(primaryButton("连接 E-H 账号",v->startActivity(new Intent(this,EhAccountActivity.class))),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(row,this,8);row.addView(button("切换到 E-H",v->selectSource("eh")),new LinearLayout.LayoutParams(0,-2,1));card.addView(row);results.addView(card);}
    private void recheckExh(){busy();worker.submit(()->{EhCapabilityStore.Snapshot capability=EhCapabilityStore.refresh(this,true);runOnUiThread(()->{if(destroyed)return;if(capability.available())reload();else showExhProblem(capability);});});}
    private String onlineLabel(UnifiedCatalogStore.Entry entry){if(!"eh".equals(entry.providerId))return "Pica";boolean eh=entry.sourceBindings.contains("eh"),exh=entry.sourceBindings.contains("exh");if(eh&&exh)return "E-H · ExH";return exh?"ExH":"E-H";}
    private String cardTags(UnifiedCatalogStore.Entry entry,EhSemanticStore.Snapshot semantics,EhTagTranslationStore translations){if(!"eh".equals(entry.providerId))return entry.tags.isEmpty()?"":String.join(" · ",entry.tags.subList(0,Math.min(3,entry.tags.size())));EhSemanticStore.Record record=semantics.byComicId.get(entry.id);if(record==null||record.rawTags.isEmpty())return entry.tags.isEmpty()?"":String.join(" · ",entry.tags.subList(0,Math.min(3,entry.tags.size())));ArrayList<String> labels=new ArrayList<>();for(EhSemanticStore.Tag tag:record.rawTags){if("language".equals(tag.namespace)||"reclass".equals(tag.namespace))continue;String value=translations.display(tag.namespace,tag.value);if(!labels.contains(value))labels.add(value);if(labels.size()>=3)break;}return String.join(" · ",labels);}
    private void showIds(List<String> ids,String label,int pages){if(destroyed)return;lastIds=new ArrayList<>(ids);lastLabel=label;lastPages=pages;loading.setVisibility(View.GONE);showStatus(label,Ui.MUTED);results.removeAllViews();UnifiedCatalogStore.Snapshot snapshot=UnifiedCatalogStore.load(this);EhSemanticStore.Snapshot semantics=EhSemanticStore.load(this);EhTagTranslationStore translations=EhTagTranslationStore.load(this);for(String id:ids){UnifiedCatalogStore.Entry entry=snapshot.byId.get(id);if(entry==null)continue;LinearLayout card=Ui.card(this);LinearLayout row=new LinearLayout(this);ImageView cover=new ImageView(this);cover.setScaleType(ImageView.ScaleType.CENTER_CROP);row.addView(cover,new LinearLayout.LayoutParams(Ui.dp(this,82),Ui.dp(this,116)));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);text.setPadding(Ui.dp(this,12),0,0,0);text.addView(Ui.text(this,entry.title,17,Ui.TEXT,true));text.addView(Ui.text(this,entry.displayAuthor(),12,Ui.MUTED,false));String tags=cardTags(entry,semantics,translations);if(!tags.isEmpty())text.addView(Ui.text(this,tags,11,Ui.PRIMARY,false));text.addView(Ui.text(this,onlineLabel(entry),11,Ui.MUTED,false));row.addView(text,new LinearLayout.LayoutParams(0,-2,1));card.addView(row);CoverRepository.load(this,cover,entry,0xffebe8ef);card.setOnClickListener(v->open(entry));results.addView(card);}if(pages>1){LinearLayout nav=new LinearLayout(this);nav.addView(button("上一页",v->{if(page>1){page--;reload();}}),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(nav,this,6);nav.addView(button("下一页",v->{if(page<pages){page++;reload();}}),new LinearLayout.LayoutParams(0,-2,1));results.addView(nav);}}
    private void showStatus(String text,int color){status.setText(text);status.setTextColor(color);status.setVisibility(text==null||text.isEmpty()?View.GONE:View.VISIBLE);}
    private void hideStatus(){if(status!=null)status.setVisibility(View.GONE);}
    private void open(UnifiedCatalogStore.Entry entry){Intent i=new Intent(this,UnifiedComicDetailActivity.class);i.putExtra("comicId",entry.id);i.putExtra("title",entry.title);i.putExtra("author",entry.author);startActivity(i);}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
}