package com.picalibrary.android;

import android.app.Activity;
import android.widget.*;

public class RemoteStorageActivity extends Activity {
    private EditText url,root,user,password;private TextView status;
    @Override public void onCreate(android.os.Bundle b){super.onCreate(b);Ui.applyWindow(this);render();}
    private Button button(String text){return Ui.button(this,text,v->{},false);}
    private void render(){RemoteConfigStore.Config c=RemoteConfigStore.load(this);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(Ui.BG);scroll.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setBackgroundColor(Ui.BG);p.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,24));scroll.addView(p);p.addView(Ui.text(this,"WebDAV",27,Ui.TEXT,true));Ui.gap(p,this,12);url=field(p,"地址",c.baseUrl,"https://...");root=field(p,"根目录",c.root,"PicaLibrary");user=field(p,"用户名","","留空则保留已保存用户名");password=field(p,"密码 / App Password","","留空则保留已保存密码");password.setInputType(0x00000081);status=Ui.text(this,c.configured()?"已配置":"尚未配置",13,Ui.MUTED,false);status.setPadding(0,Ui.dp(this,8),0,Ui.dp(this,8));p.addView(status);LinearLayout actions=new LinearLayout(this);Button test=button("测试连接"),save=button("保存");actions.addView(test,new LinearLayout.LayoutParams(0,-2,1));Ui.gap(actions,this,8);actions.addView(save,new LinearLayout.LayoutParams(0,-2,1));p.addView(actions);test.setOnClickListener(v->test(false));save.setOnClickListener(v->test(true));Button refresh=button("刷新云端状态");refresh.setOnClickListener(v->refreshPortableState());p.addView(refresh);Button clear=button("清除 WebDAV 配置");clear.setOnClickListener(v->{RemoteConfigStore.clear(this);finish();});p.addView(clear);setContentView(scroll);scroll.requestApplyInsets();}
    private EditText field(LinearLayout p,String label,String value,String hint){p.addView(Ui.text(this,label,13,Ui.TEXT,true));EditText e=new EditText(this);e.setSingleLine(true);e.setText(value);e.setHint(hint);Ui.styleField(e,this);p.addView(e);Ui.gap(p,this,8);return e;}
    private void test(boolean save){status.setText(save?"正在保存并连接…":"正在测试…");new Thread(()->{try{RemoteConfigStore.Config old=RemoteConfigStore.load(this);RemoteConfigStore.Config candidate=RemoteConfigStore.candidate(url.getText().toString(),root.getText().toString(),user.getText().toString(),password.getText().toString(),old);boolean ok=new RemoteLibraryClient(candidate).test();if(save&&ok){RemoteConfigStore.save(this,candidate.baseUrl,candidate.root,candidate.username,candidate.password);try{cachePortableState();}catch(Exception ignored){}}runOnUiThread(()->{status.setText(ok?(save?"已保存并连接成功":"连接成功"):"连接不可用");if(save&&ok){password.setText("");user.setText("");}});}catch(Exception e){runOnUiThread(()->status.setText("连接失败："+(e.getMessage()==null?"请检查配置":e.getMessage())));}}).start();}
    private void cachePortableState() throws Exception {RemoteLibraryClient client=new RemoteLibraryClient(this);UnifiedRemoteCatalogSync.refresh(this);FavoriteCacheStore.Snapshot favorites=FavoriteCacheStore.fromRemote(client.favorites());FavoriteCacheStore.save(this,favorites.items,false);if(ShelfStore.load(this).activeShelves().isEmpty())try{ShelfStore.save(this,ShelfStore.fromRemote(client.shelves()));}catch(Exception ignored){}try{ReaderSettingsStore.reconcile(this);}catch(Exception ignored){}UnifiedCatalogStore.reconcileLocalReferences(this);StoragePolicy.maintain(this);}
    private void refreshPortableState(){if(!RemoteConfigStore.load(this).configured()){status.setText("请先保存 WebDAV 配置");return;}status.setText("正在刷新…");new Thread(()->{try{cachePortableState();runOnUiThread(()->status.setText("云端状态已刷新"));}catch(Exception e){runOnUiThread(()->status.setText("刷新失败："+(e.getMessage()==null?"请稍后重试":e.getMessage())));}}).start();}
}
