package com.picalibrary.android;

import android.content.Context;
import android.graphics.Color;
import android.graphics.Shader;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.LayerDrawable;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.*;
import org.json.*;

/** Data-only theme packs. No executable/script/html payload is accepted. */
final class ThemePackStore {
    static final int FORMAT=1;
    private static final long MAX_ARCHIVE=24L*1024*1024,MAX_ENTRY=8L*1024*1024;private static final int MAX_ENTRIES=120;
    private static final String PREF="theme-pack-v1",KEY_ACTIVE="active";
    private static final Set<String> TYPOGRAPHY=new HashSet<>(Arrays.asList("default","rounded","comic","cute"));
    private static final Set<String> PROGRESS_STYLE=new HashSet<>(Arrays.asList("classic","star","mascot","paw"));
    private static final Set<String> PROGRESS_MOTION=new HashSet<>(Arrays.asList("none","bobble","hop"));
    static final class Pack {final String id,name,author,version,description;Pack(String id,String name,String author,String version,String description){this.id=id;this.name=name;this.author=author;this.version=version;this.description=description;}}
    private ThemePackStore(){}
    private static File root(Context c){File f=new File(c.getFilesDir(),"theme-packs-v1");f.mkdirs();return f;}
    private static File dir(Context c,String id){return new File(root(c),id);}
    static String activeId(Context c){return StarAccessStore.enabled(c)?c.getSharedPreferences(PREF,Context.MODE_PRIVATE).getString(KEY_ACTIVE,""):"";}
    static void deactivate(Context c){c.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().remove(KEY_ACTIVE).apply();}
    static void activate(Context c,String id){if(!StarAccessStore.enabled(c))throw new SecurityException("个性化装扮尚未解锁");if(readPack(dir(c,id))==null)throw new IllegalArgumentException("装扮包不存在");c.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().putString(KEY_ACTIVE,id).apply();}
    static List<Pack> list(Context c){ensureBuiltin(c);List<Pack> out=new ArrayList<>();File[] dirs=root(c).listFiles(File::isDirectory);if(dirs!=null)for(File d:dirs){Pack p=readPack(d);if(p!=null)out.add(p);}out.sort(Comparator.comparing(a->a.name.toLowerCase(Locale.ROOT)));return out;}
    private static void ensureBuiltin(Context c){File d=root(c);File t=new File(d,"pica-violet-star");File marker=new File(t,".official-v1");if(marker.exists())return;delete(t);t.mkdirs();try(InputStream raw=c.getAssets().open("pica-violet-default.pica-theme");ZipInputStream zip=new ZipInputStream(raw)){ZipEntry e;byte[] buf=new byte[8192];while((e=zip.getNextEntry())!=null){if(e.isDirectory())continue;String safe=safePath(e.getName());if(!allowed(safe))throw new IOException("unsupported bundled theme asset");File out=new File(t,safe);out.getParentFile().mkdirs();try(FileOutputStream stream=new FileOutputStream(out)){int n;long total=0;while((n=zip.read(buf))>0){total+=n;if(total>MAX_ENTRY)throw new IOException("bundled theme asset too large");stream.write(buf,0,n);}}}JSONObject manifest=new JSONObject(read(new File(t,"manifest.json")));if(manifest.optInt("themeFormatVersion")!=1||!"pica-violet-star".equals(manifest.optString("id")))throw new IOException("bundled theme manifest invalid");marker.createNewFile();delete(new File(d,"pica-violet"));}catch(Exception e){delete(t);t.mkdirs();try{write(new File(t,"manifest.json"),"{\"themeFormatVersion\":1,\"id\":\"pica-violet-star\",\"name\":\"Pica Violet · 星漫\",\"author\":\"Pica Library\",\"version\":\"1.0.0\",\"description\":\"官方 Star 首发装扮\"}");write(new File(t,"palette.json"),"{\"light\":{\"primary\":\"#7958D8\",\"background\":\"#F8F4FC\",\"surface\":\"#FFF9FF\",\"nav\":\"#F0E8F7\",\"text\":\"#241E2A\",\"muted\":\"#736A7B\",\"outline\":\"#D8CCE2\",\"action\":\"#EEE5F4\",\"progressTrack\":\"#E5D9F0\",\"progressFill\":\"#8A63E6\"},\"dark\":{\"primary\":\"#E58AB8\",\"background\":\"#100A10\",\"surface\":\"#21131E\",\"nav\":\"#170E16\",\"text\":\"#FFF7FB\",\"muted\":\"#CDBBC7\",\"outline\":\"#5A364C\",\"action\":\"#37212F\",\"progressTrack\":\"#432537\",\"progressFill\":\"#E16F9F\"}}");write(new File(t,"layout.json"),"{\"cardRadiusDp\":20,\"coverRadiusDp\":14,\"density\":\"standard\"}");write(new File(t,"components.json"),"{\"typography\":{\"title\":\"rounded\",\"navigation\":\"rounded\"},\"navigation\":{\"selectedEffect\":\"glow\",\"iconScale\":\"standard\"},\"progress\":{\"style\":\"mascot\",\"motion\":\"bobble\",\"effect\":\"sparkle\"},\"reader\":{\"chrome\":\"themed\"}}");marker.createNewFile();}catch(Exception ignored){}}}
    static Pack install(Context c,byte[] archive) throws Exception {if(!StarAccessStore.enabled(c))throw new SecurityException("个性化装扮尚未解锁");if(archive==null||archive.length==0||archive.length>MAX_ARCHIVE)throw new IllegalArgumentException("装扮包大小不合法");File staging=new File(root(c),".staging-"+UUID.randomUUID());staging.mkdirs();int entries=0;try(ZipInputStream zip=new ZipInputStream(new ByteArrayInputStream(archive))){ZipEntry entry;byte[] buf=new byte[8192];while((entry=zip.getNextEntry())!=null){if(entry.isDirectory())continue;if(++entries>MAX_ENTRIES)throw new IllegalArgumentException("装扮包文件过多");String safe=safePath(entry.getName());if(!allowed(safe))throw new IllegalArgumentException("不允许的装扮文件："+safe);File out=new File(staging,safe);File parent=out.getParentFile();if(parent!=null)parent.mkdirs();long size=0;try(OutputStream os=new FileOutputStream(out)){int n;while((n=zip.read(buf))>0){size+=n;if(size>MAX_ENTRY)throw new IllegalArgumentException("装扮资源过大："+safe);os.write(buf,0,n);}}}}
        Pack pack=readPack(staging);if(pack==null)throw new IllegalArgumentException("manifest.json 无效");validateJsonFiles(staging);File target=dir(c,pack.id),backup=new File(root(c),".backup-"+pack.id);delete(backup);if(target.exists()&&!target.renameTo(backup))throw new IOException("无法备份旧装扮");if(!staging.renameTo(target)){if(backup.exists())backup.renameTo(target);throw new IOException("无法安装装扮");}delete(backup);return pack;
    }
    static boolean applyToUi(Context c,boolean dark){if(!StarAccessStore.enabled(c))return false;String id=activeId(c);if(id.isEmpty())return false;File palette=new File(dir(c,id),"palette.json");if(!palette.isFile())return false;try{JSONObject root=new JSONObject(read(palette));JSONObject p=root.optJSONObject(dark?"dark":"light");if(p==null)return false;Ui.BG=color(p,"background",Ui.BG);Ui.SURFACE=color(p,"surface",Ui.SURFACE);Ui.NAV=color(p,"nav",Ui.NAV);Ui.PRIMARY=color(p,"primary",Ui.PRIMARY);Ui.PRIMARY_SOFT=color(p,"primarySoft",Ui.PRIMARY_SOFT);Ui.TEXT=color(p,"text",Ui.TEXT);Ui.MUTED=color(p,"muted",Ui.MUTED);Ui.OUTLINE=color(p,"outline",Ui.OUTLINE);Ui.ACTION=color(p,"action",Ui.ACTION);return true;}catch(Exception e){return false;}}
    static Drawable backgroundDrawable(Context c){File legacy=activeAsset(c,"background");if(legacy!=null)return Drawable.createFromPath(legacy.getAbsolutePath());File pattern=activeAsset(c,"pattern");if(pattern==null)return null;try{BitmapDrawable tile=new BitmapDrawable(c.getResources(),pattern.getAbsolutePath());tile.setTileModeX(Shader.TileMode.REPEAT);tile.setTileModeY(Shader.TileMode.REPEAT);double opacity=component(c,"background").optDouble(ThemeStore.isDark(c)?"patternOpacityDark":"patternOpacityLight",0.08d);tile.setAlpha((int)Math.round(Math.max(0d,Math.min(.18d,opacity))*255d));return new LayerDrawable(new Drawable[]{new ColorDrawable(Color.rgb(Color.red(Ui.BG),Color.green(Ui.BG),Color.blue(Ui.BG))),tile});}catch(Exception e){return null;}}
    static Drawable headerDrawable(Context c){File f=activeAsset(c,"library_header");if(f==null)f=activeAsset(c,"mascot-main");return f==null?null:Drawable.createFromPath(f.getAbsolutePath());}
    static Drawable mascotHeadDrawable(Context c){File f=activeAsset(c,"mascot-head");return f==null?null:Drawable.createFromPath(f.getAbsolutePath());}
    static Drawable recommendationLoadingDrawable(Context c){File f=activeAsset(c,"recommendation-loading");return f==null?null:Drawable.createFromPath(f.getAbsolutePath());}
    static Drawable emptyStateDrawable(Context c){File f=activeAsset(c,"empty-state");return f==null?null:Drawable.createFromPath(f.getAbsolutePath());}
    static Drawable navDrawable(Context c,String label){String base="书库".equals(label)?"nav-library":"推荐".equals(label)?"nav-recommend":"在线".equals(label)?"nav-online":"连接".equals(label)?"nav-connect":"";File f=base.isEmpty()?null:activeAsset(c,base);return f==null?null:Drawable.createFromPath(f.getAbsolutePath());}
    static boolean hasBackground(Context c){return activeAsset(c,"background")!=null||activeAsset(c,"pattern")!=null;}
    static int cardRadiusDp(Context c){try{return clamp(json(c,"layout.json").optInt("cardRadiusDp",20),8,28);}catch(Exception e){return 20;}}
    static int coverRadiusDp(Context c){try{return clamp(json(c,"layout.json").optInt("coverRadiusDp",14),4,24);}catch(Exception e){return 14;}}
    static String navigationTypography(Context c){return preset(component(c,"typography"),"navigation",TYPOGRAPHY,"default");}
    static String progressStyle(Context c){return preset(component(c,"progress"),"style",PROGRESS_STYLE,"classic");}
    static String progressMotion(Context c){return preset(component(c,"progress"),"motion",PROGRESS_MOTION,"none");}
    static boolean progressSparkle(Context c){return "sparkle".equals(component(c,"progress").optString("effect","none"));}
    static int progressFill(Context c){try{JSONObject p=json(c,"palette.json").optJSONObject(ThemeStore.isDark(c)?"dark":"light");return p==null?Ui.PRIMARY:color(p,"progressFill",Ui.PRIMARY);}catch(Exception e){return Ui.PRIMARY;}}
    static int progressTrack(Context c){try{JSONObject p=json(c,"palette.json").optJSONObject(ThemeStore.isDark(c)?"dark":"light");return p==null?Ui.PRIMARY_SOFT:color(p,"progressTrack",Ui.PRIMARY_SOFT);}catch(Exception e){return Ui.PRIMARY_SOFT;}}
    private static JSONObject component(Context c,String name){try{JSONObject root=json(c,"components.json");JSONObject value=root.optJSONObject(name);return value==null?new JSONObject():value;}catch(Exception e){return new JSONObject();}}
    private static JSONObject json(Context c,String name) throws Exception{String id=activeId(c);if(id.isEmpty())return new JSONObject();File f=new File(dir(c,id),name);return f.isFile()?new JSONObject(read(f)):new JSONObject();}
    private static String preset(JSONObject root,String key,Set<String> allowed,String fallback){String value=root.optString(key,fallback);return allowed.contains(value)?value:fallback;}
    private static int clamp(int value,int min,int max){return Math.max(min,Math.min(max,value));}
    private static File activeAsset(Context c,String base){if(!StarAccessStore.enabled(c))return null;String id=activeId(c);if(id.isEmpty())return null;File assets=new File(dir(c,id),"assets");for(String ext:new String[]{".webp",".png",".jpg",".jpeg"}){File f=new File(assets,base+ext);if(f.isFile()&&f.length()>0&&f.length()<=MAX_ENTRY)return f;}return null;}
    private static Pack readPack(File d){try{JSONObject m=new JSONObject(read(new File(d,"manifest.json")));if(m.optInt("themeFormatVersion",0)!=FORMAT)return null;String id=m.optString("id","").trim().toLowerCase(Locale.ROOT);if(!id.matches("[a-z0-9][a-z0-9._-]{0,63}"))return null;return new Pack(id,m.optString("name",id),m.optString("author","未知作者"),m.optString("version","1.0.0"),m.optString("description",""));}catch(Exception e){return null;}}
    private static void validateJsonFiles(File d) throws Exception {for(String name:new String[]{"manifest.json","palette.json","layout.json","components.json"}){File f=new File(d,name);if(f.isFile())new JSONObject(read(f));}validatePalette(new File(d,"palette.json"));validateLayout(new File(d,"layout.json"));validateComponents(new File(d,"components.json"));}
    private static void validatePalette(File f) throws Exception{if(!f.isFile())return;JSONObject root=new JSONObject(read(f));for(String mode:new String[]{"light","dark"}){JSONObject p=root.optJSONObject(mode);if(p==null)continue;Iterator<String> keys=p.keys();while(keys.hasNext()){String key=keys.next();if(!p.optString(key,"").matches("#[0-9A-Fa-f]{6}"))throw new IllegalArgumentException("装扮颜色无效："+mode+"."+key);}}}
    private static void validateLayout(File f) throws Exception{if(!f.isFile())return;JSONObject o=new JSONObject(read(f));if(o.has("cardRadiusDp")&&(o.optInt("cardRadiusDp",-1)<8||o.optInt("cardRadiusDp",-1)>28))throw new IllegalArgumentException("cardRadiusDp 无效");if(o.has("coverRadiusDp")&&(o.optInt("coverRadiusDp",-1)<4||o.optInt("coverRadiusDp",-1)>24))throw new IllegalArgumentException("coverRadiusDp 无效");if(o.has("density")&&!Arrays.asList("compact","standard","comfortable").contains(o.optString("density")))throw new IllegalArgumentException("density 无效");}
    private static void validateComponents(File f) throws Exception{if(!f.isFile())return;JSONObject o=new JSONObject(read(f));JSONObject t=o.optJSONObject("typography"),n=o.optJSONObject("navigation"),p=o.optJSONObject("progress"),b=o.optJSONObject("background"),r=o.optJSONObject("reader");check(t,"title",TYPOGRAPHY);check(t,"navigation",TYPOGRAPHY);check(n,"selectedEffect",new HashSet<>(Arrays.asList("none","pill","glow")));check(n,"iconScale",new HashSet<>(Arrays.asList("small","standard","large")));check(p,"style",PROGRESS_STYLE);check(p,"motion",PROGRESS_MOTION);check(p,"effect",new HashSet<>(Arrays.asList("none","sparkle")));if(b!=null){for(String key:new String[]{"patternOpacityLight","patternOpacityDark"})if(b.has(key)){double v=b.optDouble(key,-1);if(v<0||v>.18)throw new IllegalArgumentException(key+" 无效");}}if(r!=null&&r.has("chrome")&&!Arrays.asList("default","themed").contains(r.optString("chrome")))throw new IllegalArgumentException("reader.chrome 无效");}
    private static void check(JSONObject o,String key,Set<String> allowed){if(o!=null&&o.has(key)&&!allowed.contains(o.optString(key)))throw new IllegalArgumentException(key+" 无效");}
    private static int color(JSONObject p,String key,int fallback){String value=p.optString(key,"").trim();try{return value.matches("#[0-9A-Fa-f]{6}")?Color.parseColor(value):fallback;}catch(Exception e){return fallback;}}
    private static String safePath(String raw){String p=raw.replace('\\','/');if(p.startsWith("/")||p.contains("../")||p.equals("..")||p.contains("\u0000"))throw new IllegalArgumentException("非法装扮路径");return p;}
    private static boolean allowed(String p){if(p.equals("manifest.json")||p.equals("palette.json")||p.equals("layout.json")||p.equals("components.json"))return true;if(!p.startsWith("assets/"))return false;String lower=p.toLowerCase(Locale.ROOT);return lower.endsWith(".png")||lower.endsWith(".jpg")||lower.endsWith(".jpeg")||lower.endsWith(".webp");}
    private static void write(File f,String text) throws Exception {try(OutputStream out=new FileOutputStream(f)){out.write(text.getBytes(StandardCharsets.UTF_8));}}
    private static String read(File f) throws Exception {try(InputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))>0)out.write(b,0,n);return out.toString("UTF-8");}}
    private static void delete(File f){if(f==null||!f.exists())return;if(f.isDirectory()){File[] xs=f.listFiles();if(xs!=null)for(File x:xs)delete(x);}f.delete();}
}