package com.picalibrary.android;

import android.content.Context;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.*;
import org.json.*;

/** Persistent comic-centric mobile catalog. Source refreshes mutate availability, not comic identity. */
final class UnifiedCatalogStore {
    static final class Entry {
        final String id;
        String providerId="",providerRemoteId="",completionStatus="UNKNOWN";
        String title="未命名漫画",author="未知作者",canonicalAuthor="",authorId="",updatedAt="";
        String description="",chineseTeam="",uploader="";
        String desktopCoverPath="",remoteCoverPath="",remoteManifestPath="",picaCoverUrl="",ehCoverUrl="";
        final List<String> alternateTitles=new ArrayList<>(),tags=new ArrayList<>(),categories=new ArrayList<>(),shelfIds=new ArrayList<>();
        boolean finished,favorite,picaFavorite,localFavorite,ehFavorite,inShelf,phoneDownloaded,desktopAvailable,desktopDownloaded,remoteAvailable,picaAvailable,ehAvailable;
        int knownPictures,desktopDownloadedPictures,remotePageCount,remoteEpisodeCount;
        long totalLikes,totalViews;
        double rating=Double.NaN;
        Entry(String id){this.id=id==null?"":id;if(this.id.startsWith("eh:"))providerId="eh";}
        Entry(String id,String title,String author){this(id);this.title=safe(title,"未命名漫画");this.author=safe(author,"未知作者");}
        String displayAuthor(){return canonicalAuthor==null||canonicalAuthor.isEmpty()?author:canonicalAuthor;}
        String bestCoverUrl(){return ehAvailable&&!ehCoverUrl.isEmpty()?ehCoverUrl:picaCoverUrl;}
    }
    static final class Snapshot {
        String generatedAt="",desktopUpdatedAt="",remoteUpdatedAt="",remoteGeneration="";
        final LinkedHashMap<String,Entry> byId=new LinkedHashMap<>();
        List<Entry> entries(){return new ArrayList<>(byId.values());}
    }
    private UnifiedCatalogStore(){}
    private static File file(Context context){return MobileStoragePaths.dataFile(context,"unified-catalog-v1.json");}

    static Snapshot load(Context context){File source=file(context);if(!source.isFile())return new Snapshot();try(InputStream in=new FileInputStream(source);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[16384];int n;while((n=in.read(b))>0)out.write(b,0,n);JSONObject root=new JSONObject(out.toString("UTF-8"));Snapshot s=new Snapshot();s.generatedAt=root.optString("generatedAt","");s.desktopUpdatedAt=root.optString("desktopUpdatedAt","");s.remoteUpdatedAt=root.optString("remoteUpdatedAt","");s.remoteGeneration=root.optString("remoteGeneration","");JSONArray arr=root.optJSONArray("entries");if(arr!=null)for(int i=0;i<arr.length();i++){Entry e=parseEntry(arr.optJSONObject(i));if(e!=null)s.byId.put(e.id,e);}return s;}catch(Exception e){return new Snapshot();}}
    static synchronized void save(Context context,Snapshot s){try{s.generatedAt=Instant.now().toString();JSONObject root=new JSONObject();root.put("schemaVersion",4);root.put("generatedAt",s.generatedAt);root.put("desktopUpdatedAt",s.desktopUpdatedAt);root.put("remoteUpdatedAt",s.remoteUpdatedAt);root.put("remoteGeneration",s.remoteGeneration);JSONArray arr=new JSONArray();for(Entry e:s.byId.values())arr.put(json(e));root.put("entries",arr);File target=file(context);target.getParentFile().mkdirs();File tmp=new File(target.getParentFile(),target.getName()+".tmp");try(OutputStream out=new FileOutputStream(tmp)){out.write(root.toString().getBytes(StandardCharsets.UTF_8));}if(target.exists()&&!target.delete())throw new IOException("unified catalog replace failed");if(!tmp.renameTo(target))throw new IOException("unified catalog rename failed");}catch(Exception e){throw new IllegalStateException("无法保存统一书库目录",e);}}

    static Snapshot refreshDesktop(Context context) throws Exception {Snapshot s=load(context);LinkedHashMap<String,JSONObject> rows=new LinkedHashMap<>();int offset=0,total=Integer.MAX_VALUE;final int pageSize=500;while(offset<total&&offset<20000){JSONObject root=new JSONObject(BridgeClient.get(context,"/mobile/v1/library?scope=library&limit="+pageSize+"&offset="+offset+"&sort=latest"));JSONArray arr=root.optJSONArray("items");int count=arr==null?0:arr.length();total=Math.max(0,root.optInt("total",offset+count));if(arr!=null)for(int i=0;i<arr.length();i++){JSONObject o=arr.optJSONObject(i);if(o!=null&&!o.optString("comicId","").isEmpty())rows.put(o.optString("comicId"),o);}if(count==0||count<pageSize)break;offset+=count;}for(Entry e:s.byId.values()){e.desktopAvailable=false;e.desktopDownloaded=false;e.desktopDownloadedPictures=0;}for(JSONObject row:rows.values())mergeDesktop(s,row);s.desktopUpdatedAt=Instant.now().toString();applyLocalReferences(context,s);save(context,s);return s;}
    static Snapshot refreshRemote(Context context) throws Exception {Snapshot s=load(context);RemoteLibraryClient client=new RemoteLibraryClient(context);JSONObject pointer=client.json("v1/control/current.json");String generation=pointer.optString("generation",""),catalogPath=pointer.optString("catalogPath","");if(catalogPath.isEmpty())throw new IllegalStateException("云端书库尚未发布");if(!generation.isEmpty()&&generation.equals(s.remoteGeneration)){s.remoteUpdatedAt=Instant.now().toString();applyLocalReferences(context,s);save(context,s);return s;}JSONObject root=client.json(catalogPath);JSONArray arr=root.optJSONArray("comics");for(Entry e:s.byId.values()){e.remoteAvailable=false;e.remotePageCount=0;e.remoteEpisodeCount=0;e.remoteCoverPath="";e.remoteManifestPath="";}if(arr!=null)for(int i=0;i<arr.length();i++){JSONObject o=arr.optJSONObject(i);if(o!=null)mergeRemote(s,o);}s.remoteGeneration=generation;s.remoteUpdatedAt=Instant.now().toString();applyLocalReferences(context,s);save(context,s);return s;}
    static Snapshot reconcileLocalReferences(Context context){Snapshot s=load(context);applyLocalReferences(context,s);save(context,s);return s;}

    private static void applyLocalReferences(Context context,Snapshot s){
        ShelfStore.Snapshot shelves=ShelfStore.load(context);if(!shelves.updatedAt.isEmpty()){for(Entry e:s.byId.values()){e.inShelf=false;e.shelfIds.clear();}for(ShelfStore.Shelf shelf:shelves.shelves)if(shelf.active())for(ShelfStore.Item item:shelf.items)if(item.active()){Entry e=entry(s,item.comicId);basic(e,item.title,item.author);e.inShelf=true;if(!e.shelfIds.contains(shelf.id))e.shelfIds.add(shelf.id);e.knownPictures=Math.max(e.knownPictures,item.knownPictures);e.desktopDownloadedPictures=Math.max(e.desktopDownloadedPictures,item.downloadedPictures);}}
        EhFavoriteStore.Snapshot ehFavorites=EhFavoriteStore.migrateLegacyEhLocals(context);FavoriteCacheStore.Snapshot favorites=FavoriteCacheStore.load(context);if(!favorites.updatedAt.isEmpty()||!ehFavorites.updatedAt.isEmpty()){for(Entry e:s.byId.values()){e.picaFavorite=false;e.localFavorite=false;e.ehFavorite=false;}for(BridgeClient.ComicItem item:favorites.items){Entry e=entry(s,item.id);if(EhClient.isEhId(item.id))e.localFavorite=true;else e.picaFavorite=true;basic(e,item.title,item.author);if(item.coverPath!=null&&!item.coverPath.isEmpty())e.desktopCoverPath=item.coverPath;e.desktopDownloadedPictures=Math.max(e.desktopDownloadedPictures,item.downloadedPictures);}for(String id:ehFavorites.localIds)entry(s,id).localFavorite=true;for(String id:ehFavorites.remoteIds)entry(s,id).ehFavorite=true;for(Entry e:s.byId.values())e.favorite=EhFavoriteStore.aggregate(e.picaFavorite,e.localFavorite,e.ehFavorite);}
        for(Entry e:s.byId.values())e.phoneDownloaded=false;PhoneDownloadStore.Snapshot downloads=PhoneDownloadStore.load(context);for(PhoneDownloadStore.Comic comic:downloads.comics.values()){Entry e=entry(s,comic.id);basic(e,comic.title,comic.author);e.phoneDownloaded=comic.pages()>0;e.knownPictures=Math.max(e.knownPictures,comic.pages());}
    }

    private static void mergeDesktop(Snapshot s,JSONObject o){String id=o.optString("comicId","");if(id.isEmpty())return;Entry e=entry(s,id);basic(e,o.optString("title",e.title),o.optString("author",e.author));e.providerId=o.optString("providerId",e.providerId);e.providerRemoteId=o.optString("providerRemoteId",e.providerRemoteId);e.completionStatus=o.optString("completionStatus",e.completionStatus);e.description=o.optString("description",e.description);e.chineseTeam=o.optString("chineseTeam",e.chineseTeam);e.canonicalAuthor=o.optString("canonicalAuthor",e.canonicalAuthor);e.authorId=o.optString("authorId",e.authorId);copyIfPresent(o,"alternateTitles",e.alternateTitles);copyIfPresent(o,"tags",e.tags);copyIfPresent(o,"categories",e.categories);if(o.has("finished"))e.finished=o.optBoolean("finished",e.finished);if(o.has("isFavorite"))e.favorite=o.optBoolean("isFavorite",e.favorite);if(o.has("rating"))e.rating=o.optDouble("rating",e.rating);if(o.has("totalLikes"))e.totalLikes=o.optLong("totalLikes",e.totalLikes);if(o.has("totalViews"))e.totalViews=o.optLong("totalViews",e.totalViews);e.updatedAt=newer(e.updatedAt,o.optString("updatedAt",o.optString("lastSeenAt","")));e.knownPictures=Math.max(e.knownPictures,o.optInt("knownPictures",0));e.desktopDownloadedPictures=Math.max(0,o.optInt("downloadedPictures",0));e.desktopAvailable=true;e.desktopDownloaded=e.desktopDownloadedPictures>0;e.desktopCoverPath=o.optString("coverPath","/mobile/v1/covers/"+id);}
    private static void mergeRemote(Snapshot s,JSONObject o){String id=o.optString("comicId","");if(id.isEmpty())return;Entry e=entry(s,id);basic(e,o.optString("title",e.title),o.optString("author",e.author));e.providerId=o.optString("providerId",e.providerId);e.providerRemoteId=o.optString("providerRemoteId",e.providerRemoteId);e.completionStatus=o.optString("completionStatus",e.completionStatus);e.description=o.optString("description",e.description);e.canonicalAuthor=o.optString("canonicalAuthor",e.canonicalAuthor);e.authorId=o.optString("authorId",e.authorId);copyIfPresent(o,"alternateTitles",e.alternateTitles);copyIfPresent(o,"tags",e.tags);copyIfPresent(o,"categories",e.categories);if(o.has("finished"))e.finished=o.optBoolean("finished",e.finished);if(o.has("isFavorite"))e.favorite=o.optBoolean("isFavorite",e.favorite);if(o.has("rating"))e.rating=o.optDouble("rating",e.rating);e.updatedAt=newer(e.updatedAt,o.optString("updatedAt",""));e.knownPictures=Math.max(e.knownPictures,o.optInt("knownPictures",o.optInt("pageCount",0)));e.remotePageCount=Math.max(0,o.optInt("pageCount",0));e.remoteEpisodeCount=Math.max(0,o.optInt("episodeCount",0));e.remoteAvailable=true;e.remoteCoverPath=o.optString("coverPath","");e.remoteManifestPath=o.optString("manifestPath","");}
    private static Entry entry(Snapshot s,String id){Entry e=s.byId.get(id);if(e==null){e=new Entry(id);s.byId.put(id,e);}return e;}
    private static void basic(Entry e,String title,String author){if(title!=null&&!title.trim().isEmpty())e.title=title;if(author!=null&&!author.trim().isEmpty())e.author=author;}
    private static void copyIfPresent(JSONObject o,String key,List<String> target){if(!o.has(key))return;JSONArray arr=o.optJSONArray(key);if(arr==null)return;target.clear();for(int i=0;i<arr.length();i++){String value=arr.optString(i,"").trim();if(!value.isEmpty()&&!target.contains(value))target.add(value);}}
    private static String newer(String a,String b){String left=a==null?"":a,right=b==null?"":b;return right.compareTo(left)>0?right:left;}
    private static String safe(String value,String fallback){return value==null||value.trim().isEmpty()?fallback:value;}
    private static void readArray(JSONArray arr,List<String> out){if(arr==null)return;for(int i=0;i<arr.length();i++){String value=arr.optString(i,"").trim();if(!value.isEmpty()&&!out.contains(value))out.add(value);}}
    private static Entry parseEntry(JSONObject o){if(o==null)return null;String id=o.optString("id","");if(id.isEmpty())return null;Entry e=new Entry(id,o.optString("title","未命名漫画"),o.optString("author","未知作者"));e.providerId=o.optString("providerId",e.providerId);e.providerRemoteId=o.optString("providerRemoteId","");e.completionStatus=o.optString("completionStatus",o.has("finished")?(o.optBoolean("finished")?"FINISHED":"ONGOING"):"UNKNOWN");e.description=o.optString("description","");e.chineseTeam=o.optString("chineseTeam","");e.uploader=o.optString("uploader","");e.canonicalAuthor=o.optString("canonicalAuthor","");e.authorId=o.optString("authorId","");e.updatedAt=o.optString("updatedAt","");e.desktopCoverPath=o.optString("desktopCoverPath","");e.remoteCoverPath=o.optString("remoteCoverPath","");e.remoteManifestPath=o.optString("remoteManifestPath","");e.picaCoverUrl=o.optString("picaCoverUrl","");e.ehCoverUrl=o.optString("ehCoverUrl","");readArray(o.optJSONArray("alternateTitles"),e.alternateTitles);readArray(o.optJSONArray("tags"),e.tags);readArray(o.optJSONArray("categories"),e.categories);readArray(o.optJSONArray("shelfIds"),e.shelfIds);e.finished=o.optBoolean("finished",false);e.favorite=o.optBoolean("favorite",false);e.picaFavorite=o.optBoolean("picaFavorite",false);e.localFavorite=o.optBoolean("localFavorite",false);e.ehFavorite=o.optBoolean("ehFavorite",false);e.inShelf=o.optBoolean("inShelf",false);e.phoneDownloaded=o.optBoolean("phoneDownloaded",false);e.desktopAvailable=o.optBoolean("desktopAvailable",false);e.desktopDownloaded=o.optBoolean("desktopDownloaded",false);e.remoteAvailable=o.optBoolean("remoteAvailable",false);e.picaAvailable=o.optBoolean("picaAvailable",false);e.ehAvailable=o.optBoolean("ehAvailable",false);e.knownPictures=o.optInt("knownPictures",0);e.desktopDownloadedPictures=o.optInt("desktopDownloadedPictures",0);e.remotePageCount=o.optInt("remotePageCount",0);e.remoteEpisodeCount=o.optInt("remoteEpisodeCount",0);e.totalLikes=o.optLong("totalLikes",0);e.totalViews=o.optLong("totalViews",0);if(o.has("rating")&&!o.isNull("rating"))e.rating=o.optDouble("rating",Double.NaN);return e;}
    private static JSONObject json(Entry e) throws Exception {JSONObject o=new JSONObject();o.put("id",e.id);o.put("providerId",e.providerId);o.put("providerRemoteId",e.providerRemoteId);o.put("completionStatus",e.completionStatus);o.put("title",e.title);o.put("alternateTitles",new JSONArray(e.alternateTitles));o.put("author",e.author);o.put("description",e.description);o.put("chineseTeam",e.chineseTeam);o.put("uploader",e.uploader);o.put("canonicalAuthor",e.canonicalAuthor);o.put("authorId",e.authorId);o.put("updatedAt",e.updatedAt);o.put("desktopCoverPath",e.desktopCoverPath);o.put("remoteCoverPath",e.remoteCoverPath);o.put("remoteManifestPath",e.remoteManifestPath);o.put("picaCoverUrl",e.picaCoverUrl);o.put("ehCoverUrl",e.ehCoverUrl);o.put("tags",new JSONArray(e.tags));o.put("categories",new JSONArray(e.categories));o.put("shelfIds",new JSONArray(e.shelfIds));o.put("finished",e.finished);o.put("favorite",e.favorite);o.put("picaFavorite",e.picaFavorite);o.put("localFavorite",e.localFavorite);o.put("ehFavorite",e.ehFavorite);o.put("inShelf",e.inShelf);o.put("phoneDownloaded",e.phoneDownloaded);o.put("desktopAvailable",e.desktopAvailable);o.put("desktopDownloaded",e.desktopDownloaded);o.put("remoteAvailable",e.remoteAvailable);o.put("picaAvailable",e.picaAvailable);o.put("ehAvailable",e.ehAvailable);o.put("knownPictures",e.knownPictures);o.put("desktopDownloadedPictures",e.desktopDownloadedPictures);o.put("remotePageCount",e.remotePageCount);o.put("remoteEpisodeCount",e.remoteEpisodeCount);o.put("totalLikes",e.totalLikes);o.put("totalViews",e.totalViews);if(!Double.isNaN(e.rating))o.put("rating",e.rating);return o;}
}
