package com.picalibrary.android;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;

/** Comic-first detail screen with explicit reading/download actions and portable shelves. */
public final class UnifiedComicDetailActivity extends Activity {
    private static final class ResolvedChapter {
        final String id,title,sourceKind,label;final int order,pages,priority;boolean picaBacked,ehBacked;
        ResolvedChapter(BridgeClient.ChapterItem item,String sourceKind,String label,int priority,boolean picaBacked,boolean ehBacked){this.id=item.id;this.title=item.title;this.order=item.order;this.pages=item.downloadedPictures;this.sourceKind=sourceKind;this.label=label;this.priority=priority;this.picaBacked=picaBacked;this.ehBacked=ehBacked;}
    }
    private static final class ProbeResult {
        final String sourceKind,label;final int priority;final List<BridgeClient.ChapterItem> chapters;final boolean pica,eh;
        ProbeResult(String sourceKind,String label,int priority,List<BridgeClient.ChapterItem> chapters,boolean pica,boolean eh){this.sourceKind=sourceKind;this.label=label;this.priority=priority;this.chapters=chapters;this.pica=pica;this.eh=eh;}
    }
    private final ExecutorService worker=Executors.newFixedThreadPool(5);private final LinkedHashMap<String,ResolvedChapter> resolved=new LinkedHashMap<>();private final LinkedHashSet<String> availableSources=new LinkedHashSet<>();private final AtomicInteger remaining=new AtomicInteger();
    private LinearLayout chapterArea,actionArea;private TextView sourceState;private ProgressBar loading;private ImageView coverView;private UnifiedCatalogStore.Entry entry;private volatile Boolean picaFavoriteState;private boolean destroyed,picaReady,ehReady;

    @Override public void onCreate(Bundle saved){super.onCreate(saved);Ui.applyWindow(this);String comicId=getIntent().getStringExtra("comicId");entry=UnifiedCatalogStore.load(this).byId.get(comicId);if(entry==null)entry=new UnifiedCatalogStore.Entry(comicId==null?"":comicId,getIntent().getStringExtra("title"),getIntent().getStringExtra("author"));render();resolveSources();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.addView(small("‹ 返回",v->finish()));bar.addView(Ui.text(this,"漫画详情",20,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));root.addView(bar);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(Ui.BG);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(Ui.dp(this,16),Ui.dp(this,4),Ui.dp(this,16),Ui.dp(this,28));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout hero=new LinearLayout(this);coverView=new ImageView(this);coverView.setScaleType(ImageView.ScaleType.CENTER_CROP);coverView.setBackgroundColor(Ui.PLACEHOLDER);hero.addView(coverView,new LinearLayout.LayoutParams(Ui.dp(this,118),Ui.dp(this,168)));CoverRepository.load(this,coverView,entry,Ui.PLACEHOLDER);LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);copy.setPadding(Ui.dp(this,15),0,0,0);TextView title=Ui.text(this,entry.title,20,Ui.TEXT,true);title.setMaxLines(4);copy.addView(title);copy.addView(Ui.text(this,entry.displayAuthor(),13,Ui.MUTED,false));if("eh".equals(entry.providerId)){String meta="E-H"+(Double.isNaN(entry.rating)?"":" · ★ "+String.format(Locale.ROOT,"%.2f",entry.rating))+(entry.completionStatus.equals("UNKNOWN")?" · 完结状态未知":"");copy.addView(Ui.text(this,meta,11.5f,Ui.MUTED,false));}String tags=tagLine();if(!tags.isEmpty()){TextView t=Ui.text(this,tags,11.5f,Ui.PRIMARY,false);t.setPadding(0,Ui.dp(this,8),0,0);copy.addView(t);}hero.addView(copy,new LinearLayout.LayoutParams(0,-2,1));content.addView(hero);actionArea=new LinearLayout(this);actionArea.setPadding(0,Ui.dp(this,10),0,0);content.addView(actionArea);sourceState=Ui.text(this,"正在检查可读来源…",12,Ui.MUTED,false);sourceState.setPadding(0,Ui.dp(this,8),0,0);content.addView(sourceState);if(RemoteConfigStore.targets(this).size()>1){Button switchRemote=small("切换当前网盘",v->chooseRemoteTarget());switchRemote.setAllCaps(false);content.addView(switchRemote);}loading=new ProgressBar(this);content.addView(loading);chapterArea=new LinearLayout(this);chapterArea.setOrientation(LinearLayout.VERTICAL);content.addView(chapterArea);setContentView(root);root.requestApplyInsets();renderActions();}
    private Button button(String text,View.OnClickListener action){return Ui.button(this,text,action,false);}
    private Button small(String text,View.OnClickListener action){return Ui.button(this,text,action,true);}
    private String tagLine(){if(entry.tags.isEmpty())return "";StringBuilder out=new StringBuilder();for(int i=0;i<entry.tags.size()&&i<5;i++){if(i>0)out.append(" · ");out.append(entry.tags.get(i));}return out.toString();}

    private void resolveSources(){List<Callable<ProbeResult>> probes=new ArrayList<>();if(PhoneDownloadStore.has(this,entry.id))probes.add(()->probe(new PhoneDownloadReaderSource(this),"phone","手机",0,false,false));if(entry.desktopDownloaded&&BridgeStore.paired(this))probes.add(()->{BridgeClient.device(this);return probe(new DesktopReaderSource(this),"desktop","电脑",1,false,false);});RemoteConfigStore.Config remote=RemoteConfigStore.load(this);if(entry.remoteAvailable&&remote.configured())probes.add(()->probe(new RemoteReaderSource(this),"remote","WebDAV · "+remote.label,2,false,false));if(entry.ehAvailable||EhClient.isEhId(entry.id))probes.add(this::probeEh);if(!EhClient.isEhId(entry.id)&&PicaAccountStore.load(this).configured())probes.add(this::probePica);if(probes.isEmpty()){finishProbing();return;}remaining.set(probes.size());for(Callable<ProbeResult> call:probes)worker.submit(()->{try{ProbeResult result=call.call();if(result!=null&&!result.chapters.isEmpty())runOnUiThread(()->accept(result));}catch(Exception ignored){}finally{if(remaining.decrementAndGet()==0)runOnUiThread(this::finishProbing);}});}
    private ProbeResult probe(ReaderSource source,String kind,String label,int priority,boolean pica,boolean eh) throws Exception {List<BridgeClient.ChapterItem> chapters=source.chapters(entry.id);List<BridgeClient.ChapterItem> readable=new ArrayList<>();for(BridgeClient.ChapterItem item:chapters)if(item.downloadedPictures>0)readable.add(item);readable.sort(Comparator.comparingInt(c->c.order));return new ProbeResult(kind,label,priority,readable,pica,eh);}
    private ProbeResult probePica() throws Exception {PicaClient client=new PicaClient(this);PicaClient.Comic online=client.comic(entry.id);if(online.id.isEmpty())return null;picaFavoriteState=online.favorite;entry=UnifiedPicaCatalogSync.merge(this,online);List<BridgeClient.ChapterItem> chapters=new ArrayList<>();for(PicaClient.Episode ep:client.episodes(entry.id))chapters.add(new BridgeClient.ChapterItem(ep.id,ep.title,ep.order,1));chapters.sort(Comparator.comparingInt(c->c.order));runOnUiThread(()->{if(!destroyed){CoverRepository.load(this,coverView,entry,Ui.PLACEHOLDER);renderActions();}});return new ProbeResult("pica","Pica 在线",3,chapters,true,false);}
    private ProbeResult probeEh() throws Exception {EhClient client=new EhClient(this);EhClient.Comic online=client.comic(entry.id);entry=UnifiedEhCatalogSync.merge(this,online);List<BridgeClient.ChapterItem> chapters=new ArrayList<>();for(EhClient.Episode ep:client.episodes(entry.id))chapters.add(new BridgeClient.ChapterItem(ep.id,ep.title,ep.order,Math.max(1,online.pagesCount)));chapters.sort(Comparator.comparingInt(c->c.order));runOnUiThread(()->{if(!destroyed){CoverRepository.load(this,coverView,entry,Ui.PLACEHOLDER);renderActions();}});return new ProbeResult("eh","E-H 在线",3,chapters,false,true);}
    private void accept(ProbeResult result){if(destroyed)return;availableSources.add(result.label);if(result.pica)picaReady=true;if(result.eh)ehReady=true;for(BridgeClient.ChapterItem item:result.chapters){ResolvedChapter prior=resolved.get(item.id);if(prior==null||result.priority<prior.priority){ResolvedChapter next=new ResolvedChapter(item,result.sourceKind,result.label,result.priority,result.pica,result.eh);if(prior!=null&&prior.picaBacked)next.picaBacked=true;if(prior!=null&&prior.ehBacked)next.ehBacked=true;resolved.put(item.id,next);}else{if(result.pica)prior.picaBacked=true;if(result.eh)prior.ehBacked=true;}}renderActions();renderChapters(false);}
    private void finishProbing(){if(destroyed)return;loading.setVisibility(View.GONE);if(resolved.isEmpty()){sourceState.setText("当前没有可读章节");return;}renderChapters(true);}

    private void chooseRemoteTarget(){List<RemoteConfigStore.Config> targets=RemoteConfigStore.targets(this);if(targets.size()<2){startActivity(new Intent(this,RemoteStorageActivity.class));return;}String active=RemoteConfigStore.activeTargetId(this);String[] labels=new String[targets.size()];int checked=0;for(int i=0;i<targets.size();i++){RemoteConfigStore.Config c=targets.get(i);labels[i]=c.label+" · "+RemoteConfigStore.preset(c.vendor).label;if(c.id.equals(active))checked=i;}new AlertDialog.Builder(this).setTitle("选择当前网盘").setSingleChoiceItems(labels,checked,(dialog,which)->{dialog.dismiss();RemoteConfigStore.Config target=targets.get(which);if(target.id.equals(RemoteConfigStore.activeTargetId(this)))return;sourceState.setText("正在切换到“"+target.label+"”…");loading.setVisibility(View.VISIBLE);new Thread(()->{try{RemoteConfigStore.setActive(this,target.id);UnifiedRemoteCatalogSync.refresh(this);runOnUiThread(()->{if(!destroyed)recreate();});}catch(Exception e){runOnUiThread(()->{if(destroyed)return;loading.setVisibility(View.GONE);sourceState.setText("切换网盘失败");Toast.makeText(this,e.getMessage()==null?"无法读取该网盘":e.getMessage(),Toast.LENGTH_LONG).show();});}}).start();}).setNegativeButton("取消",null).show();}

    private void renderActions(){if(actionArea==null||destroyed)return;actionArea.removeAllViews();if(EhClient.isEhId(entry.id)){boolean local=entry.localFavorite,remote=entry.ehFavorite;Button localFav=small(local?"★ 本地":"☆ 本地",v->{EhFavoriteStore.setLocalFavorite(this,entry.id,!local);UnifiedCatalogStore.Entry refreshed=UnifiedCatalogStore.load(this).byId.get(entry.id);if(refreshed!=null)entry=refreshed;renderActions();Toast.makeText(this,!local?"已加入本地收藏":"已取消本地收藏",Toast.LENGTH_SHORT).show();});localFav.setTextColor(local?Ui.FAVORITE:Ui.MUTED);actionArea.addView(localFav,new LinearLayout.LayoutParams(0,-2,1));Ui.gap(actionArea,this,6);if(EhAccountStore.load(this).configured()){Button cloud=small(remote?"★ E-H 云":"☆ E-H 云",v->setEhRemoteFavorite(!remote));cloud.setTextColor(remote?Ui.FAVORITE:Ui.MUTED);actionArea.addView(cloud,new LinearLayout.LayoutParams(0,-2,1));}else actionArea.addView(small("E-H 账号",v->startActivity(new Intent(this,EhAccountActivity.class))),new LinearLayout.LayoutParams(0,-2,1));}else if(picaReady&&picaFavoriteState!=null){boolean favorite=picaFavoriteState;Button fav=small(favorite?"★ 已收藏":"☆ 收藏",v->setPicaFavorite(!favorite));fav.setTextColor(favorite?Ui.FAVORITE:Ui.MUTED);actionArea.addView(fav,new LinearLayout.LayoutParams(0,-2,1));}else{Button fav=small(entry.favorite?"★ 已收藏":"☆ 收藏",v->{if(PicaAccountStore.load(this).configured())Toast.makeText(this,"正在读取 Pica 收藏状态",Toast.LENGTH_SHORT).show();else startActivity(new Intent(this,PicaAccountActivity.class));});fav.setTextColor(entry.favorite?Ui.FAVORITE:Ui.MUTED);actionArea.addView(fav,new LinearLayout.LayoutParams(0,-2,1));}Ui.gap(actionArea,this,6);actionArea.addView(small("书架",v->chooseShelves()),new LinearLayout.LayoutParams(0,-2,1));}
    private void setEhRemoteFavorite(boolean desired){actionArea.setEnabled(false);worker.submit(()->{try{new EhClient(this).setRemoteFavorite(entry.id,desired);EhFavoriteStore.setRemoteFavorite(this,entry.id,desired);UnifiedCatalogStore.Entry refreshed=UnifiedCatalogStore.load(this).byId.get(entry.id);if(refreshed!=null)entry=refreshed;runOnUiThread(()->{if(destroyed)return;actionArea.setEnabled(true);renderActions();Toast.makeText(this,desired?"已加入 E-H 云收藏":"已取消 E-H 云收藏",Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->{if(destroyed)return;actionArea.setEnabled(true);renderActions();Toast.makeText(this,"E-H 云收藏更新失败",Toast.LENGTH_LONG).show();});}});}
    private void setPicaFavorite(boolean desired){actionArea.setEnabled(false);worker.submit(()->{try{new PicaClient(this).setFavorite(entry.id,desired);FavoriteCacheStore.setLocalFavorite(this,entry.id,entry.title,entry.displayAuthor(),desired);UnifiedCatalogStore.Entry refreshed=UnifiedCatalogStore.load(this).byId.get(entry.id);if(refreshed!=null)entry=refreshed;picaFavoriteState=desired;runOnUiThread(()->{if(destroyed)return;actionArea.setEnabled(true);renderActions();Toast.makeText(this,desired?"已收藏":"已取消收藏",Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->{if(destroyed)return;actionArea.setEnabled(true);renderActions();Toast.makeText(this,"收藏更新失败",Toast.LENGTH_LONG).show();});}});}
    private void chooseShelves(){List<ShelfStore.Shelf> shelves=ShelfStore.load(this).activeShelves();if(shelves.isEmpty()){new AlertDialog.Builder(this).setTitle("还没有书架").setNegativeButton("取消",null).setPositiveButton("新建书架",(d,w)->createShelfThenChoose()).show();return;}String[] labels=new String[shelves.size()];boolean[] checked=new boolean[shelves.size()];Set<String> current=new HashSet<>();for(ShelfStore.Shelf s:ShelfStore.activeForComic(this,entry.id))current.add(s.id);for(int i=0;i<shelves.size();i++){labels[i]=shelves.get(i).name;checked[i]=current.contains(shelves.get(i).id);}new AlertDialog.Builder(this).setTitle("加入书架").setMultiChoiceItems(labels,checked,(d,which,value)->checked[which]=value).setNeutralButton("＋ 新建",(d,w)->createShelfThenChoose()).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{for(int i=0;i<shelves.size();i++)ShelfStore.setMembership(this,shelves.get(i).id,entry,checked[i]);syncShelvesAsync();Toast.makeText(this,"书架已更新",Toast.LENGTH_SHORT).show();}).show();}
    private void createShelfThenChoose(){EditText input=new EditText(this);input.setHint("书架名称");Ui.styleField(input,this);new AlertDialog.Builder(this).setTitle("新建书架").setView(input).setNegativeButton("取消",null).setPositiveButton("创建",(d,w)->{try{ShelfStore.Shelf shelf=ShelfStore.create(this,input.getText().toString());ShelfStore.setMembership(this,shelf.id,entry,true);syncShelvesAsync();Toast.makeText(this,"已加入“"+shelf.name+"”",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}).show();}
    private void syncShelvesAsync(){if(!BridgeStore.paired(this))return;worker.submit(()->{try{BridgeClient.device(this);ShelfStore.syncWithDesktop(this);}catch(Exception ignored){}});}

    private void renderChapters(boolean complete){if(destroyed)return;List<ResolvedChapter> chapters=new ArrayList<>(resolved.values());chapters.sort((a,b)->{int order=Integer.compare(a.order,b.order);return order!=0?order:a.title.compareToIgnoreCase(b.title);});sourceState.setText((complete?"可用：":"已发现：")+String.join(" · ",availableSources));chapterArea.removeAllViews();if(picaReady||ehReady){LinearLayout downloadRow=new LinearLayout(this);downloadRow.setGravity(Gravity.CENTER_VERTICAL);TextView heading=Ui.text(this,"章节",20,Ui.TEXT,true);downloadRow.addView(heading,new LinearLayout.LayoutParams(0,-2,1));downloadRow.addView(small("全部下载",v->{if(ehReady&&EhClient.isEhId(entry.id))EhDownloadJobs.enqueue(this,entry.id);else PicaDownloadJobs.enqueue(this,entry.id,"");Toast.makeText(this,"已加入后台下载",Toast.LENGTH_SHORT).show();}));chapterArea.addView(downloadRow);}else{TextView section=Ui.text(this,"章节",20,Ui.TEXT,true);section.setPadding(0,Ui.dp(this,12),0,Ui.dp(this,6));chapterArea.addView(section);}for(ResolvedChapter chapter:chapters){LinearLayout row=Ui.card(this);row.setPadding(Ui.dp(this,14),Ui.dp(this,10),Ui.dp(this,14),Ui.dp(this,10));row.addView(Ui.text(this,chapter.title,15.5f,Ui.TEXT,true));String meta=(chapter.sourceKind.equals("pica")||chapter.sourceKind.equals("eh"))?chapter.label:chapter.pages+" 页 · "+chapter.label;row.addView(Ui.text(this,meta,11.5f,Ui.MUTED,false));LinearLayout actions=new LinearLayout(this);actions.setPadding(0,Ui.dp(this,8),0,0);actions.addView(small("阅读",v->openReader(chapter.sourceKind,chapter.id)),new LinearLayout.LayoutParams(0,-2,1));Ui.gap(actions,this,8);if("phone".equals(chapter.sourceKind)){Button done=small("✓ 已下载",v->{});done.setEnabled(false);actions.addView(done,new LinearLayout.LayoutParams(0,-2,1));}else if(chapter.ehBacked){actions.addView(small("下载",v->{EhDownloadJobs.enqueue(this,entry.id);Toast.makeText(this,"E-H 画廊已加入后台下载",Toast.LENGTH_SHORT).show();}),new LinearLayout.LayoutParams(0,-2,1));}else if(chapter.picaBacked){actions.addView(small("下载",v->{PicaDownloadJobs.enqueue(this,entry.id,chapter.id);Toast.makeText(this,"本章已加入后台下载",Toast.LENGTH_SHORT).show();}),new LinearLayout.LayoutParams(0,-2,1));}row.addView(actions);chapterArea.addView(row);}}
    private void openReader(String sourceKind,String episodeId){Intent i=new Intent(this,ReaderActivity.class);i.putExtra("comicId",entry.id);i.putExtra("title",entry.title);i.putExtra("episodeId",episodeId);i.putExtra("source",sourceKind);startActivity(i);}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
}
