import fs from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('Android Library / Author / History V2 contracts', () => {
  it('separates replica location from online provider and keeps sorting outside active filters', () => {
    const filter = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/UnifiedLibraryFilter.java','utf8')
    const store = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/UnifiedFilterStore.java','utf8')
    const dialog = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/UnifiedLibraryFilterDialog.java','utf8')
    expect(filter).toContain('enum Location { PHONE, DESKTOP, WEBDAV, ONLINE }')
    expect(filter).toContain('enum Provider { PICA, EH, EXH }')
    expect(filter).not.toContain('enum Source {')
    expect(store).toContain('legacy.contains("PICA")')
    expect(store).toContain('Location.ONLINE')
    expect(store).toContain('Provider.PICA')
    expect(dialog).toContain('"更多筛选"')
    expect(dialog).not.toContain('section(root,activity,"排序")')
  })

  it('keeps library chrome compact and restores history outside bottom navigation', () => {
    const home = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/HomeActivity.java','utf8')
    const shell = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ShellPolicy.java','utf8')
    const manifest = fs.readFileSync('mobile/android-alpha2/app/src/main/AndroidManifest.xml','utf8')
    expect(home).toContain('compact("历史",v->startActivity(new Intent(this,HistoryActivity.class)))')
    expect(home).toContain('compact("书架",v->{showingShelves=true;show();})')
    expect(home).toContain('compact("显示",v->chooseCollectionMode())')
    expect(home).toContain('Ui.iconButton(this,R.drawable.ic_refresh_24,"刷新书库"')
    expect(home).not.toContain('compact("⋮",v->showLibraryMenu())')
    expect(home).toContain('UnifiedLibraryFilter.sortLabel(librarySpec.sort)+" ▾"')
    expect(home).toContain('private void chooseLibrarySort()')
    expect(shell).toContain('{"书库","推荐","在线","设置"}')
    expect(shell).not.toContain('历史')
    expect(manifest).toContain('.HistoryActivity')
  })

  it('uses an auditable creator concept and two-stage creator navigation', () => {
    const concepts = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/AuthorConceptStore.java','utf8')
    const detail = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/UnifiedComicDetailActivity.java','utf8')
    const directory = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/AuthorDirectoryActivity.java','utf8')
    const works = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/AuthorWorksActivity.java','utf8')
    expect(concepts).toContain('final class AuthorConceptStore')
    expect(concepts).toContain('"artist:"+name,"artist"')
    expect(concepts).toContain('"group:"+name,"group"')
    expect(detail).toContain('AuthorDirectoryActivity.class')
    expect(directory).toContain('AuthorWorksActivity.class')
    expect(directory).toContain('"本作作者"')
    expect(works).toContain('AuthorConceptStore.queryForPica(concept)')
    expect(works).toContain('AuthorConceptStore.queryForEh(concept)')
    expect(works).toContain('EhCapabilityStore.refresh(this,false)')
  })

  it('keeps Author Works catalog and creator rebuilds off the UI render path', () => {
    const works = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/AuthorWorksActivity.java','utf8')
    expect(works).toContain('private static final class LocalState')
    expect(works).toContain('private LocalState readLocalState()')
    expect(works).toContain('UnifiedCatalogStore.Snapshot nextCatalog =')
    expect(works).toContain('EhSemanticStore.Snapshot semantics = EhSemanticStore.load(this)')
    expect(works).toContain('AuthorConceptStore.build(nextCatalog, semantics)')
    expect(works).toContain('worker.submit(() -> {')
    expect(works).toContain('LocalState next = readLocalState();')
    expect(works).not.toContain('AuthorConceptStore.build(this)')

    const renderStart = works.indexOf('private void renderWorks()')
    const renderEnd = works.indexOf('private boolean bindingMatches(', renderStart)
    const renderBody = works.slice(renderStart, renderEnd)
    expect(renderBody).not.toContain('UnifiedCatalogStore.load(')
    expect(renderBody).not.toContain('EhSemanticStore.load(')
    expect(renderBody).not.toContain('AuthorConceptStore.build(')

    const onCreateStart = works.indexOf('@Override public void onCreate')
    const onCreateEnd = works.indexOf('private Button compact(', onCreateStart)
    const onCreateBody = works.slice(onCreateStart, onCreateEnd)
    expect(onCreateBody).toContain('renderShell();')
    expect(onCreateBody).toContain('loadLocalState(true);')
    expect(onCreateBody).not.toContain('UnifiedCatalogStore.load(')
    expect(onCreateBody).not.toContain('AuthorConceptStore.build(')
  })

  it('records session history separately from bookmarks and supports exact-date resume', () => {
    const progress = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ReaderProgress.java','utf8')
    const store = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ReadingHistoryStore.java','utf8')
    const history = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/HistoryActivity.java','utf8')
    expect(progress).toContain('ReadingHistoryStore.record(')
    expect(progress).toContain('historyChapterId')
    expect(progress).toContain('seedOneShotPosition')
    expect(store).toContain('enum Range { TODAY, DAYS_7, DAYS_30, ALL }')
    expect(store).toContain('legacySnapshot')
    expect(history).toContain('new DatePickerDialog(')
    expect(history).toContain('ReadingHistoryStore.Range.DAYS_30')
    expect(history).toContain('ReaderProgress.seedOneShotPosition(this,row.comicId,row.chapterId,row.lastPage)')
  })

  it('groups mobile history by comic, shows covers and preserves chapter metadata', () => {
    const reader = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ReaderActivity.java','utf8')
    const progress = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ReaderProgress.java','utf8')
    const store = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ReadingHistoryStore.java','utf8')
    const history = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/HistoryActivity.java','utf8')
    expect(reader).toContain('chapterAdvance.setText(LocalizedText.ui("下一章 · ")+target.title)')
    expect(reader).toContain('progress.chapterMetadata(data.episode.id,data.episode.title,data.episode.order)')
    expect(reader).toContain('if(atChapterEnd())setChrome(true)')
    expect(progress).toContain('void chapterMetadata(String chapterId,String chapterTitle,int chapterOrder)')
    expect(store).toContain('chapterOrder')
    expect(store).toContain('o.put("chapterOrder",v.chapterOrder)')
    expect(history).toContain('List<ComicHistory> groups=grouped(rows)')
    expect(history).toContain('CoverRepository.load(this,cover')
    expect(history).toContain('"已记录 "+chapters.size()+" 个章节')
    expect(history).toContain('setTitle(group.latest.title+LocalizedText.ui(" · 章节记录"))')
    expect(history).not.toContain('private void addSession(')
  })

  it('keeps E-H browse and filter compact actions in one row', () => {
    const browse = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java','utf8')
    expect(browse).toContain('Button browse=button("浏览"')
    expect(browse).toContain('Button filter=button(filterLabel()')
    expect(browse).toContain('browse.setSingleLine(true)')
    expect(browse).toContain('filter.setSingleLine(true)')
    expect(browse).not.toContain('LinearLayout filterRow=')
  })
})
