import fs from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('source-oriented product navigation', () => {
  it('keeps Desktop source/account choices collapsed until requested', () => {
    const html = fs.readFileSync('web/index.html', 'utf8')
    expect(html).toContain('<details class="source-picker">')
    expect(html).toContain('id="search-provider"')
    expect(html).toContain('<option value="exh">')
    expect(html).toContain('<details class="wide account-disclosure">')
    expect(html).toContain('<details class="account-advanced">')
    expect(html).not.toContain('<button data-online-source="pica"')
    expect(html).not.toContain('<button data-online-source="eh"')
    expect(html).not.toContain('<button data-online-source="exh"')
  })

  it('progressively discloses Desktop filters, account, batch and card actions', () => {
    const script = fs.readFileSync('web/eh-account.js', 'utf8')
    expect(script).toContain("summary.textContent = ehT('筛选 ▾','Filters ▾','絞り込み ▾')")
    expect(script).toContain("disclosure(ehT('官方账号 ▾','Official account ▾','公式アカウント ▾')")
    expect(script).toContain("disclosure(ehT('账号功能 ▾','Account actions ▾','アカウント操作 ▾')")
    expect(script).toContain("disclosure(ehT('批量操作 ▾','Batch actions ▾','一括操作 ▾')")
    expect(script).toContain("disclosure(ehT('更多 ▾','More ▾','その他 ▾'), [download, favorite], 'result-action-menu')")
    expect(script).toContain('observeResultCardActions()')
  })

  it('uses one Android source capability authority and classifies ExH as optional under E-H', () => {
    const caps = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/SourceCapabilities.java', 'utf8')
    const browse = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    expect(caps).toContain('enum Tier { AGGREGATE, CORE, OPTIONAL_CAPABILITY }')
    expect(caps).toContain('PICA=new Source("pica","Pica","",Tier.CORE')
    expect(caps).toContain('EH=new Source("eh","E-Hentai","",Tier.CORE')
    expect(caps).toContain('EXH=new Source("exh","ExHentai","eh",Tier.OPTIONAL_CAPABILITY')
    expect(caps).toContain('baseRecommendationSource')
    expect(browse).toContain('SourceCapabilities.byId(sourceMode)')
    expect(browse).toContain('if(source().supportsBrowse)')
    expect(browse).toContain('Button browse=button("浏览"')
    expect(browse).toContain('Button filter=button(filterLabel()')
    expect(browse).not.toContain('LinearLayout filterRow=')
    expect(browse).not.toContain('Pica 功能')
    expect(browse).not.toContain('全部来源 · E-H 公共浏览无需账号')
  })

  it('routes Android account management through a unified hub while keeping ExH monitored under E-H', () => {
    const browse = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    const hub = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/AccountSourcesActivity.java', 'utf8')
    const manifest = fs.readFileSync('mobile/android-alpha2/app/src/main/AndroidManifest.xml', 'utf8')
    expect(browse).toContain('AccountSourcesActivity.class')
    expect(hub).toContain('"Pica"')
    expect(hub).toContain('"E-Hentai / ExHentai"')
    expect(hub).toContain('SettingsRow.panel(this')
    expect(hub).toContain('"E-H 账号"')
    expect(hub).toContain('status(localEh,desktop.ehConfigured)')
    expect(hub).toContain('DesktopAccountStatusStore.load(this)')
    expect(hub).toContain('"已由 Desktop 连接"')
    expect(hub).toContain('"ExH 扩展"')
    expect(hub).toContain('EhCapabilityStore.load(this)')
    expect(hub).toContain('EhCapabilityStore.refreshAsync(this,false')
    expect(hub).not.toContain('"ExH 权限"')
    expect(hub).not.toContain('ExHAccountActivity')
    expect(manifest).toContain('.AccountSourcesActivity')
    expect(manifest).toContain('.EhWebLoginActivity')
    expect(manifest).toContain('.EhSessionActivity')
  })

  it('uses official in-app web login as the normal E-H connection path', () => {
    const eh = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/EhAccountActivity.java', 'utf8')
    const login = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/EhWebLoginActivity.java', 'utf8')
    expect(eh).toContain('"网页登录"')
    expect(eh).toContain('EhWebLoginActivity.class')
    expect(eh).toContain('"手动导入会话"')
    expect(login).toContain('CookieManager.getInstance()')
    expect(login).toContain('"ipb_member_id"')
    expect(login).toContain('"ipb_pass_hash"')
    expect(login).toContain('new EhClient(this).verifyAccount()')
    expect(login).toContain('EhAccountStore.save(this,next)')
    expect(login).not.toContain('EditText')
    expect(login).not.toContain('password')
  })

  it('keeps normal account pages quiet and moves technical session fields to a focused child page', () => {
    const pica = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaAccountActivity.java', 'utf8')
    const eh = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/EhAccountActivity.java', 'utf8')
    const session = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/EhSessionActivity.java', 'utf8')
    expect(pica).toContain('"账号操作 ▾"')
    expect(pica).toContain('"注册账号"')
    expect(pica).not.toContain('第一次使用 Pica')
    expect(pica).not.toContain('已有账号：填写')
    expect(eh).toContain('"账号管理 ▾"')
    expect(eh).toContain('"其他方式 ▾"')
    expect(eh).toContain('EhSessionActivity.class')
    expect(eh).toContain('"重新检查 ExH"')
    expect(eh).not.toContain('公共 E-H 搜索、阅读、下载无需账号')
    expect(eh).not.toContain('Android Keystore AES-GCM')
    expect(session).toContain('"手动导入会话"')
    expect(session).toContain('"更多 ▾"')
    expect(session).toContain('advanced.setVisibility(View.GONE)')
    expect(session).toContain('"验证并保存"')
    expect(session).toContain('"网页登录"')
  })

  it('keeps all four top-level tabs inside Home and opens Online/Settings details only on demand', () => {
    const home = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/HomeActivity.java', 'utf8')
    const online = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    const settings = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/SettingsActivity.java', 'utf8')
    const nav = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ShellNavigation.java', 'utf8')
    expect(home).toContain('ShellNavigation.build(this,current)')
    expect(home).toContain('private void onlineEntry()')
    expect(home).toContain('private void settingsEntry()')
    expect(home).toContain('SettingsRow.row(this,"全部来源"')
    expect(home).toContain('SettingsRow.row(this,"软件更新","检查并安装正式更新"')
    expect(online).not.toContain('ShellNavigation.build(this,2)')
    expect(settings).not.toContain('ShellNavigation.build(this,3)')
    expect(nav).toContain('new Intent(activity,HomeActivity.class)')
    expect(nav).not.toContain('new Intent(activity,PicaBrowseActivity.class)')
    expect(nav).not.toContain('new Intent(activity,SettingsActivity.class)')
    expect(settings).not.toContain('感谢你使用')
  })

  it('keeps Android secondary actions collapsed and ExH failure scoped to its optional surface', () => {
    const browse = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    const detail = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/UnifiedComicDetailActivity.java', 'utf8')
    const shell = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ShellPolicy.java', 'utf8')
    expect(browse).toContain('setSingleChoiceItems(LocalizedText.ui(labels),checked')
    expect(browse).toContain('primaryButton("搜索"')
    expect(browse).toContain('showPicaUnavailable()')
    expect(browse).toContain('showExhProblem(EhCapabilityStore.Snapshot capability)')
    expect(browse).toContain('"ExHentai · 可选扩展"')
    expect(browse).toContain('"部分核心来源不可用"')
    expect(detail).toContain('content.addView(sourceDetails,new LinearLayout.LayoutParams(-2,-2))')
    expect(detail).toContain('rows.add("切换当前网盘 · "+active.label)')
    expect(detail).not.toContain('content.addView(switchRemote)')
    expect(shell).toContain('{"书库","推荐","在线","设置"}')
  })

  it('keeps Android touch targets while reducing default button chrome', () => {
    const ui = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/Ui.java', 'utf8')
    expect(ui).toContain('b.setMinWidth(0)')
    expect(ui).toContain('compact?44:48')
    expect(ui).toContain('compact?10:14')
  })
})
