import fs from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('source-oriented product navigation', () => {
  it('keeps Desktop source/account choices collapsed until requested', () => {
    const html = fs.readFileSync('web/index.html', 'utf8')
    expect(html).toContain('<details class="source-picker">')
    expect(html).toContain('id="search-provider"')
    expect(html).toContain('<option value="exh">ExH（需 E-H 账号权限）</option>')
    expect(html).toContain('<details class="wide account-disclosure">')
    expect(html).toContain('<details class="account-advanced">')
    expect(html).not.toContain('<button data-online-source="pica"')
    expect(html).not.toContain('<button data-online-source="eh"')
    expect(html).not.toContain('<button data-online-source="exh"')
  })

  it('progressively discloses Desktop filters, account, batch and card actions', () => {
    const script = fs.readFileSync('web/eh-account.js', 'utf8')
    expect(script).toContain("summary.textContent = '筛选 ▾'")
    expect(script).toContain("disclosure('官方账号 ▾'")
    expect(script).toContain("disclosure('账号功能 ▾'")
    expect(script).toContain("disclosure('批量操作 ▾'")
    expect(script).toContain("disclosure('更多 ▾', [download, favorite], 'result-action-menu')")
    expect(script).toContain('observeResultCardActions()')
  })

  it('uses one Android source capability authority instead of source-specific button leakage', () => {
    const caps = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/SourceCapabilities.java', 'utf8')
    const browse = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    expect(caps).toContain('ALL=new Source("all","全部来源",false')
    expect(caps).toContain('PICA=new Source("pica","Pica",true')
    expect(caps).toContain('EH=new Source("eh","E-Hentai",true')
    expect(caps).toContain('EXH=new Source("exh","ExHentai",true')
    expect(browse).toContain('SourceCapabilities.byId(sourceMode)')
    expect(browse).toContain('if(source().supportsBrowse)')
    expect(browse).toContain('button("浏览 ▾"')
    expect(browse).not.toContain('Pica 功能')
    expect(browse).not.toContain('全部来源 · E-H 公共浏览无需账号')
  })

  it('routes Android account management through a unified hub while keeping ExH under E-H', () => {
    const browse = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    const hub = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/AccountSourcesActivity.java', 'utf8')
    const manifest = fs.readFileSync('mobile/android-alpha2/app/src/main/AndroidManifest.xml', 'utf8')
    expect(browse).toContain('AccountSourcesActivity.class')
    expect(hub).toContain('"Pica"')
    expect(hub).toContain('"E-Hentai / ExHentai"')
    expect(hub).toContain('SettingsRow.statusLine(this,"ExH"')
    expect(hub).not.toContain('ExHAccountActivity')
    expect(manifest).toContain('.AccountSourcesActivity')
    expect(manifest).toContain('.EhSessionActivity')
  })

  it('keeps normal account pages quiet and moves technical session fields to a focused child page', () => {
    const pica = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaAccountActivity.java', 'utf8')
    const eh = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/EhAccountActivity.java', 'utf8')
    const session = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/EhSessionActivity.java', 'utf8')
    expect(pica).toContain('"账号操作 ▾"')
    expect(pica).toContain('"注册账号"')
    expect(pica).not.toContain('第一次使用 Pica')
    expect(pica).not.toContain('已有账号：填写')
    expect(eh).toContain('"官方账号 ▾"')
    expect(eh).toContain('"账号管理 ▾"')
    expect(eh).toContain('EhSessionActivity.class')
    expect(eh).not.toContain('公共 E-H 搜索、阅读、下载无需账号')
    expect(eh).not.toContain('Android Keystore AES-GCM')
    expect(session).toContain('"更多 ▾"')
    expect(session).toContain('advanced.setVisibility(View.GONE)')
    expect(session).toContain('"验证并保存"')
    expect(session).toContain('"官网登录"')
  })

  it('splits Online and Settings out of Home while sharing one top-level bottom navigator', () => {
    const home = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/HomeActivity.java', 'utf8')
    const online = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    const settings = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/SettingsActivity.java', 'utf8')
    const nav = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ShellNavigation.java', 'utf8')
    expect(home).toContain('ShellNavigation.build(this,current)')
    expect(online).toContain('ShellNavigation.build(this,2)')
    expect(settings).toContain('ShellNavigation.build(this,3)')
    expect(nav).toContain('HomeActivity.class')
    expect(nav).toContain('PicaBrowseActivity.class')
    expect(nav).toContain('SettingsActivity.class')
    expect(home).not.toContain('private void connections()')
    expect(home).not.toContain('private void online()')
    for (const row of ['账号与来源','连接电脑','存储与下载','个性化','数据与缓存','软件更新','关于']) expect(settings).toContain(`"${row}"`)
    expect(settings).not.toContain('Ui.card(')
    expect(settings).not.toContain('感谢你使用')
  })

  it('keeps Android secondary actions collapsed and settings named as a top-level destination', () => {
    const browse = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java', 'utf8')
    const detail = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/UnifiedComicDetailActivity.java', 'utf8')
    const shell = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ShellPolicy.java', 'utf8')
    expect(browse).toContain('setSingleChoiceItems(labels,checked')
    expect(browse).toContain('primaryButton("搜索"')
    expect(browse).toContain('showPicaUnavailable()')
    expect(browse).toContain('showExhUnavailable()')
    expect(detail).toContain('content.addView(sourceDetails,new LinearLayout.LayoutParams(-2,-2))')
    expect(detail).toContain('rows.add("切换当前网盘 · "+active.label)')
    expect(detail).not.toContain('content.addView(switchRemote)')
    expect(shell).toContain('{"书库","推荐","在线","设置"}')
  })

  it('keeps Android touch targets while reducing default button chrome', () => {
    const ui = fs.readFileSync('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/Ui.java', 'utf8')
    expect(ui).toContain('b.setMinWidth(0)')
    expect(ui).toContain('compact?44:48')
    expect(ui).toContain('compact?10:14')
  })
})
