import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const root = path.resolve(import.meta.dirname, '../..')
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

describe('v0.4.7 long-task stability contract', () => {
    it('makes Desktop recommendation generation observable and controllable', () => {
        const service = read('src/library/service.ts')
        const server = read('src/library/server.ts')
        const ui = read('web/alpha8-theme-help.js')
        expect(service).toContain("recommendationBuildControl(action: 'pause' | 'resume' | 'cancel')")
        expect(service).toContain('private async recommendationCheckpoint()')
        expect(service).toContain("state: 'pausing'")
        expect(service).toContain("cancelled ? 'cancelled' : 'failed'")
        expect(server).toContain("input.action === 'pause_build'")
        expect(server).toContain("input.action === 'resume_build'")
        expect(server).toContain("input.action === 'cancel_build'")
        expect(ui).toContain("controlRecommendationBuild('pause_build')")
        expect(ui).toContain("controlRecommendationBuild('resume_build')")
        expect(ui).toContain("controlRecommendationBuild('cancel_build')")
    })

    it('bounds provider failures and preserves the last usable recommendation cycle', () => {
        const sdk = read('src/sdk.ts')
        const retriever = read('src/recommendation-v3/retriever-v3.ts')
        const coordinator = read('src/recommendation-v3/cycle-coordinator-v3.ts')
        expect(sdk).toContain('const PICA_API_TIMEOUT_MS = 15000')
        expect(retriever).toContain("stoppedBy = 'PROVIDER_FAILURE_BUDGET'")
        expect(retriever).toContain('consecutiveProviderFailures >= 3')
        expect(coordinator).toContain("built.readiness === 'FAILED_INSUFFICIENT_POOL'")
        expect(read('test/unit/recommendation-network-recovery.test.ts')).toContain('clears a stale persisted building cycle')
    })

    it('keeps Desktop visual indexing bounded and pauseable without losing pending work', () => {
        const app = read('web/app.js')
        const runtime = read('web/visual-runtime.js')
        const worker = read('web/visual-worker.js')
        const html = read('web/index.html')
        expect(html).toContain('id="visual-index-pause"')
        expect(html).toContain('id="visual-index-resume"')
        expect(app).toContain('async function visualTaskCheckpoint')
        expect(app).toContain("t('visual.cancelled')")
        expect(app).toContain('visualIndexAbortController')
        expect(app).toContain('state.visualIndexAbortController?.abort()')
        expect(runtime).toContain('MODEL_LOAD_TIMEOUT_MS = 120000')
        expect(runtime).toContain('PAGE_ANALYSIS_TIMEOUT_MS = 45000')
        expect(runtime).toContain(
            "new Worker(new URL('./visual-worker.js', import.meta.url)"
        )
        expect(runtime).toContain("signal?.addEventListener('abort'")
        expect(runtime).toContain('terminateVisualWorker(worker)')
        expect(runtime).not.toContain('Promise.race')
        expect(worker).toContain("input.type !== 'analyze'")
        expect(worker).toContain("post(id, 'page-start'")
        expect(worker).toContain('await extractor(sample.url)')
    })

    it('makes favorites sync pauseable at page checkpoints', () => {
        const provider = read('src/services/provider-service.ts')
        const service = read('src/library/service.ts')
        const server = read('src/library/server.ts')
        const app = read('web/app.js')
        expect(provider).toContain('checkpoint?: () => Promise<void>')
        expect(provider).toContain('await checkpoint?.()')
        expect(service).toContain("favoritesSyncControl(action: 'pause' | 'resume' | 'cancel')")
        expect(server).toContain("url.pathname === '/api/v1/sync/control'")
        expect(app).toContain("controlFavoritesSync('pause')")
        expect(app).toContain("controlFavoritesSync('resume')")
        expect(app).toContain("controlFavoritesSync('cancel')")
    })

    it('keeps WebDAV sync checkpointable and local hashing asynchronous', () => {
        const sync = read('src/remote-storage/sync-service.ts')
        const manager = read('src/remote-storage/desktop-manager.ts')
        const cloud = read('web/alpha7-cloud.js')
        expect(sync).toContain('await fs.promises.readFile(file)')
        expect(sync).not.toContain('const data = fs.readFileSync(file)')
        expect(sync).toContain('private checkpoint()')
        expect(sync).toContain("error.name === 'RemoteSyncCancelledError'")
        expect(manager).toContain("syncControl(action: 'pause' | 'resume' | 'cancel')")
        expect(cloud).toContain("controlRemoteSync('pause')")
        expect(cloud).toContain("controlRemoteSync('resume')")
        expect(cloud).toContain("controlRemoteSync('cancel')")
    })

    it('gives Android recommendation, downloads and imports durable pause/resume semantics', () => {
        const taskCenter = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/TaskCenterActivity.java')
        const recJobs = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/NativeRecommendationJobs.java')
        const recEngine = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/NativeRecommendationEngine.java')
        const downloadJobs = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaDownloadJobs.java')
        const downloadWorker = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaDownloadWorker.java')
        const favoriteJobs = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/FavoriteImportJobs.java')
        const bootstrap = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBootstrapWorker.java')
        expect(recJobs).toContain('static void pause(Context context)')
        expect(recJobs).toContain('static void resume(Context context)')
        expect(recJobs).not.toContain('setPaused(context,"recommendation",UNIQUE_NAME,true);WorkManager.getInstance(context.getApplicationContext()).cancelUniqueWork(UNIQUE_NAME)')
        expect(recJobs).toContain('ExistingWorkPolicy.KEEP')
        expect(recEngine).toContain('interface Control { void checkpoint() throws Exception; }')
        expect(recEngine).toContain('consecutivePicaFailures>=3')
        expect(downloadJobs).toContain('static void pause(Context context,String comicId,String episodeId)')
        expect(downloadJobs).toContain('static void resume(Context context,String comicId,String episodeId)')
        expect(downloadWorker).toContain('PhoneDownloadStore.putChapter')
        expect(favoriteJobs).toContain('static void pause(Context context)')
        expect(favoriteJobs).toContain('static void resume(Context context)')
        expect(bootstrap).toContain('正在读取 Pica 收藏 · 第 ')
        expect(taskCenter).toContain('继续会从已经完成并校验的页面续传。')
        expect(taskCenter).toContain('继续会从当前检查点继续本轮生成；上一轮可用推荐不会被覆盖。')
    })

    it('retains mature Desktop download and Android updater controls', () => {
        const web = read('web/app.js')
        const server = read('src/library/server.ts')
        const updater = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/UpdateActivity.java')
        expect(web).toContain('data-job-action="pause"')
        expect(web).toContain('data-job-action="resume"')
        expect(server).toContain('(pause|resume|retry|cancel)')
        expect(updater).toContain('DownloadManager')
        expect(updater).toContain('STALL_MS=120_000L')
    })
})
