import fs from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => fs.readFileSync(path, 'utf8')

describe('Recommendation V4 mobile settings surface', () => {
    it('exposes a visible recommendation and visual-style settings entry', () => {
        const settings = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/SettingsActivity.java')
        const activity = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationStyleActivity.java')
        expect(settings).toContain('推荐与画风')
        expect(settings).toContain('RecommendationStyleActivity.class')
        expect(activity).toContain('DINOv2、全库向量和作者画风原型继续在 Windows 端批量处理')
        expect(activity).toContain('PortableRecommendationPackageStore')
        expect(activity).toContain('RecommendationProfileActivity.class')
        expect(activity).toContain('RecommendationSyncActivity.class')
        expect(activity).toContain('BridgeClient.visualStatus')
        expect(activity).toContain('BridgeClient.updateVisualSettings')
    })

    it('keeps Visual independently switchable with device-local strength and fast mobile batch paging', () => {
        const activity = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationStyleActivity.java')
        const policy = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/MobileVisualPolicyStore.java')
        const engine = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/NativeRecommendationEngine.java')
        const main = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/MainActivity.java')
        const web = read('web/index.html')
        const app = read('web/app.js')
        expect(policy).toContain('STANDARD="STANDARD"')
        expect(policy).toContain('关闭 · 不影响常规推荐')
        expect(activity).toContain('chooseMobileVisualStrength()')
        expect(activity).toContain('Desktop 画风影响强度')
        expect(engine).toContain('MobileVisualPolicyStore.strength(app)')
        expect(web).toContain('启用画风推荐模块（关闭时不影响常规推荐）')
        expect(web).toContain('id="visual-strength"')
        expect(app).toContain("strength: $('#visual-strength').value")
        expect(main).toContain('switchNativeRecommendationBatch(1)')
        expect(main).toContain('renderNativeRecommendationBatch')
        expect(main).not.toContain('NativeRecommendationStore.nextBatch(this);showTab()')
    })

    it('loads heavy recommendation profile/control data off the UI thread and caches hot evidence', () => {
        const profile = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationProfileActivity.java')
        const control = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationControlActivity.java')
        const evidence = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationEvidenceStore.java')
        const localProfile = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationLocalProfile.java')
        const reader = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ReaderProgress.java')
        const home = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/HomeActivity.java')
        expect(profile).toContain('Executors.newSingleThreadExecutor()')
        expect(profile).toContain('private void loadAsync()')
        expect(profile).toContain('worker.submit')
        expect(profile).not.toContain('renderShell();render();')
        expect(control).toContain('Executors.newSingleThreadExecutor()')
        expect(control).toContain('loadedInferred')
        expect(control).toContain('RecommendationLocalProfile.inferred(app,catalog,state)')
        expect(evidence).toContain('cachedEvents')
        expect(evidence).toContain('cachedRaw')
        expect(localProfile).toContain('UnifiedCatalogStore.Snapshot catalog,JSONObject remoteSnapshot')
        expect(reader).toContain('ensureComicMetadata(comic)')
        expect(home).toContain('switchHomeRecommendationBatch')
        expect(home).not.toContain('RecommendationPolicyStore.moveVisibleBatch(this,1);show()')
    })

    it('uses one Home shell for all top-level tabs and distinguishes disclosure hierarchy', () => {
        const shell = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/ShellNavigation.java')
        const home = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/HomeActivity.java')
        const browse = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/PicaBrowseActivity.java')
        const settings = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/SettingsActivity.java')
        const control = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationControlActivity.java')
        const ui = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/Ui.java')
        expect(shell).toContain('new Intent(activity,HomeActivity.class)')
        expect(shell).not.toContain('new Intent(activity,PicaBrowseActivity.class)')
        expect(shell).not.toContain('new Intent(activity,SettingsActivity.class)')
        expect(home).toContain('private void onlineEntry()')
        expect(home).toContain('private void settingsEntry()')
        expect(home).toContain('SettingsRow.row(this,"全部来源"')
        expect(home).toContain('SettingsRow.row(this,"软件更新","检查并安装正式更新"')
        expect(browse).not.toContain('ShellNavigation.build(this,2)')
        expect(settings).not.toContain('ShellNavigation.build(this,3)')
        expect(ui).toContain('static Button foldHeader(')
        expect(control).toContain('Ui.foldHeader(this,(open?"▾ ":"▸ ")+group.label')
        expect(control).toContain('Ui.foldHeader(this,(facetOpen?"▾ ":"▸ ")+facet.label')
    })

    it('uses release-facing Visual language without Beta or Shadow labels', () => {
        const web = read('web/index.html')
        const mobile = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/MobileVisualPolicyStore.java')
        const activity = read('mobile/android-alpha2/app/src/main/java/com/picalibrary/android/RecommendationStyleActivity.java')
        expect(web).toContain('推荐反馈与画风推荐</h3>')
        expect(web).not.toContain('推荐反馈与画风推荐 · Beta')
        expect(web).toContain('仅分析：只计算不改排序')
        expect(web).toContain('参与排序：按所选强度生效')
        expect(web).not.toContain('Shadow：')
        expect(web).not.toContain('Live：')
        expect(mobile).toContain('仅分析 · 不改变本机排序')
        expect(mobile).toContain('参与排序 · ')
        expect(activity).not.toContain('Desktop 画风实验设置')
    })

    it('keeps E-H with Pica in General instead of a separate desktop account section', () => {
        const hub = read('web/alpha8-7-desktop-hub.js')
        expect(hub).not.toContain("['accounts', 'accounts']")
        expect(hub).toContain("panels.get('general').appendChild(ehAccount)")
        expect(hub).toContain("['recommendations', 'recommendations']")
    })
})
