const state={mode:'lite',records:[],authors:[],visible:[],recommendations:null}
const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)]
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm=(v)=>String(v??'').normalize('NFKC').trim().toLocaleLowerCase()
const list=(v)=>String(v??'').split(',').map((x)=>x.trim()).filter(Boolean)
async function api(path,options){const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw new Error(value.error||`HTTP ${response.status}`);return value}
const post=(path,value)=>api(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)})

function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function csvRecords(text){const rows=parseCsv(text),head=rows[0]||[];const at=(row,...names)=>{for(const name of names){const i=head.indexOf(name);if(i>=0)return row[i]||''}return''};return rows.slice(1).flatMap((row)=>{const comicId=at(row,'comic_id','_id','id').trim(),title=at(row,'title').trim();return comicId&&title?[{comicId,title,author:at(row,'author','author_raw'),tags:list(at(row,'tags').replaceAll('|',',')),categories:list(at(row,'categories').replaceAll('|',',')),totalLikes:Number(at(row,'total_likes','totalLikes'))||0,totalViews:Number(at(row,'total_views','totalViews'))||0,updatedAt:at(row,'updated_at'),isFavorite:true}]:[]})}
function deriveAuthors(){const map=new Map;for(const comic of state.records){const raw=String(comic.canonicalAuthor||comic.author||'未知作者').trim(),match=raw.match(/^(.+?)\s*\(([^()]+)\)$/),name=match?match[2].trim():raw,key=norm(name),item=map.get(key)||{id:`lite_${key}`,canonicalName:name,aliases:new Set,circles:new Set,works:0,confidence:match?.8:1,reviewStatus:match?'pending':'approved',evidence:match?'检测到“社团（作者）”格式，请确认作者实体。':'规范化名称一致。'};item.works++;item.aliases.add(raw);if(match)item.circles.add(match[1].trim());map.set(key,item);comic.canonicalAuthor=name}state.authors=[...map.values()].map((x)=>({...x,aliases:[...x.aliases],circles:[...x.circles]})).sort((a,b)=>b.works-a.works)}
function summary(value={}){const items=[['漫画',value.comics??state.records.length],['收藏',value.favorites??state.records.length],['作者',value.authors??state.authors.length],['待审核作者',value.authorsPendingReview??state.authors.filter((x)=>x.reviewStatus==='pending').length],['章节',value.episodes||0],['已下载图片',value.downloadedPictures||0]];$('#summary').innerHTML=items.map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${Number(v).toLocaleString()}</strong></div>`).join('')}
function renderComics(records=state.records){const q=norm($('#filter-text').value),tags=list($('#filter-tag').value).map(norm),sort=$('#sort-mode').value;state.visible=records.filter((c)=>(!q||norm([c.title,c.author,c.canonicalAuthor].join(' ')).includes(q))&&tags.every((t)=>(c.tags||[]).map(norm).includes(t)));state.visible.sort((a,b)=>sort==='likes'?(b.totalLikes||0)-(a.totalLikes||0):sort==='views'?(b.totalViews||0)-(a.totalViews||0):sort==='title'?String(a.title).localeCompare(b.title):String(b.updatedAt||'').localeCompare(a.updatedAt||''));$('#comic-rows').innerHTML=state.visible.map((c)=>`<tr><td><input type="checkbox" data-comic-id="${esc(c.comicId)}"></td><td><strong>${esc(c.title)}</strong></td><td>${esc(c.canonicalAuthor||c.author||'未知')}</td><td>${(c.tags||[]).slice(0,6).map((t)=>`<span class="tag">${esc(t)}</span>`).join('')}</td><td>${Number(c.totalLikes||0).toLocaleString()}</td><td>${esc(c.updatedAt||'')}</td><td>${Number(c.downloadedPictures||0)}/${Number(c.knownPictures||0)}</td></tr>`).join('')}
function renderAuthors(){const pending=$('#pending-only').checked,items=state.authors.filter((a)=>!pending||a.reviewStatus==='pending');$('#author-list').innerHTML='';for(const author of items){const node=$('#author-template').content.cloneNode(true);node.querySelector('.list-item').dataset.authorId=author.id;node.querySelector('.author-name').textContent=author.canonicalName;node.querySelector('.author-meta').textContent=`${author.works} 部作品 · ${author.aliases.join(' / ')} · 置信度 ${Math.round(author.confidence*100)}%`;node.querySelector('.author-evidence').textContent=author.evidence;$('#author-list').append(node)}}
function resultCards(records,target,withReasons=false){$(target).innerHTML=(records||[]).map((item)=>{const comic=item.comic||item;return `<article class="result"><h3>${esc(comic.title)}</h3><p>${esc(comic.canonicalAuthor||comic.author||'未知作者')}</p>${withReasons?`<p>${(item.reasons||[]).slice(0,3).map((r)=>esc(r.value||r)).join(' · ')}</p>`:''}<p>爱心 ${Number(comic.totalLikes||0).toLocaleString()} · 浏览 ${Number(comic.totalViews||0).toLocaleString()}</p><button data-result-download="${esc(comic.comicId)}">加入下载</button></article>`}).join('')}
function downloadJson(name,value){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function selectedIds(){return $$('[data-comic-id]:checked').map((x)=>x.dataset.comicId)}
async function loadJobs(){if(state.mode!=='connected'){ $('#job-list').innerHTML='<article class="notice">连接本地服务后可查看和控制持久化队列。</article>';return}const jobs=await api('/api/v1/downloads');$('#job-list').innerHTML=jobs.map((j)=>{const pct=j.progressTotal?Math.round(j.progressCompleted/j.progressTotal*100):0;return `<article class="list-item"><div class="grow"><strong>${esc(j.comicId)}</strong><p>${j.source} · ${j.runner} · ${j.status} · 重试 ${j.retryCount}</p><div class="progress"><span style="width:${pct}%"></span></div><p>${j.progressCompleted}/${j.progressTotal} · ${Number(j.bytes).toLocaleString()} bytes${j.error?` · ${esc(j.error)}`:''}</p></div><div class="actions">${['QUEUED','PREPARING','RUNNING'].includes(j.status)?`<button data-job-action="pause" data-job-id="${j.id}">暂停</button>`:''}${['PAUSED','FAILED'].includes(j.status)?`<button data-job-action="resume" data-job-id="${j.id}">恢复</button>`:''}${!['COMPLETED','CANCELLED'].includes(j.status)?`<button data-job-action="cancel" data-job-id="${j.id}">取消</button>`:''}</div></article>`}).join('')||'<article class="notice">队列为空。</article>'}

$$('nav [data-view], [data-go]').forEach((b)=>b.addEventListener('click',()=>{const id=b.dataset.view||b.dataset.go;$$('.view').forEach((x)=>x.classList.toggle('active',x.id===id));$$('nav button').forEach((x)=>x.classList.toggle('active',x.dataset.view===id));if(id==='downloads')loadJobs()}))
$$('.tabs').forEach((tabs)=>tabs.addEventListener('click',(e)=>{const id=e.target.dataset.tab;if(!id)return;tabs.querySelectorAll('button').forEach((x)=>x.classList.toggle('active',x===e.target));const section=tabs.parentElement;section.querySelectorAll(':scope > .tab').forEach((x)=>x.classList.toggle('active',x.id===id));if(id==='authors')renderAuthors()}))
$('#apply-filter').onclick=()=>renderComics();$('#pending-only').onchange=renderAuthors
$('#import-button').onclick=async()=>{const file=$('#import-file').files[0];if(!file)return;try{const text=await file.text(),value=file.name.endsWith('.csv')?csvRecords(text):JSON.parse(text),records=Array.isArray(value)?value:value.library?.comics||value.favorites||[];if(state.mode==='connected')await post('/api/v1/import',{records});state.records=records;deriveAuthors();summary();renderComics();renderAuthors();$('#import-result').textContent=`已导入 ${records.length} 条记录。`}catch(e){$('#import-result').textContent=e.message}}
$('#sync-button').onclick=async()=>{try{if(state.mode!=='connected')throw new Error('同步收藏需要连接本地服务。');await post('/api/v1/sync',{});await detect()}catch(e){$('#import-result').textContent=e.message}}
$('#export-plan').onclick=()=>downloadJson('download-plan.json',{schemaVersion:1,createdAt:new Date().toISOString(),comicIds:selectedIds().length?selectedIds():state.visible.map((x)=>x.comicId)})
async function enqueue(ids,source){if(!ids.length)return;if(state.mode!=='connected'){downloadJson('download-plan.json',{schemaVersion:1,createdAt:new Date().toISOString(),comicIds:ids});return}await post('/api/v1/download',{comicIds:ids,source,run:false});await loadJobs()}
$('#queue-selected').onclick=()=>enqueue(selectedIds(),'library')
$('#search-button').onclick=async()=>{try{if(state.mode!=='connected')throw new Error('站内搜索需要连接本地服务。');const records=await post('/api/v1/search',{keyword:$('#search-keyword').value,tags:list($('#search-tags').value),sort:$('#search-sort').value,limit:100});resultCards(records,'#search-results');$('#search-message').textContent=`找到 ${records.length} 条结果。`}catch(e){$('#search-message').textContent=e.message}}
$('#recommend-button').onclick=async()=>{try{let value=state.recommendations;if(state.mode==='connected')value=await post('/api/v1/recommendations',{limit:30,seedCount:8});if(!value)throw new Error('请先导入包含推荐结果的数据包，或连接本地服务。');state.recommendations=value;const prefs=[...(value.profile?.authors||[]),...(value.profile?.tags||[])].slice(0,12);$('#profile').innerHTML=prefs.map((x)=>`<span class="preference">${esc(x.value)} · ${x.count}</span>`).join('');resultCards(value.recommendations,'#recommend-results',true);$('#recommend-message').textContent=`已生成 ${value.recommendations.length} 条推荐。`}catch(e){$('#recommend-message').textContent=e.message}}
;['#search-results','#recommend-results'].forEach((id)=>$(id).onclick=(e)=>{const comicId=e.target.dataset.resultDownload;if(comicId)enqueue([comicId],id.includes('recommend')?'recommendation':'search')})
$('#refresh-jobs').onclick=loadJobs;$('#run-jobs').onclick=async()=>{await post('/api/v1/downloads/run',{});await loadJobs()};$('#job-list').onclick=async(e)=>{if(!e.target.dataset.jobAction)return;await post(`/api/v1/downloads/${e.target.dataset.jobId}/${e.target.dataset.jobAction}`,{});await loadJobs()}
$('#check-updates').onclick=async()=>{try{$('#update-result').textContent=JSON.stringify(await post('/api/v1/maintenance/updates',{}),null,2)}catch(e){$('#update-result').textContent=e.message}}
$('#scan-repair').onclick=async()=>{try{$('#repair-result').textContent=JSON.stringify(await post('/api/v1/maintenance/repair',{}),null,2)}catch(e){$('#repair-result').textContent=e.message}}
$('#run-health').onclick=async()=>{$('#health-result').textContent=JSON.stringify(state.mode==='connected'?await api('/api/v1/status'):{mode:'lite',records:state.records.length,storage:'browser only'},null,2)}
$('#author-list').onclick=async(e)=>{const decision=e.target.dataset.decision;if(!decision)return;const item=e.target.closest('[data-author-id]');if(state.mode==='connected')await post(`/api/v1/authors/${item.dataset.authorId}/decision`,{reviewStatus:decision});else{const author=state.authors.find((x)=>x.id===item.dataset.authorId);if(author)author.reviewStatus=decision}renderAuthors()}
async function detect(){try{const status=await api('/api/v1/status');state.mode='connected';$('#mode').textContent='Connected';state.records=await api('/api/v1/comics');state.authors=await api('/api/v1/authors');summary(status.summary)}catch{state.mode='lite';$('#mode').textContent='Browser Lite';deriveAuthors();summary()}renderComics();renderAuthors()}
detect()
